name: "Download and Build Boost"
description: "Download and Build Boost"
inputs:
  prefix:
    description: 'extra qualifiers'
    required: true
runs:
  using: "composite"
  steps: 
  - id: install-boost
    shell: bash
    run: |
      wget https://github.com/boostorg/boost/releases/download/boost-1.81.0/boost-1.81.0.tar.gz
      tar xvf boost-1.81.0.tar.gz
      cd boost-1.81.0
      ./bootstrap.sh --prefix=${{inputs.prefix}}/ --with-libraries=serialization,program_options,mpi
      echo "using mpi ;" >> project-config.jam
      ./b2 install
