image: ubuntu

build:
  stage: build
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update --fix-missing
    - apt-get install build-essential -y
    - apt-get install git -y
    - apt-get install cmake -y
    - apt-get install libjsoncpp-dev -y
    - apt-get install libgtest-dev -y
    - apt-get install libboost-mpi-dev -y
    - cmake -B _build -S . -DCMAKE_BUILD_TYPE=Release -DUSE_SEQUENTIAL=true -DUSE_MPI=true -DBUILD_DEPS=ON
    - cmake --build _build --config Release
    
    
deploy:
  stage: deploy
  script:
    - cd _build
    - cpack -G ZIP
  artifacts:
    paths:
      - _build/antaresXpansion-*.*.*-*.zip
