image: ubuntu

build:
  stage: build
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update --fix-missing
    - apt-get install build-essential -y
    - apt-get install git -y
    - apt-get install cmake -y
    - apt-get install libjsoncpp-dev -y
    - apt-get install libgtest-dev -y
    - apt-get install libboost-mpi-dev -y    
    - apt-get install libuuid1 uuid-dev libssh2-1 libssh2-1-dev libidn2-dev libidn11 libidn11-dev libcurl4-openssl-dev libb64-dev -y
    - apt-get install libboost-test-dev libboost-filesystem-dev libboost-dev -y
    - cmake -B _build -S . -DCMAKE_BUILD_TYPE=Release -DUSE_SEQUENTIAL=true -DUSE_MPI=true -DBUILD_DEPS=ON
    - cmake --build _build --config Release
    - cd _build
    - cpack -G ZIP
  artifacts:
    paths:
      - _build/antaresXpansion-*.*.*-*.zip