name: antares-xpansion
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.9
  - pip
  - pip:
      - -r requirements-tests.txt