name: antares-xpansion
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/main/linux-64/
  - https://repo.anaconda.com/pkgs/main/win-64/
dependencies:
  - wheel
  - pyinstaller==4.5.1
  - pyyaml
  - dataclasses
  - psutil==5.8.0
  - pytest
  - numpy
  - pytest-cov
  - behave