docs_dir: docs
site_name: Antares Xpansion Documentation
repo_url: https://github.com/AntaresSimulatorTeam/antares-xpansion
edit_uri: edit/doc/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/Icone.png
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.top
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
  #  - navigation.sections
  #   - header.autohide
  #   - toc.separate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - 'Antares ecosystem': 'https://antares-doc.readthedocs.io'
  - 'User guide':
    - 'How does Antares-Xpansion work ?':
        - 'The optimal investment problem in Antares-Xpansion': 'user-guide/optimization-principles/investment-problem.md'
        - 'Mathematical aspects of the investment problem': 'user-guide/optimization-principles/problem-formalization.md'
        - 'Performance history': 'user-guide/performance-history/perf-graphs.ipynb'
    - 'Getting started':
      - 'Installation': 'user-guide/get-started/installation.md'
      - 'Set up an Antares-Xpansion study':
        - 'Prepare the Antares study': 'user-guide/get-started/prepare-a-simulation.md'
        - 'Define the candidates': 'user-guide/get-started/candidate-definition.md'
        - 'Settings of the algorithm': 'user-guide/get-started/settings-definition.md'
      - 'Launch the optimization': 'user-guide/get-started/launching-optimization.md'
      - 'Sensitivity analysis': 'user-guide/get-started/sensitivity-analysis.md'
  - 'Developer guide': 
    - 'Install from sources':
      - 'Introduction': 'developer-guide/install_from_sources/0-INSTALL.md'
      - 'Development requirements': 'developer-guide/install_from_sources/1-Development-requirements.md'
      - 'Dependencies install': 'developer-guide/install_from_sources/2-Dependencies-install.md'
      - 'Build': 'developer-guide/install_from_sources/3-Build.md'
      - 'Tests': 'developer-guide/install_from_sources/4-Tests.md'
      - 'UI creation': 'developer-guide/install_from_sources/5-ui-creation.md'
      - 'Installer creation': 'developer-guide/install_from_sources/6-Installer-creation.md'
    - 'Antares-Xpansion simulation procedure' : 
      - 'Overview' : 'developer-guide/xpansion_steps/0-overview.md'
      - 'Antares optimization problem retrieval' : 'developer-guide/xpansion_steps/1-antares-solver-problem.md'
      - 'Investment problem generation' : 'developer-guide/xpansion_steps/2-problem-modification.md'
  - 'Changelog': 
    - 'Changelog': 'changelog/CHANGELOG.md'
    - 'File format changes': 'changelog/format_changes.md'

plugins:
  - search
  - mkdocs-jupyter:
      execute: False
      show_input: False
      theme: dark
  - bibtex:
      bib_file: 'docs/user-guide/benders.bib'

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - footnotes

copyright: Copyright &copy; 2007 - 2023 RTE