docs_dir: docs
site_name: Antares Xpansion Documentation
repo_url: https://github.com/AntaresSimulatorTeam/antares-xpansion
edit_uri: edit/doc/docs/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/Icone.png
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.top
    - navigation.expand
  #  - navigation.sections
  #   - header.autohide
  #   - toc.separate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - 'Antares ecosystem': 'https://antares-doc.readthedocs.io'
  - 'User guide':
    - 'Problems addressed by Antares-Xpansion': 'user-guide/0-introduction.md'
    - 'Get started':
      - 'Installation': 'user-guide/get-started/0-installation.md'
      - 'Set up an Antares-Xpansion study':
        - 'Prepare the Antares study': 'user-guide/get-started/1-prepare-a-simulation.md'
        - 'Define the candidates': 'user-guide/get-started/2-candidate-definition.md'
        - 'Settings of the algorithm': 'user-guide/get-started/3-settings-definition.md'
      - 'Launch the optimization': 'user-guide/get-started/4-launching-optimization.md'
    - 'The optimization problem in Antares-Xpansion':
      - 'General principles': 'user-guide/optimization-principles/0-optimization-principles.md'
      - 'Formulation of the problem': 'user-guide/optimization-principles/1-problem-formalization.md'
  - 'Developer guide': 
    - 'Install from sources':
      - 'Introduction': 'developer-guide/build/0-INSTALL.md'
      - 'Development requirements': 'developer-guide/build/1-Development-requirements.md'
      - 'Dependencies install': 'developer-guide/build/2-Dependencies-install.md'
      - 'Build': 'developer-guide/build/3-Build.md'
      - 'Tests': 'developer-guide/build/4-Tests.md'
      - 'UI creation': 'developer-guide/build/6-ui-creation.md'
      - 'Installer creation': 'developer-guide/build/5-Installer-creation.md'
    - 'Antares-Xpansion simulation procedure' : 'developer-guide/0-Process.md'
    - 'Optimization problems generation' : 'developer-guide/1-antares-solver.md'
    - 'Modification of problems to introduce investment variables' : 'developer-guide/2-problem-modification.md'
  - 'Changelog': 'CHANGELOG.md'

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

copyright: Copyright &copy; 2007 - 2021 RTE