docs_dir: docs
repo_name: antares-xpansion
site_name: Antares Xpansion Documentation
repo_url: https://github.com/AntaresSimulatorTeam/antares-xpansion
edit_uri: edit/develop/docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/Icone.png
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Overview: 
    - Home: index.md
    - Changelog: overview/CHANGELOG.md
    - File format changes: overview/format_changes.md
    - Documentation guidelines: overview/doc-guidelines.md
  - Reference:
    - reference/index.md
    - Installation: reference/installation.md
    - Input files:
      - reference/inputs/index.md
      - Candidates: reference/inputs/candidates.md
      - Settings: reference/inputs/settings.md
      - Benders: reference/inputs/benders.md
      - Sensitivity analysis: reference/inputs/sensitivity.md
      - Adequacy criterion: reference/inputs/adequacy-criterion.md
    - Running Antares Xpansion: reference/cli.md
    - Output files:
      - reference/outputs/index.md
      - Optimization output: reference/outputs/optimization-output.md
      - Logs: reference/outputs/logs.md
      - Sensitivity analysis: reference/outputs/sensitivity.md
    - Trajectory investment:
      - reference/trajectory-investment/index.md
      - Full trajectory workflow: reference/trajectory-investment/trajectory-workflow.md
      - Launching the workflow: reference/trajectory-investment/orchestration.md
      - User input file parsing: reference/trajectory-investment/user-input.md
      - Multiple problem generation: reference/trajectory-investment/multiple-problem-generation.md
      - Merged weights file generation : reference/trajectory-investment/merge-weights.md
      - Merging annual problems: reference/trajectory-investment/merge-master.md
  - Developer guide:
    - developer-guide/index.md
    - Install from source:
      - developer-guide/install-from-source/index.md
      - Development requirements: developer-guide/install-from-source/development-requirements.md
      - Dependencies install: developer-guide/install-from-source/install-dependencies.md
      - Build: developer-guide/install-from-source/build.md
      - Tests: developer-guide/install-from-source/tests.md
      - Installer creation: developer-guide/install-from-source/installer-creation.md
      - Xpress: developer-guide/install-from-source/xpress.md
    - Simulation procedure:
      - developer-guide/xpansion-steps/index.md
      - Antares optimization problem retrieval: developer-guide/xpansion-steps/antares-solver-problem.md
      - Investment problem generation: developer-guide/xpansion-steps/problem-modification.md


plugins:
  - search
  - mkdocs-jupyter:
      execute: False
      show_input: False
      theme: dark

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML


markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - footnotes
  - pymdownx.arithmatex:
      generic: true

copyright: Copyright &copy; 2007 - 2024 RTE
