docs_dir: docs
repo_name: antares-xpansion
site_name: Antares Xpansion Documentation
repo_url: https://github.com/AntaresSimulatorTeam/antares-xpansion
edit_uri: edit/develop/docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/Icone.png
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.top
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Overview: 
    - Home: index.md
    - Changelog:
      - Changelog: changelog/CHANGELOG.md
      - File format changes: changelog/format_changes.md
  - Reference:
    - Installation: reference/installation.md
    - Input files:
      - reference/inputs/index.md
      - Candidates: reference/inputs/candidates.md
      - Settings: reference/inputs/settings.md
      - Benders: reference/inputs/benders.md
      - Sensitivity analysis: reference/inputs/sensitivity.md
    - Running Antares Xpansion: reference/cli.md
    - Output files:
      - reference/outputs/index.md
      - Logs: reference/outputs/logs.md
      - Sensitivity analysis: reference/outputs/sensitivity.md
    - Adequacy criterion: reference/adequacy-criterion.md
    - Trajectory investment:
      - Trajectory investment problem: user-guide/trajectory-investment/trajectory-problem.md
      - Full trajectory workflow: user-guide/trajectory-investment/trajectory-workflow.md
      - Launching the workflow: user-guide/trajectory-investment/orchestration.md
      - User input file parsing: user-guide/trajectory-investment/user-input.md
      - Multiple problem generation: user-guide/trajectory-investment/multiple-problem-generation.md
      - Merged weights file generation : user-guide/trajectory-investment/merge-weights.md
      - Merging annual problems: user-guide/trajectory-investment/merge-master.md
  - Developer guide:
    - Install from sources:
      - Introduction: developer-guide/install_from_sources/0-INSTALL.md
      - Development requirements: developer-guide/install_from_sources/1-Development-requirements.md
      - Dependencies install: developer-guide/install_from_sources/2-Dependencies-install.md
      - Build: developer-guide/install_from_sources/3-Build.md
      - Tests: developer-guide/install_from_sources/4-Tests.md
      - Installer creation: developer-guide/install_from_sources/5-Installer-creation.md
      - Xpress: developer-guide/install_from_sources/6-Xpress.md
    - Antares-Xpansion simulation procedure:
      - Overview: developer-guide/xpansion_steps/0-overview.md
      - Antares optimization problem retrieval: developer-guide/xpansion_steps/1-antares-solver-problem.md
      - Investment problem generation: developer-guide/xpansion_steps/2-problem-modification.md
    - Contributing: 
      - Documentation guidelines: developer-guide/contributing/doc-guidelines.md


plugins:
  - search
  - mkdocs-jupyter:
      execute: False
      show_input: False
      theme: dark
  - bibtex:
      bib_file: docs/user-guide/benders.bib

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML


markdown_extensions:
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - footnotes
  - pymdownx.arithmatex:
      generic: true

copyright: Copyright &copy; 2007 - 2024 RTE
