FROM antaresrte/xpansion-centos7:1.1.1

CMD ["/bin/bash"]

RUN groupadd --gid 1001 docker && \
    adduser --uid 1001 --ingroup docker --home /home/docker --shell /bin/sh --disabled-password --gecos "" docker

USER docker
RUN mkdir /workspace \
    && chmod a+w /workspace

WORKDIR /workspace

#https://github.com/boxboat/fixuid
RUN USER=docker && \
    GROUP=docker && \
    curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.6.0/fixuid-0.6.0-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - && \
    chown root:root /usr/local/bin/fixuid && \
    chmod 4755 /usr/local/bin/fixuid && \
    mkdir -p /etc/fixuid && \
    printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml

ADD build.sh /workspace
RUN chmod +x /workspace/build.sh
#Every container will run this
ENTRYPOINT ["/workspace/build.sh"]