var searchData=
[
  ['macos_0',['Linux/macOS',['../md_docs_2developer-guide_2install-from-source_2xpress.html#autotoc_md96',1,'']]],
  ['maintenance_1',['Refactoring &amp; Maintenance',['../md_docs_2overview_2CHANGELOG.html#autotoc_md147',1,'']]],
  ['manager_2',['Install with a VCPKG package manager',['../md_docs_2developer-guide_2install-from-source_2install-dependencies.html#autotoc_md71',1,'']]],
  ['mandatory_20arguments_3',['Mandatory arguments',['../md_docs_2reference_2trajectory-investment_2orchestration.html#autotoc_md261',1,'']]],
  ['mapping_20file_4',['5- Creation of a variable / column ID mapping file',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md126',1,'']]],
  ['mark_5findices_5fto_5fkeep_5fpresolve_5',['mark_indices_to_keep_presolve',['../classProblem.html#ac88e46f0d938d1e96195840043d800fc',1,'Problem::mark_indices_to_keep_presolve()'],['../classSolverAbstract.html#a921606b2acfc864c6e76c470064dce40',1,'SolverAbstract::mark_indices_to_keep_presolve()'],['../classSolverXpress.html#a0cfe27d07c07220bdce1368e220be826',1,'SolverXpress::mark_indices_to_keep_presolve()'],['../classSolverCbc.html#a89efc60109ea87a1d2f4090160dcd1ee',1,'SolverCbc::mark_indices_to_keep_presolve()'],['../classSolverClp.html#a9e616f254e74d5dcc6dad240514e991f',1,'SolverClp::mark_indices_to_keep_presolve()'],['../classNOOPSolver.html#aaa067994b51cd788f40541dc7316ab60',1,'NOOPSolver::mark_indices_to_keep_presolve()']]],
  ['markers_6',['Markers',['../md_docs_2agents_2testing.html#autotoc_md57',1,'']]],
  ['markers_7',['markers',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md291',1,'Test markers'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md302',1,'Test markers']]],
  ['master_8',['Master',['../classxpansion_1_1logger_1_1Master.html',1,'xpansion::logger']]],
  ['master_20merger_20executable_9',['Usage of the master merger executable',['../md_docs_2reference_2trajectory-investment_2merge-master.html#autotoc_md244',1,'']]],
  ['master_20merger_20info_20file_10',['Master merger info file',['../md_docs_2reference_2trajectory-investment_2merge-master.html#autotoc_md246',1,'']]],
  ['master_20problem_11',['4- Creation of master problem',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md125',1,'']]],
  ['master_20problem_20formulation_12',['Master problem formulation',['../md_docs_2reference_2outputs_2others.html#autotoc_md238',1,'']]],
  ['master_20problems_20of_20annual_20xpansion_20studies_13',['Merging the master problems of annual Xpansion studies',['../md_docs_2reference_2trajectory-investment_2merge-master.html',1,'']]],
  ['masterfilenotfound_14',['MasterFileNotFound',['../classantares__xpansion_1_1resume__study_1_1ResumeStudy_1_1MasterFileNotFound.html',1,'antares_xpansion::resume_study::ResumeStudy']]],
  ['mastergeneration_15',['MasterGeneration',['../classMasterGeneration.html',1,'']]],
  ['mastergenerationtest_16',['MasterGenerationTest',['../classMasterGenerationTest.html',1,'']]],
  ['masterloggertest_17',['MasterLoggerTest',['../classMasterLoggerTest.html',1,'']]],
  ['masterproblembuilder_18',['MasterProblemBuilder',['../classMasterProblemBuilder.html',1,'']]],
  ['masterupdatebase_19',['MasterUpdateBase',['../classOuterloop_1_1MasterUpdateBase.html',1,'Outerloop']]],
  ['masterupdatebasetest_20',['MasterUpdateBaseTest',['../classMasterUpdateBaseTest.html',1,'']]],
  ['mathlogger_21',['MathLogger',['../structMathLogger.html',1,'']]],
  ['mathloggerbase_22',['MathLoggerBase',['../structMathLoggerBase.html',1,'']]],
  ['mathloggerbaseexternalloop_23',['MathLoggerBaseExternalLoop',['../structMathLoggerBaseExternalLoop.html',1,'']]],
  ['mathloggerbehaviour_24',['MathLoggerBehaviour',['../structMathLoggerBehaviour.html',1,'']]],
  ['mathloggerbendersbybatch_25',['MathLoggerBendersByBatch',['../structMathLoggerBendersByBatch.html',1,'']]],
  ['mathloggerbendersbybatchexternalloop_26',['MathLoggerBendersByBatchExternalLoop',['../structMathLoggerBendersByBatchExternalLoop.html',1,'']]],
  ['mathloggerdriver_27',['MathLoggerDriver',['../classMathLoggerDriver.html',1,'']]],
  ['mathloggerexternalloopspecific_28',['MathLoggerExternalLoopSpecific',['../structMathLoggerExternalLoopSpecific.html',1,'']]],
  ['mathloggerfactory_29',['MathLoggerFactory',['../classMathLoggerFactory.html',1,'']]],
  ['mathloggerfile_30',['MathLoggerFile',['../classMathLoggerFile.html',1,'']]],
  ['mathloggerimplementation_31',['MathLoggerImplementation',['../classMathLoggerImplementation.html',1,'']]],
  ['mathloggerostream_32',['MathLoggerOstream',['../classMathLoggerOstream.html',1,'']]],
  ['max_5fcumulative_5finvestment_5fper_5fnode_20tt_33',['&lt;tt&gt;type: max_cumulative_investment_per_node&lt;/tt&gt;',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md275',1,'']]],
  ['max_5fcumulative_5fretirement_5fper_5fnode_20tt_34',['&lt;tt&gt;type: max_cumulative_retirement_per_node&lt;/tt&gt;',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md277',1,'']]],
  ['max_5finvestment_5fper_5fnode_5fper_5fcandidate_20tt_35',['&lt;tt&gt;type: max_investment_per_node_per_candidate&lt;/tt&gt;',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md274',1,'']]],
  ['max_5fretirement_5fper_5fnode_5fper_5fcandidate_20tt_36',['&lt;tt&gt;type: max_retirement_per_node_per_candidate&lt;/tt&gt;',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md276',1,'']]],
  ['maxitervalueerror_37',['MaxIterValueError',['../classantares__xpansion_1_1input__checker_1_1MaxIterValueError.html',1,'antares_xpansion::input_checker']]],
  ['maxunitsandmaxinvestmentarenullsimultaneously_38',['MaxUnitsAndMaxInvestmentAreNullSimultaneously',['../classantares__xpansion_1_1input__checker_1_1MaxUnitsAndMaxInvestmentAreNullSimultaneously.html',1,'antares_xpansion::input_checker']]],
  ['maxunitsandmaxinvestmentnonnullsimultaneously_39',['MaxUnitsAndMaxInvestmentNonNullSimultaneously',['../classantares__xpansion_1_1input__checker_1_1MaxUnitsAndMaxInvestmentNonNullSimultaneously.html',1,'antares_xpansion::input_checker']]],
  ['mcyearnotinactiveyearslisterror_40',['McYearNotInActiveYearsListError',['../classYearlyWeightsWriter_1_1McYearNotInActiveYearsListError.html',1,'YearlyWeightsWriter']]],
  ['merge_5flocal_5fsolver_41',['merge_local_solver',['../classAbstractMergeMPS.html#a5b71702ecca3ab9b5147169a297658af',1,'AbstractMergeMPS']]],
  ['mergemasterdata_42',['MergeMasterData',['../classdriver__merge__master_1_1MergeMasterData.html',1,'driver_merge_master']]],
  ['mergemasterdriver_43',['MergeMasterDriver',['../classdriver__merge__master_1_1MergeMasterDriver.html',1,'driver_merge_master']]],
  ['mergemasterexecutionerror_44',['MergeMasterExecutionError',['../classdriver__merge__master_1_1MergeMasterDriver_1_1MergeMasterExecutionError.html',1,'driver_merge_master::MergeMasterDriver']]],
  ['mergemasterexeerror_45',['MergeMasterExeError',['../classdriver__merge__master_1_1MergeMasterDriver_1_1MergeMasterExeError.html',1,'driver_merge_master::MergeMasterDriver']]],
  ['mergemasterinputerror_46',['MergeMasterInputError',['../classdriver__merge__master_1_1MergeMasterDriver_1_1MergeMasterInputError.html',1,'driver_merge_master::MergeMasterDriver']]],
  ['mergemastersubproblemmps_47',['MergeMasterSubproblemMPS',['../classMergeMasterSubproblemMPS.html',1,'']]],
  ['mergemastertrajectorymps_48',['MergeMasterTrajectoryMPS',['../classMergeMasterTrajectoryMPS.html',1,'']]],
  ['mergempstest_49',['MergeMPSTest',['../classMergeMPSTest.html',1,'']]],
  ['merger_20executable_50',['Usage of the master merger executable',['../md_docs_2reference_2trajectory-investment_2merge-master.html#autotoc_md244',1,'']]],
  ['merger_20info_20file_51',['Master merger info file',['../md_docs_2reference_2trajectory-investment_2merge-master.html#autotoc_md246',1,'']]],
  ['mergeweightsdata_52',['MergeWeightsData',['../classdriver__merge__weights_1_1MergeWeightsData.html',1,'driver_merge_weights']]],
  ['mergeweightsdriver_53',['MergeWeightsDriver',['../classdriver__merge__weights_1_1MergeWeightsDriver.html',1,'driver_merge_weights']]],
  ['mergeweightsexecutionerror_54',['MergeWeightsExecutionError',['../classdriver__merge__weights_1_1MergeWeightsDriver_1_1MergeWeightsExecutionError.html',1,'driver_merge_weights::MergeWeightsDriver']]],
  ['mergeweightsexeerror_55',['MergeWeightsExeError',['../classdriver__merge__weights_1_1MergeWeightsDriver_1_1MergeWeightsExeError.html',1,'driver_merge_weights::MergeWeightsDriver']]],
  ['mergeweightsinputerror_56',['MergeWeightsInputError',['../classdriver__merge__weights_1_1MergeWeightsDriver_1_1MergeWeightsInputError.html',1,'driver_merge_weights::MergeWeightsDriver']]],
  ['mergeweightstrajectory_57',['MergeWeightsTrajectory',['../classMergeWeightsTrajectory.html',1,'']]],
  ['merging_20the_20master_20problems_20of_20annual_20xpansion_20studies_58',['Merging the master problems of annual Xpansion studies',['../md_docs_2reference_2trajectory-investment_2merge-master.html',1,'']]],
  ['min_5finvestment_5fper_5fcandidate_5fper_5fnode_20tt_59',['&lt;tt&gt;type: min_investment_per_candidate_per_node&lt;/tt&gt;',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md278',1,'']]],
  ['min_5fretirement_5fper_5fcandidate_5fper_5fnode_20tt_60',['&lt;tt&gt;type: min_retirement_per_candidate_per_node&lt;/tt&gt;',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md279',1,'']]],
  ['mini_5finstance_5finfeasible_61',['mini_instance_INFEASIBLE',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md289',1,'mini_instance_INFEASIBLE'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md300',1,'mini_instance_INFEASIBLE']]],
  ['mini_5finstance_5flp_5fdefault_62',['mini_instance_LP_default',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md286',1,'mini_instance_LP_default'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md297',1,'mini_instance_LP_default']]],
  ['mini_5finstance_5fmip_5fdefault_63',['mini_instance_MIP_default',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md287',1,'mini_instance_MIP_default'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md298',1,'mini_instance_MIP_default']]],
  ['mini_5finstance_5funbounded_64',['mini_instance_UNBOUNDED',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md288',1,'mini_instance_UNBOUNDED'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md299',1,'mini_instance_UNBOUNDED']]],
  ['mini_5fnetwork_5fdefault_65',['mini_network_default',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md284',1,'mini_network_default'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md295',1,'mini_network_default']]],
  ['mini_5fnetwork_5fslave_5fweight_66',['mini_network_slave_weight',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md285',1,'mini_network_slave_weight'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md296',1,'mini_network_slave_weight']]],
  ['mismatchedparameters_67',['MismatchedParameters',['../classProblemGenerationOptions_1_1MismatchedParameters.html',1,'ProblemGenerationOptions']]],
  ['missingantaresoutput_68',['MissingAntaresOutput',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1MissingAntaresOutput.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['missingfile_69',['MissingFile',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1MissingFile.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['missingparameters_70',['MissingParameters',['../classProblemGenerationOptions_1_1MissingParameters.html',1,'ProblemGenerationOptions']]],
  ['missingsimulationname_71',['MissingSimulationName',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1MissingSimulationName.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['modification_20of_20mps_20file_72',['2- Modification of .mps file',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md121',1,'']]],
  ['modification_20of_20weekly_20problems_20with_20tt_20lp_5fnamer_20tt_73',['Modification of weekly problems with &lt;tt&gt;lp_namer&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md119',1,'']]],
  ['modifications_20for_20em_20satellite_20problems_20em_74',['Modifications for &lt;em&gt;satellite problems&lt;/em&gt;',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md123',1,'']]],
  ['mpi_20related_20issues_20please_20use_20the_20other_20ones_75',['⚠️ Single-file versions in Ubuntu are known to have MPI-related issues. Please use the other ones.',['../md_docs_2overview_2CHANGELOG.html#autotoc_md163',1,'']]],
  ['mpicommunicationstrategy_76',['MpiCommunicationStrategy',['../classMpiCommunicationStrategy.html',1,'']]],
  ['mps_20file_77',['2- Modification of .mps file',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md121',1,'']]],
  ['mps_20tt_20file_78',['&lt;tt&gt;variables.txt&lt;/tt&gt; file for each &lt;tt&gt;.mps&lt;/tt&gt; file',['../md_docs_2developer-guide_2xpansion-steps_2antares-solver-problem.html#autotoc_md105',1,'']]],
  ['mps_20tt_20files_20for_20the_20weekly_20optimization_20problems_79',['&lt;tt&gt;.mps&lt;/tt&gt; files for the weekly optimization problems',['../md_docs_2developer-guide_2xpansion-steps_2antares-solver-problem.html#autotoc_md104',1,'']]],
  ['mpsfileproblemprovideradapter_80',['MPSFileProblemProviderAdapter',['../classMPSFileProblemProviderAdapter.html',1,'']]],
  ['mpstxtwritertest_81',['MpsTxtWriterTest',['../classMpsTxtWriterTest.html',1,'']]],
  ['mpszipfileexception_82',['MpsZipFileException',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorDriver_1_1MpsZipFileException.html',1,'antares_xpansion::problem_generator_driver::ProblemGeneratorDriver']]],
  ['multiple_20problem_20generation_83',['Multiple problem generation',['../md_docs_2reference_2trajectory-investment_2multiple-problem-generation.html',1,'']]],
  ['multiplealreadyinstalledcapacitydetectedforlink_84',['MultipleAlreadyInstalledCapacityDetectedForLink',['../classActiveLinksBuilder_1_1MultipleAlreadyInstalledCapacityDetectedForLink.html',1,'ActiveLinksBuilder']]],
  ['multiplealreadyinstalledprofiledetectedforlink_85',['MultipleAlreadyInstalledProfileDetectedForLink',['../classActiveLinksBuilder_1_1MultipleAlreadyInstalledProfileDetectedForLink.html',1,'ActiveLinksBuilder']]],
  ['multiplelinkiddetectedforlink_86',['MultipleLinkIddetectedForLink',['../classActiveLinksBuilder_1_1MultipleLinkIddetectedForLink.html',1,'ActiveLinksBuilder']]],
  ['multipleproblemgeneration_87',['MultipleProblemGeneration',['../classMultipleProblemGeneration.html',1,'']]],
  ['multipleproblemgenerationdata_88',['MultipleProblemGenerationData',['../classdriver__multiple__problem__gen_1_1MultipleProblemGenerationData.html',1,'driver_multiple_problem_gen']]],
  ['multipleproblemgenerationdriver_89',['MultipleProblemGenerationDriver',['../classdriver__multiple__problem__gen_1_1MultipleProblemGenerationDriver.html',1,'driver_multiple_problem_gen']]],
  ['multipleproblemgenerationexecutionerror_90',['MultipleProblemGenerationExecutionError',['../classdriver__multiple__problem__gen_1_1MultipleProblemGenerationDriver_1_1MultipleProblemGenerationExecutionError.html',1,'driver_multiple_problem_gen::MultipleProblemGenerationDriver']]],
  ['multipleproblemgenerationexeerror_91',['MultipleProblemGenerationExeError',['../classdriver__multiple__problem__gen_1_1MultipleProblemGenerationDriver_1_1MultipleProblemGenerationExeError.html',1,'driver_multiple_problem_gen::MultipleProblemGenerationDriver']]],
  ['multipleproblemgenerationexeoptions_92',['MultipleProblemGenerationExeOptions',['../classMultipleProblemGenerationExeOptions.html',1,'']]],
  ['multiply_5fobj_5fby_5fweight_5ffactor_93',['multiply_obj_by_weight_factor',['../classAbstractMergeMPS.html#a3564177205bdc0a9231ce4fef65c31aa',1,'AbstractMergeMPS']]]
];
