var searchData=
[
  ['m_20method_20benders_20benders_5fby_5fbatch_20mergemps_20tt_0',['&lt;tt&gt;-m, --method {benders, benders_by_batch, mergeMPS}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md138',1,'']]],
  ['mainwidget_1',['MainWidget',['../classantares-xpansion-ui_1_1MainWidget.html',1,'antares-xpansion-ui']]],
  ['manager_2',['Install with a package manager',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md66',1,'']]],
  ['mapgenerator_3',['MapGenerator',['../classCatch_1_1Generators_1_1MapGenerator.html',1,'Catch::Generators']]],
  ['mapping_20file_4',['5- Creation of a variable / column ID mapping file',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md102',1,'']]],
  ['markers_5',['markers',['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md225',1,'Test markers'],['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md214',1,'Test markers']]],
  ['master_6',['Master',['../classxpansion_1_1logger_1_1Master.html',1,'xpansion::logger']]],
  ['master_20problem_7',['4- Creation of master problem',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md101',1,'']]],
  ['master_20tt_8',['&lt;tt&gt;master&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md177',1,'']]],
  ['masterfilenotfound_9',['MasterFileNotFound',['../classantares__xpansion_1_1resume__study_1_1ResumeStudy_1_1MasterFileNotFound.html',1,'antares_xpansion::resume_study::ResumeStudy']]],
  ['mastergeneration_10',['MasterGeneration',['../classMasterGeneration.html',1,'']]],
  ['masterloggertest_11',['MasterLoggerTest',['../classMasterLoggerTest.html',1,'']]],
  ['masterproblembuilder_12',['MasterProblemBuilder',['../classMasterProblemBuilder.html',1,'']]],
  ['masterupdatebase_13',['MasterUpdateBase',['../classMasterUpdateBase.html',1,'']]],
  ['masterupdatebasetest_14',['MasterUpdateBaseTest',['../classMasterUpdateBaseTest.html',1,'']]],
  ['matchallof_15',['MatchAllOf',['../structCatch_1_1Matchers_1_1Impl_1_1MatchAllOf.html',1,'Catch::Matchers::Impl']]],
  ['matchanyof_16',['MatchAnyOf',['../structCatch_1_1Matchers_1_1Impl_1_1MatchAnyOf.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_17',['MatcherBase',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_3c_20argt_20_3e_18',['MatcherBase&lt; ArgT &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_3c_20double_20_3e_19',['MatcherBase&lt; double &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_3c_20std_3a_3aexception_20_3e_20',['MatcherBase&lt; std::exception &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_3c_20std_3a_3astring_20_3e_21',['MatcherBase&lt; std::string &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_3c_20std_3a_3avector_3c_20t_20_3e_20_3e_22',['MatcherBase&lt; std::vector&lt; T &gt; &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_23',['MatcherMethod',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_3c_20argt_20_3e_24',['MatcherMethod&lt; ArgT &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_3c_20double_20_3e_25',['MatcherMethod&lt; double &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_3c_20std_3a_3aexception_20_3e_26',['MatcherMethod&lt; std::exception &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_3c_20std_3a_3astring_20_3e_27',['MatcherMethod&lt; std::string &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_3c_20std_3a_3avector_3c_20t_20_3e_20_3e_28',['MatcherMethod&lt; std::vector&lt; T &gt; &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_3c_20t_20_3e_29',['MatcherMethod&lt; T &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matcheruntypedbase_30',['MatcherUntypedBase',['../classCatch_1_1Matchers_1_1Impl_1_1MatcherUntypedBase.html',1,'Catch::Matchers::Impl']]],
  ['matchnotof_31',['MatchNotOf',['../structCatch_1_1Matchers_1_1Impl_1_1MatchNotOf.html',1,'Catch::Matchers::Impl']]],
  ['mathematical_20aspects_20of_20the_20investment_20problem_32',['Mathematical aspects of the investment problem',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html',1,'']]],
  ['mathematical_20formulation_20of_20the_20sensitivity_20analysis_20problem_33',['Mathematical formulation of the sensitivity analysis problem',['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md163',1,'']]],
  ['mathlogger_34',['MathLogger',['../structMathLogger.html',1,'']]],
  ['mathloggerbase_35',['MathLoggerBase',['../structMathLoggerBase.html',1,'']]],
  ['mathloggerbaseexternalloop_36',['MathLoggerBaseExternalLoop',['../structMathLoggerBaseExternalLoop.html',1,'']]],
  ['mathloggerbehaviour_37',['MathLoggerBehaviour',['../structMathLoggerBehaviour.html',1,'']]],
  ['mathloggerbendersbybatch_38',['MathLoggerBendersByBatch',['../structMathLoggerBendersByBatch.html',1,'']]],
  ['mathloggerbendersbybatchexternalloop_39',['MathLoggerBendersByBatchExternalLoop',['../structMathLoggerBendersByBatchExternalLoop.html',1,'']]],
  ['mathloggerdriver_40',['MathLoggerDriver',['../classMathLoggerDriver.html',1,'']]],
  ['mathloggerfactory_41',['MathLoggerFactory',['../classMathLoggerFactory.html',1,'']]],
  ['mathloggerfile_42',['MathLoggerFile',['../classMathLoggerFile.html',1,'']]],
  ['mathloggerimplementation_43',['MathLoggerImplementation',['../classMathLoggerImplementation.html',1,'']]],
  ['mathloggerostream_44',['MathLoggerOstream',['../classMathLoggerOstream.html',1,'']]],
  ['max_20investment_20tt_45',['&lt;tt&gt;max-investment&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md115',1,'']]],
  ['max_20units_20tt_46',['&lt;tt&gt;max-units&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md117',1,'']]],
  ['max_5fiteration_20tt_47',['&lt;tt&gt;max_iteration&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md174',1,'']]],
  ['maxitervalueerror_48',['MaxIterValueError',['../classantares__xpansion_1_1input__checker_1_1MaxIterValueError.html',1,'antares_xpansion::input_checker']]],
  ['maxunitsandmaxinvestmentarenullsimultaneously_49',['MaxUnitsAndMaxInvestmentAreNullSimultaneously',['../classantares__xpansion_1_1input__checker_1_1MaxUnitsAndMaxInvestmentAreNullSimultaneously.html',1,'antares_xpansion::input_checker']]],
  ['maxunitsandmaxinvestmentnonnullsimultaneously_50',['MaxUnitsAndMaxInvestmentNonNullSimultaneously',['../classantares__xpansion_1_1input__checker_1_1MaxUnitsAndMaxInvestmentNonNullSimultaneously.html',1,'antares_xpansion::input_checker']]],
  ['mergemps_51',['MergeMPS',['../classMergeMPS.html',1,'']]],
  ['mergemps_20tt_52',['&lt;tt&gt;-m, --method {benders, benders_by_batch, mergeMPS}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md138',1,'']]],
  ['messagebuilder_53',['MessageBuilder',['../structCatch_1_1MessageBuilder.html',1,'Catch']]],
  ['messageinfo_54',['MessageInfo',['../structCatch_1_1MessageInfo.html',1,'Catch']]],
  ['messagestream_55',['MessageStream',['../structCatch_1_1MessageStream.html',1,'Catch']]],
  ['method_56',['Description of the method',['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md162',1,'']]],
  ['method_20benders_20benders_5fby_5fbatch_20mergemps_20tt_57',['&lt;tt&gt;-m, --method {benders, benders_by_batch, mergeMPS}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md138',1,'']]],
  ['mini_5finstance_5finfeasible_58',['mini_instance_infeasible',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md212',1,'mini_instance_INFEASIBLE'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md223',1,'mini_instance_INFEASIBLE']]],
  ['mini_5finstance_5flp_5fdefault_59',['mini_instance_lp_default',['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md220',1,'mini_instance_LP_default'],['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md209',1,'mini_instance_LP_default']]],
  ['mini_5finstance_5fmip_5fdefault_60',['mini_instance_mip_default',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md210',1,'mini_instance_MIP_default'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md221',1,'mini_instance_MIP_default']]],
  ['mini_5finstance_5funbounded_61',['mini_instance_unbounded',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md211',1,'mini_instance_UNBOUNDED'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md222',1,'mini_instance_UNBOUNDED']]],
  ['mini_5fnetwork_5fdefault_62',['mini_network_default',['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md218',1,'mini_network_default'],['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md207',1,'mini_network_default']]],
  ['mini_5fnetwork_5fslave_5fweight_63',['mini_network_slave_weight',['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md219',1,'mini_network_slave_weight'],['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md208',1,'mini_network_slave_weight']]],
  ['mismatchedparameters_64',['MismatchedParameters',['../classProblemGenerationOptions_1_1MismatchedParameters.html',1,'ProblemGenerationOptions']]],
  ['missingantaresoutput_65',['MissingAntaresOutput',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1MissingAntaresOutput.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['missingfile_66',['MissingFile',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1MissingFile.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['missingparameters_67',['MissingParameters',['../classProblemGenerationOptions_1_1MissingParameters.html',1,'ProblemGenerationOptions']]],
  ['missingsimulationname_68',['MissingSimulationName',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1MissingSimulationName.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['modification_20of_20mps_20file_69',['2- Modification of .mps file',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md97',1,'']]],
  ['modification_20of_20weekly_20problems_20with_20tt_20lp_5fnamer_20tt_70',['Modification of weekly problems with &lt;tt&gt;lp_namer&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md95',1,'']]],
  ['modifications_20for_20em_20satellite_20problems_20em_71',['Modifications for &lt;em&gt;satellite problems&lt;/em&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md99',1,'']]],
  ['monte_20carlo_20year_72',['Using different profiles depending on the Monte-Carlo year',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md122',1,'']]],
  ['mps_20file_73',['2- Modification of .mps file',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md97',1,'']]],
  ['mps_20tt_20file_74',['&lt;tt&gt;variables.txt&lt;/tt&gt; file for each &lt;tt&gt;.mps&lt;/tt&gt; file',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md90',1,'']]],
  ['mps_20tt_20files_20for_20the_20weekly_20optimization_20problems_75',['&lt;tt&gt;.mps&lt;/tt&gt; files for the weekly optimization problems',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md89',1,'']]],
  ['mpsfileproblemprovideradapter_76',['MPSFileProblemProviderAdapter',['../classMPSFileProblemProviderAdapter.html',1,'']]],
  ['mpsfilewriter_77',['MPSFileWriter',['../classMPSFileWriter.html',1,'']]],
  ['mpstxtwritertest_78',['MpsTxtWriterTest',['../classMpsTxtWriterTest.html',1,'']]],
  ['mpszipfileexception_79',['MpsZipFileException',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorDriver_1_1MpsZipFileException.html',1,'antares_xpansion::problem_generator_driver::ProblemGeneratorDriver']]],
  ['multiplealreadyinstalledcapacitydetectedforlink_80',['MultipleAlreadyInstalledCapacityDetectedForLink',['../classActiveLinksBuilder_1_1MultipleAlreadyInstalledCapacityDetectedForLink.html',1,'ActiveLinksBuilder']]],
  ['multiplealreadyinstalledprofiledetectedforlink_81',['MultipleAlreadyInstalledProfileDetectedForLink',['../classActiveLinksBuilder_1_1MultipleAlreadyInstalledProfileDetectedForLink.html',1,'ActiveLinksBuilder']]],
  ['multiplelinkiddetectedforlink_82',['MultipleLinkIddetectedForLink',['../classActiveLinksBuilder_1_1MultipleLinkIddetectedForLink.html',1,'ActiveLinksBuilder']]],
  ['mw_20tt_83',['&lt;tt&gt;annual-cost-per-mw&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md114',1,'']]]
];
