var searchData=
[
  ['a_20variable_20column_20id_20mapping_20file_0',['5- Creation of a variable / column ID mapping file',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md123',1,'']]],
  ['a_20vcpkg_20package_20manager_1',['Install with a VCPKG package manager',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md75',1,'']]],
  ['act_2',['act',['../classact.html',1,'']]],
  ['activelink_3',['ActiveLink',['../classActiveLink.html',1,'']]],
  ['activelinksbuilder_4',['ActiveLinksBuilder',['../classActiveLinksBuilder.html',1,'']]],
  ['add_5fcols_5',['add_cols',['../classProblem.html#a3a39dd85d31f7a5fe895fe8d119a7e69',1,'Problem::add_cols()'],['../classSolverAbstract.html#a4a4dacaf5af0d774302be7487f194f42',1,'SolverAbstract::add_cols()'],['../classSolverCbc.html#a4d0812f1777b1a4e43a71ed0d0e8c3f3',1,'SolverCbc::add_cols()'],['../classSolverClp.html#ab95a20cf2acc6d7a365a63d7e0923f49',1,'SolverClp::add_cols()'],['../classSolverXpress.html#a8e031ade7772323f466f16f3d9e45952',1,'SolverXpress::add_cols()'],['../classNOOPSolver.html#a1580de6c19d2196a778ed146cf85d96d',1,'NOOPSolver::add_cols()']]],
  ['add_5fcut_6',['add_cut',['../classWorkerMaster.html#a1278325052f29d3a4b145052a23761ad',1,'WorkerMaster']]],
  ['add_5fcut_5fby_5fiter_7',['add_cut_by_iter',['../classWorkerMaster.html#a8762f8cb421031c5333c2e024044238c',1,'WorkerMaster']]],
  ['add_5fdynamic_5fcut_8',['add_dynamic_cut',['../classWorkerMaster.html#ad82d7509516e2ddb7ed5d43e9b246f3e',1,'WorkerMaster']]],
  ['add_5fname_9',['add_name',['../classProblem.html#a2fd6e04f639afc967adf2f1a3d3d4b85',1,'Problem::add_name()'],['../classSolverAbstract.html#afc4ceb13f60ec7f53cdc166dd70baee6',1,'SolverAbstract::add_name()'],['../classSolverCbc.html#a0990733602db4b38284455ef0aa0349a',1,'SolverCbc::add_name()'],['../classSolverClp.html#a8c52ca73a3482eee8e402dd9d95c1134',1,'SolverClp::add_name()'],['../classSolverXpress.html#a3d66403a0b9cad3c4988c5f943fcfc57',1,'SolverXpress::add_name()'],['../classNOOPSolver.html#ae32c377fdb30d6d8969dc26f955d358e',1,'NOOPSolver::add_name()']]],
  ['add_5frows_10',['add_rows',['../classProblem.html#a8fb8c92a38162a74023e798e9e824c80',1,'Problem::add_rows()'],['../classSolverAbstract.html#a7cfec83d515d78f875e45c4743668be2',1,'SolverAbstract::add_rows()'],['../classSolverCbc.html#af74f4f01aef4f5bf99971d91e2000a10',1,'SolverCbc::add_rows()'],['../classSolverClp.html#a94232131fe77df5b58b539e6fd0b10a9',1,'SolverClp::add_rows()'],['../classSolverXpress.html#aa3387353e9219c23e22297b2943657dc',1,'SolverXpress::add_rows()'],['../classNOOPSolver.html#a8e091428888e75fcba2e8feb5a127054',1,'NOOPSolver::add_rows()']]],
  ['add_5fstream_11',['add_stream',['../classSolverAbstract.html#a4b0cf85b1d8d2b63c3bc8ef62ed036d9',1,'SolverAbstract']]],
  ['additional_20candidate_20constraints_12',['3- Read additional candidate constraints',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md121',1,'']]],
  ['additional_20characteristics_20for_20links_20of_20investment_20candidates_13',['Additional characteristics for links of investment candidates',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md184',1,'']]],
  ['additional_20constraints_20tt_14',['&lt;tt&gt;additional-constraints&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md205',1,'']]],
  ['additional_5fconstraints_15',['additional_constraints',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader.html#a4144519a671a579b2440aa61a06bf6b1',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['additionalconstraint_16',['additionalconstraint',['../classAdditionalConstraint.html',1,'AdditionalConstraint'],['../classAdditionalConstraint.html#a6c15a4ee5ecfa901ba8a9e8d60383660',1,'AdditionalConstraint::AdditionalConstraint()=default'],['../classAdditionalConstraint.html#aac25a7a8f92a5ee43559630a5f4bcca6',1,'AdditionalConstraint::AdditionalConstraint(std::string sectionName_p, std::string constraintName_p, std::string sign_p, double rhs_p)']]],
  ['additionalconstraints_17',['additionalconstraints',['../classAdditionalConstraints.html#aec74e09f6510d8f371a69b04afc0f877',1,'AdditionalConstraints::AdditionalConstraints(std::string constraints_file_path, ProblemGenerationLog::ProblemGenerationLoggerSharedPointer logger)'],['../classAdditionalConstraints.html#adb3cf7d561ce9b0c6a69b408505a3ee9',1,'AdditionalConstraints::AdditionalConstraints(ProblemGenerationLog::ProblemGenerationLoggerSharedPointer logger)'],['../classAdditionalConstraints.html',1,'AdditionalConstraints']]],
  ['additionalconstraintsreader_18',['additionalconstraintsreader',['../structAdditionalConstraintsReader.html#a13bb619592df9587a2d0bf6bffbbf870',1,'AdditionalConstraintsReader::AdditionalConstraintsReader()'],['../structAdditionalConstraintsReader.html',1,'AdditionalConstraintsReader'],['../structAdditionalConstraintsReader.html#a39a522c1d724b360215ec54ed15ee6cd',1,'AdditionalConstraintsReader::AdditionalConstraintsReader()']]],
  ['additionalconstraintsreadertest_19',['AdditionalConstraintsReaderTest',['../classAdditionalConstraintsReaderTest.html',1,'']]],
  ['additionalconstraintstest_20',['AdditionalConstraintsTest',['../classAdditionalConstraintsTest.html',1,'']]],
  ['addsubproblemcut_21',['addSubproblemCut',['../classWorkerMaster.html#acc3f28ce6ae84fc72955e36bb1679fbf',1,'WorkerMaster']]],
  ['addvariablestobinarise_22',['addVariablesToBinarise',['../classAdditionalConstraints.html#ab36807d147de7e46f29574156262ab9a',1,'AdditionalConstraints']]],
  ['addvariabletobinarise_23',['addVariableToBinarise',['../classAdditionalConstraints.html#adcd74c76f8273acaa05730110829537c',1,'AdditionalConstraints']]],
  ['adequacy_20criterion_24',['adequacy criterion',['../md_docs_2user-guide_2get-started_2adequacy-criterion.html',1,'Adequacy criterion'],['../md_docs_2user-guide_2get-started_2adequacy-criterion.html#autotoc_md132',1,'Launching the optimization with the adequacy criterion']]],
  ['adequacy_20criterion_20in_20tt_20adequacy_5fcriterion_20yml_20tt_25',['Input data for adequacy criterion in &lt;tt&gt;adequacy_criterion.yml&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2adequacy-criterion.html#autotoc_md131',1,'']]],
  ['adequacy_5fcriterion_20tt_26',['&lt;tt&gt;-m, --method {benders, mergeMPS, adequacy_criterion}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md163',1,'']]],
  ['adequacy_5fcriterion_20yml_20tt_27',['Input data for adequacy criterion in &lt;tt&gt;adequacy_criterion.yml&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2adequacy-criterion.html#autotoc_md131',1,'']]],
  ['algorithm_28',['algorithm',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md223',1,'Benders reformulation and decomposition algorithm'],['../md_docs_2user-guide_2get-started_2settings-definition.html',1,'Settings of the algorithm'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md226',1,'The Benders by batch algorithm'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md225',1,'The Benders decomposition algorithm']]],
  ['already_20installed_20capacity_20tt_29',['&lt;tt&gt;already-installed-capacity&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md143',1,'']]],
  ['already_20installed_20in_20direct_20link_20profile_20tt_30',['&lt;tt&gt;already-installed-[in]direct-link-profile&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md145',1,'']]],
  ['always_5ffalse_31',['always_false',['../structCatch_1_1always__false.html',1,'Catch']]],
  ['an_20antares_20simulation_32',['The operating cost as the solution of an Antares simulation',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md218',1,'']]],
  ['an_20antares_20xpansion_20study_33',['Set up an Antares-Xpansion study',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html',1,'']]],
  ['analysis_34',['analysis',['../classAnalysis.html',1,'Analysis'],['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md189',1,'Launch the sensitivity analysis'],['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md192',1,'Output of the sensitivity analysis'],['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md191',1,'Run the sensitivity analysis'],['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html',1,'Sensitivity analysis']]],
  ['analysis_20problem_35',['Mathematical formulation of the sensitivity analysis problem',['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md187',1,'']]],
  ['and_20capacity_20of_20the_20antares_20study_36',['Link between invested capacity and capacity of the Antares study',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md146',1,'']]],
  ['and_20costs_37',['Variables and costs',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md215',1,'']]],
  ['and_20decomposition_20algorithm_38',['Benders reformulation and decomposition algorithm',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md223',1,'']]],
  ['and_20get_20link_20column_20id_39',['1- Read candidates and get link column ID',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md117',1,'']]],
  ['and_20installation_20details_40',['Build and installation details',['../md_docs_2developer-guide_2install__from__sources_20-INSTALL.html#autotoc_md68',1,'']]],
  ['and_20investment_20cost_41',['Invested capacity and investment cost',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md216',1,'']]],
  ['and_20loading_20it_20dynamically_42',['Installing Xpress Solver and Loading it Dynamically',['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html',1,'']]],
  ['annual_20cost_20per_20mw_20tt_43',['&lt;tt&gt;annual-cost-per-mw&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md139',1,'']]],
  ['annuity_20for_20decommissioning_20candidates_44',['Fixed-cost annuity for decommissioning candidates',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md183',1,'']]],
  ['annuity_20for_20investment_20candidates_45',['Fixed-cost annuity for investment candidates',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md182',1,'']]],
  ['antares_20n_20cpu_20tt_46',['&lt;tt&gt;--antares-n-cpu&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md165',1,'']]],
  ['antares_20optimization_20problem_20retrieval_47',['Antares optimization problem retrieval',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html',1,'']]],
  ['antares_20output_20directory_20tt_48',['&lt;tt&gt;--simulationName {last, your-antares-output-directory}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md162',1,'']]],
  ['antares_20problem_5fgeneration_20benders_20study_5fupdate_20sensitivity_20resume_20tt_49',['&lt;tt&gt;--step {full, antares, problem_generation, benders, study_update, sensitivity, resume}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md160',1,'']]],
  ['antares_20simulation_50',['The operating cost as the solution of an Antares simulation',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md218',1,'']]],
  ['antares_20simulator_20build_51',['Automatic Antares Simulator build',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md82',1,'']]],
  ['antares_20simulator_20optimization_20problems_20retrieval_3a_20tt_20antares_20tt_52',['1- Antares-Simulator optimization problems retrieval: &lt;tt&gt;antares&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md102',1,'']]],
  ['antares_20study_53',['antares study',['../md_docs_2index.html#autotoc_md128',1,'Antares study'],['../index.html#autotoc_md2',1,'Antares study'],['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md146',1,'Link between invested capacity and capacity of the Antares study'],['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md176',1,'Prepare the Antares study']]],
  ['antares_20study_3a_20tt_20study_5fupdate_20tt_54',['4- Update of antares study: &lt;tt&gt;study_update&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md105',1,'']]],
  ['antares_20tt_55',['1- Antares-Simulator optimization problems retrieval: &lt;tt&gt;antares&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md102',1,'']]],
  ['antares_20version_20tt_56',['&lt;tt&gt;--antares-version&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md168',1,'']]],
  ['antares_20xpansion_57',['antares xpansion',['../index.html',1,'Antares-Xpansion'],['../md_docs_2user-guide_2get-started_2installation.html#autotoc_md153',1,'Download Antares-Xpansion'],['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md169',1,'Output of Antares-Xpansion'],['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md108',1,'Specific configuration for Antares-Xpansion'],['../md_docs_2user-guide_2optimization-principles_2investment-problem.html',1,'The optimal investment problem in Antares-Xpansion']]],
  ['antares_20xpansion_20changelog_58',['Antares-Xpansion changelog',['../md_docs_2changelog_2CHANGELOG.html',1,'']]],
  ['antares_20xpansion_20package_20executables_59',['Antares-Xpansion package executables',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md106',1,'']]],
  ['antares_20xpansion_20simulation_60',['antares xpansion simulation',['../index.html#autotoc_md3',1,'Antares-Xpansion simulation'],['../md_docs_2index.html#autotoc_md129',1,'Antares-Xpansion simulation']]],
  ['antares_20xpansion_20simulation_20procedure_61',['Antares-Xpansion simulation procedure',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html',1,'']]],
  ['antares_20xpansion_20study_62',['Set up an Antares-Xpansion study',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html',1,'']]],
  ['antares_5foutput_63',['antares_output',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader.html#a7ebd0291e5efb3c813ec863c9f31c80d',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['antares_5foutput_5fdir_64',['antares_output_dir',['../classantares__xpansion_1_1antares__driver_1_1AntaresDriver.html#a8440bc0602ca38c565287c80dcfbf0f2',1,'antares_xpansion::antares_driver::AntaresDriver']]],
  ['antares_5fxpansion_65',['antares_xpansion',['../namespaceantares__xpansion.html',1,'']]],
  ['antares_5fxpansion_3a_3aantares_5fdriver_66',['antares_driver',['../namespaceantares__xpansion_1_1antares__driver.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3abenders_5fdriver_67',['benders_driver',['../namespaceantares__xpansion_1_1benders__driver.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3aconfig_5floader_68',['config_loader',['../namespaceantares__xpansion_1_1config__loader.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3adriver_69',['driver',['../namespaceantares__xpansion_1_1driver.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3ainput_5fchecker_70',['input_checker',['../namespaceantares__xpansion_1_1input__checker.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3aproblem_5fgenerator_5fdriver_71',['problem_generator_driver',['../namespaceantares__xpansion_1_1problem__generator__driver.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3asensitivity_5fdriver_72',['sensitivity_driver',['../namespaceantares__xpansion_1_1sensitivity__driver.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3astudy_5fupdater_5fdriver_73',['study_updater_driver',['../namespaceantares__xpansion_1_1study__updater__driver.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3axpansion_5futils_74',['xpansion_utils',['../namespaceantares__xpansion_1_1xpansion__utils.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3axpansionconfig_75',['xpansionConfig',['../namespaceantares__xpansion_1_1xpansionConfig.html',1,'antares_xpansion']]],
  ['antaresarchiveupdater_76',['AntaresArchiveUpdater',['../classAntaresArchiveUpdater.html',1,'']]],
  ['antaresarchiveupdaterexeerror_77',['AntaresArchiveUpdaterExeError',['../classantares__xpansion_1_1driver_1_1XpansionDriver_1_1AntaresArchiveUpdaterExeError.html',1,'antares_xpansion::driver::XpansionDriver']]],
  ['antaresarchiveupdaterexeoptions_78',['AntaresArchiveUpdaterExeOptions',['../classAntaresArchiveUpdaterExeOptions.html',1,'']]],
  ['antaresdriver_79',['AntaresDriver',['../classantares__xpansion_1_1antares__driver_1_1AntaresDriver.html',1,'antares_xpansion::antares_driver']]],
  ['antaresexecutionerror_80',['AntaresExecutionError',['../classantares__xpansion_1_1antares__driver_1_1AntaresDriver_1_1AntaresExecutionError.html',1,'antares_xpansion::antares_driver::AntaresDriver']]],
  ['antareslinkdatareader_81',['AntaresLinkDataReader',['../classAntaresLinkDataReader.html',1,'']]],
  ['antaresproblemtoxpansionproblemtranslator_82',['AntaresProblemToXpansionProblemTranslator',['../classAntaresProblemToXpansionProblemTranslator.html',1,'']]],
  ['antaresversionprovider_83',['AntaresVersionProvider',['../classAntaresVersionProvider.html',1,'']]],
  ['antaresversionproviderstub_84',['AntaresVersionProviderStub',['../classAntaresVersionProviderStub.html',1,'']]],
  ['approx_85',['Approx',['../classCatch_1_1Detail_1_1Approx.html',1,'Catch::Detail']]],
  ['archiveio_86',['ArchiveIO',['../classArchiveIO.html',1,'']]],
  ['archiveiogeneralexception_87',['ArchiveIOGeneralException',['../classArchiveIOGeneralException.html',1,'']]],
  ['archiveiospecificexception_88',['ArchiveIOSpecificException',['../classArchiveIOSpecificException.html',1,'']]],
  ['archivereader_89',['ArchiveReader',['../classArchiveReader.html',1,'']]],
  ['archivereadertest_90',['ArchiveReaderTest',['../classArchiveReaderTest.html',1,'']]],
  ['archiveupdatertest_91',['ArchiveUpdaterTest',['../classArchiveUpdaterTest.html',1,'']]],
  ['archivewriter_92',['ArchiveWriter',['../classArchiveWriter.html',1,'']]],
  ['archivewritertest_93',['ArchiveWriterTest',['../classArchiveWriterTest.html',1,'']]],
  ['are_20known_20to_20have_20mpi_20related_20issues_20please_20use_20the_20other_20ones_94',['⚠️ Single-file versions in Ubuntu are known to have MPI-related issues. Please use the other ones.',['../md_docs_2changelog_2CHANGELOG.html#autotoc_md17',1,'']]],
  ['area_20txt_20tt_95',['The file &lt;tt&gt;area.txt&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md112',1,'']]],
  ['areafiledata_96',['AreaFileData',['../structAreaFileData.html',1,'']]],
  ['areafileerror_97',['AreaFileError',['../structAreaFileError.html',1,'']]],
  ['areafileexception_98',['AreaFileException',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorDriver_1_1AreaFileException.html',1,'antares_xpansion::problem_generator_driver::ProblemGeneratorDriver']]],
  ['areaparser_99',['AreaParser',['../structAreaParser.html',1,'']]],
  ['areas_100',['Investment in transmission capacity between two areas',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md177',1,'']]],
  ['as_101',['as',['../structCatch_1_1Generators_1_1as.html',1,'Catch::Generators']]],
  ['as_20the_20solution_20of_20an_20antares_20simulation_102',['The operating cost as the solution of an Antares simulation',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md218',1,'']]],
  ['aspects_20of_20the_20investment_20problem_103',['Mathematical aspects of the investment problem',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html',1,'']]],
  ['assertionhandler_104',['AssertionHandler',['../classCatch_1_1AssertionHandler.html',1,'Catch']]],
  ['assertioninfo_105',['AssertionInfo',['../structCatch_1_1AssertionInfo.html',1,'Catch']]],
  ['assertionreaction_106',['AssertionReaction',['../structCatch_1_1AssertionReaction.html',1,'Catch']]],
  ['automatic_20antares_20simulator_20build_107',['Automatic Antares Simulator build',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md82',1,'']]],
  ['autoreg_108',['AutoReg',['../structCatch_1_1AutoReg.html',1,'Catch']]]
];
