var searchData=
[
  ['m_20method_20benders_20mergemps_20adequacy_5fcriterion_20tt_0',['&lt;tt&gt;-m, --method {benders, mergeMPS, adequacy_criterion}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md168',1,'']]],
  ['macos_1',['Linux/macOS',['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html#autotoc_md100',1,'']]],
  ['manager_2',['Install with a VCPKG package manager',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md79',1,'']]],
  ['mapgenerator_3',['MapGenerator',['../classCatch_1_1Generators_1_1MapGenerator.html',1,'Catch::Generators']]],
  ['mapping_20file_4',['5- Creation of a variable / column ID mapping file',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md127',1,'']]],
  ['markers_5',['markers',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md256',1,'Test markers'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md267',1,'Test markers']]],
  ['master_6',['Master',['../classxpansion_1_1logger_1_1Master.html',1,'xpansion::logger']]],
  ['master_20merger_20executable_7',[' Usage of the master merger executable',['../md_docs_2user-guide_2trajectory-investment_2merge-master.html#autotoc_md236',1,'']]],
  ['master_20problem_8',['4- Creation of master problem',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md126',1,'']]],
  ['master_20problems_20of_20annual_20xpansion_20studies_9',['Merging the master problems of annual Xpansion studies',['../md_docs_2user-guide_2trajectory-investment_2merge-master.html',1,'']]],
  ['master_20structure_20file_10',['Master structure file',['../md_docs_2user-guide_2trajectory-investment_2merge-master.html#autotoc_md238',1,'']]],
  ['master_20tt_11',['&lt;tt&gt;master&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md207',1,'']]],
  ['masterfilenotfound_12',['MasterFileNotFound',['../classantares__xpansion_1_1resume__study_1_1ResumeStudy_1_1MasterFileNotFound.html',1,'antares_xpansion::resume_study::ResumeStudy']]],
  ['mastergeneration_13',['MasterGeneration',['../classMasterGeneration.html',1,'']]],
  ['mastergenerationtest_14',['MasterGenerationTest',['../classMasterGenerationTest.html',1,'']]],
  ['masterloggertest_15',['MasterLoggerTest',['../classMasterLoggerTest.html',1,'']]],
  ['masterproblembuilder_16',['MasterProblemBuilder',['../classMasterProblemBuilder.html',1,'']]],
  ['masterupdatebase_17',['MasterUpdateBase',['../classOuterloop_1_1MasterUpdateBase.html',1,'Outerloop']]],
  ['masterupdatebasetest_18',['MasterUpdateBaseTest',['../classMasterUpdateBaseTest.html',1,'']]],
  ['matchallof_19',['MatchAllOf',['../structCatch_1_1Matchers_1_1Impl_1_1MatchAllOf.html',1,'Catch::Matchers::Impl']]],
  ['matchanyof_20',['MatchAnyOf',['../structCatch_1_1Matchers_1_1Impl_1_1MatchAnyOf.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_21',['MatcherBase',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_3c_20argt_20_3e_22',['MatcherBase&lt; ArgT &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_3c_20double_20_3e_23',['MatcherBase&lt; double &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_3c_20std_3a_3aexception_20_3e_24',['MatcherBase&lt; std::exception &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_3c_20std_3a_3astring_20_3e_25',['MatcherBase&lt; std::string &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_3c_20std_3a_3avector_3c_20t_2c_20alloc_20_3e_20_3e_26',['MatcherBase&lt; std::vector&lt; T, Alloc &gt; &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matcherbase_3c_20std_3a_3avector_3c_20t_2c_20allocmatch_20_3e_20_3e_27',['MatcherBase&lt; std::vector&lt; T, AllocMatch &gt; &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_28',['MatcherMethod',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_3c_20argt_20_3e_29',['MatcherMethod&lt; ArgT &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_3c_20double_20_3e_30',['MatcherMethod&lt; double &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_3c_20std_3a_3aexception_20_3e_31',['MatcherMethod&lt; std::exception &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_3c_20std_3a_3astring_20_3e_32',['MatcherMethod&lt; std::string &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matchermethod_3c_20t_20_3e_33',['MatcherMethod&lt; T &gt;',['../structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html',1,'Catch::Matchers::Impl']]],
  ['matcheruntypedbase_34',['MatcherUntypedBase',['../classCatch_1_1Matchers_1_1Impl_1_1MatcherUntypedBase.html',1,'Catch::Matchers::Impl']]],
  ['matchexpr_35',['MatchExpr',['../classCatch_1_1MatchExpr.html',1,'Catch']]],
  ['matchnotof_36',['MatchNotOf',['../structCatch_1_1Matchers_1_1Impl_1_1MatchNotOf.html',1,'Catch::Matchers::Impl']]],
  ['mathematical_20aspects_20of_20the_20investment_20problem_37',['Mathematical aspects of the investment problem',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html',1,'']]],
  ['mathematical_20formulation_20of_20the_20sensitivity_20analysis_20problem_38',['Mathematical formulation of the sensitivity analysis problem',['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md193',1,'']]],
  ['mathlogger_39',['MathLogger',['../structMathLogger.html',1,'']]],
  ['mathloggerbase_40',['MathLoggerBase',['../structMathLoggerBase.html',1,'']]],
  ['mathloggerbaseexternalloop_41',['MathLoggerBaseExternalLoop',['../structMathLoggerBaseExternalLoop.html',1,'']]],
  ['mathloggerbehaviour_42',['MathLoggerBehaviour',['../structMathLoggerBehaviour.html',1,'']]],
  ['mathloggerbendersbybatch_43',['MathLoggerBendersByBatch',['../structMathLoggerBendersByBatch.html',1,'']]],
  ['mathloggerbendersbybatchexternalloop_44',['MathLoggerBendersByBatchExternalLoop',['../structMathLoggerBendersByBatchExternalLoop.html',1,'']]],
  ['mathloggerdriver_45',['MathLoggerDriver',['../classMathLoggerDriver.html',1,'']]],
  ['mathloggerexternalloopspecific_46',['MathLoggerExternalLoopSpecific',['../structMathLoggerExternalLoopSpecific.html',1,'']]],
  ['mathloggerfactory_47',['MathLoggerFactory',['../classMathLoggerFactory.html',1,'']]],
  ['mathloggerfile_48',['MathLoggerFile',['../classMathLoggerFile.html',1,'']]],
  ['mathloggerimplementation_49',['MathLoggerImplementation',['../classMathLoggerImplementation.html',1,'']]],
  ['mathloggerostream_50',['MathLoggerOstream',['../classMathLoggerOstream.html',1,'']]],
  ['max_20investment_20tt_51',['&lt;tt&gt;max-investment&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md145',1,'']]],
  ['max_20units_20tt_52',['&lt;tt&gt;max-units&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md147',1,'']]],
  ['max_5fiteration_20tt_53',['&lt;tt&gt;max_iteration&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md204',1,'']]],
  ['maxitervalueerror_54',['MaxIterValueError',['../classantares__xpansion_1_1input__checker_1_1MaxIterValueError.html',1,'antares_xpansion::input_checker']]],
  ['maxunitsandmaxinvestmentarenullsimultaneously_55',['MaxUnitsAndMaxInvestmentAreNullSimultaneously',['../classantares__xpansion_1_1input__checker_1_1MaxUnitsAndMaxInvestmentAreNullSimultaneously.html',1,'antares_xpansion::input_checker']]],
  ['maxunitsandmaxinvestmentnonnullsimultaneously_56',['MaxUnitsAndMaxInvestmentNonNullSimultaneously',['../classantares__xpansion_1_1input__checker_1_1MaxUnitsAndMaxInvestmentNonNullSimultaneously.html',1,'antares_xpansion::input_checker']]],
  ['mcyearnotinactiveyearslisterror_57',['McYearNotInActiveYearsListError',['../classYearlyWeightsWriter_1_1McYearNotInActiveYearsListError.html',1,'YearlyWeightsWriter']]],
  ['merge_5flocal_5fsolver_58',['merge_local_solver',['../classAbstractMergeMPS.html#a5b71702ecca3ab9b5147169a297658af',1,'AbstractMergeMPS']]],
  ['mergemastersubproblemmps_59',['MergeMasterSubproblemMPS',['../classMergeMasterSubproblemMPS.html',1,'']]],
  ['mergemastertrajectorymps_60',['MergeMasterTrajectoryMPS',['../classMergeMasterTrajectoryMPS.html',1,'']]],
  ['mergemps_20adequacy_5fcriterion_20tt_61',['&lt;tt&gt;-m, --method {benders, mergeMPS, adequacy_criterion}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md168',1,'']]],
  ['mergempstest_62',['MergeMPSTest',['../classMergeMPSTest.html',1,'']]],
  ['merger_20executable_63',[' Usage of the master merger executable',['../md_docs_2user-guide_2trajectory-investment_2merge-master.html#autotoc_md236',1,'']]],
  ['mergeweightstrajectory_64',['MergeWeightsTrajectory',['../classMergeWeightsTrajectory.html',1,'']]],
  ['merging_20the_20master_20problems_20of_20annual_20xpansion_20studies_65',['Merging the master problems of annual Xpansion studies',['../md_docs_2user-guide_2trajectory-investment_2merge-master.html',1,'']]],
  ['messagebuilder_66',['MessageBuilder',['../structCatch_1_1MessageBuilder.html',1,'Catch']]],
  ['messageinfo_67',['MessageInfo',['../structCatch_1_1MessageInfo.html',1,'Catch']]],
  ['messagestream_68',['MessageStream',['../structCatch_1_1MessageStream.html',1,'Catch']]],
  ['method_69',['Description of the method',['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md192',1,'']]],
  ['method_20benders_20mergemps_20adequacy_5fcriterion_20tt_70',['&lt;tt&gt;-m, --method {benders, mergeMPS, adequacy_criterion}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md168',1,'']]],
  ['mini_5finstance_5finfeasible_71',['mini_instance_INFEASIBLE',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md254',1,'mini_instance_INFEASIBLE'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md265',1,'mini_instance_INFEASIBLE']]],
  ['mini_5finstance_5flp_5fdefault_72',['mini_instance_LP_default',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md251',1,'mini_instance_LP_default'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md262',1,'mini_instance_LP_default']]],
  ['mini_5finstance_5fmip_5fdefault_73',['mini_instance_MIP_default',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md252',1,'mini_instance_MIP_default'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md263',1,'mini_instance_MIP_default']]],
  ['mini_5finstance_5funbounded_74',['mini_instance_UNBOUNDED',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md253',1,'mini_instance_UNBOUNDED'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md264',1,'mini_instance_UNBOUNDED']]],
  ['mini_5fnetwork_5fdefault_75',['mini_network_default',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md249',1,'mini_network_default'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md260',1,'mini_network_default']]],
  ['mini_5fnetwork_5fslave_5fweight_76',['mini_network_slave_weight',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md250',1,'mini_network_slave_weight'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md261',1,'mini_network_slave_weight']]],
  ['mismatchedparameters_77',['MismatchedParameters',['../classProblemGenerationOptions_1_1MismatchedParameters.html',1,'ProblemGenerationOptions']]],
  ['missingantaresoutput_78',['MissingAntaresOutput',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1MissingAntaresOutput.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['missingfile_79',['MissingFile',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1MissingFile.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['missingparameters_80',['MissingParameters',['../classProblemGenerationOptions_1_1MissingParameters.html',1,'ProblemGenerationOptions']]],
  ['missingsimulationname_81',['MissingSimulationName',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1MissingSimulationName.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['modification_20of_20mps_20file_82',['2- Modification of .mps file',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md122',1,'']]],
  ['modification_20of_20weekly_20problems_20with_20tt_20lp_5fnamer_20tt_83',['Modification of weekly problems with &lt;tt&gt;lp_namer&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md120',1,'']]],
  ['modifications_20for_20em_20satellite_20problems_20em_84',['Modifications for &lt;em&gt;satellite problems&lt;/em&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md124',1,'']]],
  ['monte_20carlo_20year_85',['Using different profiles depending on the Monte-Carlo year',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md152',1,'']]],
  ['move_20to_20developer_20guide_20as_20this_20should_20not_20be_20relevant_20to_20the_20end_20user_86',['Note : Perhaps move to developer guide, as this should not be relevant to the end user.',['../md_docs_2user-guide_2trajectory-investment_2merge-master.html#autotoc_md235',1,'']]],
  ['mpi_20related_20issues_20please_20use_20the_20other_20ones_87',['⚠️ Single-file versions in Ubuntu are known to have MPI-related issues. Please use the other ones.',['../md_docs_2changelog_2CHANGELOG.html#autotoc_md21',1,'']]],
  ['mps_20file_88',['2- Modification of .mps file',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md122',1,'']]],
  ['mps_20tt_20file_89',['&lt;tt&gt;variables.txt&lt;/tt&gt; file for each &lt;tt&gt;.mps&lt;/tt&gt; file',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md115',1,'']]],
  ['mps_20tt_20files_20for_20the_20weekly_20optimization_20problems_90',['&lt;tt&gt;.mps&lt;/tt&gt; files for the weekly optimization problems',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md114',1,'']]],
  ['mpsfileproblemprovideradapter_91',['MPSFileProblemProviderAdapter',['../classMPSFileProblemProviderAdapter.html',1,'']]],
  ['mpstxtwritertest_92',['MpsTxtWriterTest',['../classMpsTxtWriterTest.html',1,'']]],
  ['mpszipfileexception_93',['MpsZipFileException',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorDriver_1_1MpsZipFileException.html',1,'antares_xpansion::problem_generator_driver::ProblemGeneratorDriver']]],
  ['multiplealreadyinstalledcapacitydetectedforlink_94',['MultipleAlreadyInstalledCapacityDetectedForLink',['../classActiveLinksBuilder_1_1MultipleAlreadyInstalledCapacityDetectedForLink.html',1,'ActiveLinksBuilder']]],
  ['multiplealreadyinstalledprofiledetectedforlink_95',['MultipleAlreadyInstalledProfileDetectedForLink',['../classActiveLinksBuilder_1_1MultipleAlreadyInstalledProfileDetectedForLink.html',1,'ActiveLinksBuilder']]],
  ['multiplelinkiddetectedforlink_96',['MultipleLinkIddetectedForLink',['../classActiveLinksBuilder_1_1MultipleLinkIddetectedForLink.html',1,'ActiveLinksBuilder']]],
  ['multipleproblemgeneration_97',['MultipleProblemGeneration',['../classMultipleProblemGeneration.html',1,'']]],
  ['multipleproblemgenerationexeoptions_98',['MultipleProblemGenerationExeOptions',['../classMultipleProblemGenerationExeOptions.html',1,'']]],
  ['multiply_5fobj_5fby_5fweight_5ffactor_99',['multiply_obj_by_weight_factor',['../classAbstractMergeMPS.html#a3564177205bdc0a9231ce4fef65c31aa',1,'AbstractMergeMPS']]],
  ['mw_20tt_100',['&lt;tt&gt;annual-cost-per-mw&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md144',1,'']]]
];
