var searchData=
[
  ['i_20datadir_20tt_0',['&lt;tt&gt;-i, --dataDir&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md152',1,'']]],
  ['icontext_1',['IContext',['../structCatch_1_1IContext.html',1,'Catch']]],
  ['icutsmanager_2',['ICutsManager',['../classOuterloop_1_1ICutsManager.html',1,'Outerloop']]],
  ['id_3',['1- Read candidates and get link column ID',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md108',1,'']]],
  ['id_20mapping_20file_4',['5- Creation of a variable / column ID mapping file',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md114',1,'']]],
  ['iexceptiontranslator_5',['IExceptionTranslator',['../structCatch_1_1IExceptionTranslator.html',1,'Catch']]],
  ['iexceptiontranslatorregistry_6',['IExceptionTranslatorRegistry',['../structCatch_1_1IExceptionTranslatorRegistry.html',1,'Catch']]],
  ['igenerator_7',['IGenerator',['../structCatch_1_1Generators_1_1IGenerator.html',1,'Catch::Generators']]],
  ['igenerator_3c_20float_20_3e_8',['IGenerator&lt; Float &gt;',['../structCatch_1_1Generators_1_1IGenerator.html',1,'Catch::Generators']]],
  ['igenerator_3c_20integer_20_3e_9',['IGenerator&lt; Integer &gt;',['../structCatch_1_1Generators_1_1IGenerator.html',1,'Catch::Generators']]],
  ['igenerator_3c_20std_3a_3avector_3c_20t_20_3e_20_3e_10',['IGenerator&lt; std::vector&lt; T &gt; &gt;',['../structCatch_1_1Generators_1_1IGenerator.html',1,'Catch::Generators']]],
  ['igeneratortracker_11',['IGeneratorTracker',['../structCatch_1_1IGeneratorTracker.html',1,'Catch']]],
  ['illegal_5fchars_12',['illegal_chars',['../structAdditionalConstraintsReader.html#a1d529a309d6dcd07eca227181276a10c',1,'AdditionalConstraintsReader']]],
  ['illegalcharsincandidatename_13',['IllegalCharsInCandidateName',['../classantares__xpansion_1_1input__checker_1_1IllegalCharsInCandidateName.html',1,'antares_xpansion::input_checker']]],
  ['ilogger_14',['ILogger',['../classILogger.html',1,'']]],
  ['iloggerxpansion_15',['ILoggerXpansion',['../structILoggerXpansion.html',1,'']]],
  ['imasterupdate_16',['IMasterUpdate',['../classOuterloop_1_1IMasterUpdate.html',1,'Outerloop']]],
  ['impedances_5f_17',['impedances_',['../structLinkdataRecord_1_1FileColumns.html#ad65a0ad193fd24591ac5d17f074a419b',1,'LinkdataRecord::FileColumns']]],
  ['imutablecontext_18',['IMutableContext',['../structCatch_1_1IMutableContext.html',1,'Catch']]],
  ['imutableenumvaluesregistry_19',['IMutableEnumValuesRegistry',['../structCatch_1_1IMutableEnumValuesRegistry.html',1,'Catch']]],
  ['in_20antares_20xpansion_20',['The optimal investment problem in Antares-Xpansion',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html',1,'']]],
  ['in_20direct_20link_20profile_20tt_21',['in direct link profile tt',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md135',1,'&lt;tt&gt;[in]direct-link-profile&lt;/tt&gt;'],['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md136',1,'&lt;tt&gt;already-installed-[in]direct-link-profile&lt;/tt&gt;']]],
  ['in_20flexibility_22',['Investment in flexibility',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md172',1,'']]],
  ['in_20renewable_20generation_20capacity_23',['Investment in renewable generation capacity',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md171',1,'']]],
  ['in_20thermal_20generation_20capacity_24',['Investment in thermal generation capacity',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md170',1,'']]],
  ['in_20transmission_20capacity_20between_20two_20areas_25',['Investment in transmission capacity between two areas',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md169',1,'']]],
  ['in_20tt_20adequacy_5fcriterion_20yml_20tt_26',['Input data for adequacy criterion in &lt;tt&gt;adequacy_criterion.yml&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2adequacy-criterion.html#autotoc_md122',1,'']]],
  ['in_20tt_20candidates_20ini_20tt_27',['Characterization of investment candidates in &lt;tt&gt;candidates.ini&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md126',1,'']]],
  ['in_20ubuntu_20are_20known_20to_20have_20mpi_20related_20issues_20please_20use_20the_20other_20ones_28',['⚠️ Single-file versions in Ubuntu are known to have MPI-related issues. Please use the other ones.',['../md_docs_2changelog_2CHANGELOG.html#autotoc_md18',1,'']]],
  ['index_29',['index',['../md_docs_2index.html',1,'']]],
  ['indirect_5flink_5fprofile_30',['indirect_link_profile',['../classLinkProfile.html#adf7b5092f19ec8f5f63ce3b8fd69aba7',1,'LinkProfile']]],
  ['indirectcapacity_5f_31',['indirectCapacity_',['../structLinkdataRecord_1_1FileColumns.html#a729097b7eca4ae27add0d332decf53d9',1,'LinkdataRecord::FileColumns']]],
  ['indirecthurdlescost_5f_32',['indirectHurdlesCost_',['../structLinkdataRecord_1_1FileColumns.html#adfed6f095294c0bb8db291926594dd40',1,'LinkdataRecord::FileColumns']]],
  ['ini_20tt_33',['Characterization of investment candidates in &lt;tt&gt;candidates.ini&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md126',1,'']]],
  ['ini_20tt_20file_34',['ini tt file',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md127',1,'Overview of the &lt;tt&gt;candidates.ini&lt;/tt&gt; file'],['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md186',1,'Overview of the &lt;tt&gt;settings.ini&lt;/tt&gt; file']]],
  ['inifilenotfound_35',['inifilenotfound',['../classIniFileNotFound.html',1,'IniFileNotFound'],['../classantares__xpansion_1_1general__data__reader_1_1IniFileNotFound.html',1,'antares_xpansion.general_data_reader.IniFileNotFound'],['../classantares__xpansion_1_1candidates__reader_1_1IniFileNotFound.html',1,'antares_xpansion.candidates_reader.IniFileNotFound']]],
  ['inireader_36',['inireader',['../classINIReader.html',1,'INIReader'],['../classantares__xpansion_1_1general__data__reader_1_1IniReader.html',1,'antares_xpansion.general_data_reader.IniReader']]],
  ['inireaderutils_37',['IniReaderUtils',['../classIniReaderUtils.html',1,'']]],
  ['init_38',['init',['../classNOOPSolver.html#a4de8c579b665ad71ac391cdfbbfcadb1',1,'NOOPSolver::init()'],['../classWorker.html#a3db6724c271b0f26a44cfea0f3228a85',1,'Worker::init()'],['../classProblem.html#a075abb3bc479adb0de6c2326fe03ac17',1,'Problem::init()'],['../classSolverAbstract.html#a31e69eec019d489b31b2080f890cecb6',1,'SolverAbstract::init()'],['../classSolverCbc.html#a1b3d4706655309b6d8143d96343069ae',1,'SolverCbc::init()'],['../classSolverClp.html#a8a7c0625768b415c59c59bcdaaf6b6a9',1,'SolverClp::init()'],['../classSolverXpress.html#a30b56a03a4c060bbabf2bb6fc1faa4d3',1,'SolverXpress::init()']]],
  ['init_5fdata_39',['init_data',['../classBendersSequentialDouble.html#a33c0199bf9a762b001db1f631ca9444f',1,'BendersSequentialDouble::init_data()'],['../classBendersBase.html#a62a819640d2a7530fce9418547f45d65',1,'BendersBase::init_data()']]],
  ['initial_20weekly_20problems_40',['Initial weekly problems',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md110',1,'']]],
  ['initialize_41',['initialize',['../classOutput_1_1JsonWriter.html#aee3cc2a6e0300509d23bbbb8de1eae94',1,'Output::JsonWriter::initialize()'],['../classOutput_1_1VoidWriter.html#ad6904d7f602e37270c000a9dbe564cde',1,'Output::VoidWriter::initialize()'],['../classOutput_1_1OutputWriter.html#a3a0f989f5e057b16bf4ead25ab992f05',1,'Output::OutputWriter::initialize()'],['../classWriterNOOPStub.html#acff703f70a39e1ea0c0162f0f33862b8',1,'WriterNOOPStub::initialize()']]],
  ['initializeproblems_42',['initializeproblems',['../classOuterloop_1_1BendersMpiOuterLoop.html#a92374cfea41d421bf149823c531b001c',1,'Outerloop::BendersMpiOuterLoop::InitializeProblems()'],['../classBendersMpi.html#a217d3af6fbe78082f30fa9ef75cf1dfb',1,'BendersMpi::InitializeProblems()']]],
  ['initxpressenv_43',['initXpressEnv',['../classLoadXpress_1_1XpressLoader.html#a1a17e7973088bd65105007a7e2f2481e',1,'LoadXpress::XpressLoader']]],
  ['input_20data_20for_20adequacy_20criterion_20in_20tt_20adequacy_5fcriterion_20yml_20tt_44',['Input data for adequacy criterion in &lt;tt&gt;adequacy_criterion.yml&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2adequacy-criterion.html#autotoc_md122',1,'']]],
  ['input_20file_20creation_45',['Sensitivity input file creation',['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md182',1,'']]],
  ['inputparameters_46',['InputParameters',['../classantares__xpansion_1_1xpansionConfig_1_1InputParameters.html',1,'antares_xpansion::xpansionConfig']]],
  ['inputparser_47',['InputParser',['../classantares__xpansion_1_1input__parser_1_1InputParser.html',1,'antares_xpansion::input_parser']]],
  ['install_48',['Dependencies install',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html',1,'']]],
  ['install_20requirements_49',['Install requirements',['../md_docs_2developer-guide_2install__from__sources_25-ui-creation.html#autotoc_md89',1,'']]],
  ['install_20with_20a_20vcpkg_20package_20manager_50',['Install with a VCPKG package manager',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md76',1,'']]],
  ['installation_51',['installation',['../md_docs_2user-guide_2get-started_2installation.html',1,'Installation'],['../index.html#autotoc_md5',1,'Installation']]],
  ['installation_20details_52',['Build and installation details',['../md_docs_2developer-guide_2install__from__sources_20-INSTALL.html#autotoc_md69',1,'']]],
  ['installation_20instruction_53',['Installation instruction',['../md_docs_2user-guide_2get-started_2installation.html#autotoc_md145',1,'']]],
  ['installed_20capacity_20tt_54',['&lt;tt&gt;already-installed-capacity&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md134',1,'']]],
  ['installed_20in_20direct_20link_20profile_20tt_55',['&lt;tt&gt;already-installed-[in]direct-link-profile&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md136',1,'']]],
  ['installer_20creation_56',['Installer creation',['../md_docs_2developer-guide_2install__from__sources_26-Installer-creation.html',1,'']]],
  ['installing_20dependencies_57',['Installing dependencies',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md78',1,'']]],
  ['instancedata_58',['InstanceData',['../classInstanceData.html',1,'']]],
  ['instruction_59',['Installation instruction',['../md_docs_2user-guide_2get-started_2installation.html#autotoc_md145',1,'']]],
  ['interco_20txt_20tt_60',['The file &lt;tt&gt;interco.txt&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md104',1,'']]],
  ['intercofiledata_61',['IntercoFileData',['../structIntercoFileData.html',1,'']]],
  ['intercofilesexception_62',['IntercoFilesException',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorDriver_1_1IntercoFilesException.html',1,'antares_xpansion::problem_generator_driver::ProblemGeneratorDriver']]],
  ['interface_63',['interface',['../index.html#autotoc_md8',1,'Graphical user interface'],['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md160',1,'Graphical user interface']]],
  ['interface_20creation_64',['User interface creation',['../md_docs_2developer-guide_2install__from__sources_25-ui-creation.html',1,'']]],
  ['interpretation_65',['Results interpretation',['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md180',1,'']]],
  ['introduction_66',['introduction',['../index.html#autotoc_md1',1,'Introduction'],['../md_docs_2developer-guide_2install__from__sources_20-INSTALL.html',1,'Introduction'],['../md_docs_2index.html#autotoc_md118',1,'Introduction']]],
  ['invalidboundtypeexception_67',['InvalidBoundTypeException',['../classInvalidBoundTypeException.html',1,'']]],
  ['invalidcolsizeexception_68',['InvalidColSizeException',['../classInvalidColSizeException.html',1,'']]],
  ['invalidcoltypeexception_69',['InvalidColTypeException',['../classInvalidColTypeException.html',1,'']]],
  ['invalidhourforprofile_70',['InvalidHourForProfile',['../classLinkProfile_1_1InvalidHourForProfile.html',1,'LinkProfile']]],
  ['invalidintercofile_71',['InvalidIntercoFile',['../classCandidatesINIReader_1_1InvalidIntercoFile.html',1,'CandidatesINIReader']]],
  ['invalidnumberofargumentspassedtoparser_72',['InvalidNumberOfArgumentsPassedToParser',['../classOptionsParser_1_1InvalidNumberOfArgumentsPassedToParser.html',1,'OptionsParser']]],
  ['invalidrowsizeexception_73',['InvalidRowSizeException',['../classInvalidRowSizeException.html',1,'']]],
  ['invalidsimulationname_74',['InvalidSimulationName',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1InvalidSimulationName.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['invalidsolverforcopyexception_75',['InvalidSolverForCopyException',['../classInvalidSolverForCopyException.html',1,'']]],
  ['invalidsolvernameexception_76',['InvalidSolverNameException',['../classInvalidSolverNameException.html',1,'']]],
  ['invalidsolveroptionexception_77',['InvalidSolverOptionException',['../classInvalidSolverOptionException.html',1,'']]],
  ['invalidsolverstatusexception_78',['InvalidSolverStatusException',['../classInvalidSolverStatusException.html',1,'']]],
  ['invalidstatusexception_79',['InvalidStatusException',['../classInvalidStatusException.html',1,'']]],
  ['invalidyearsweightnumber_80',['invalidyearsweightnumber',['../classWeightsFileReader_1_1InvalidYearsWeightNumber.html',1,'WeightsFileReader::InvalidYearsWeightNumber'],['../classantares__xpansion_1_1xpansion__study__reader_1_1XpansionStudyReader_1_1InvalidYearsWeightNumber.html',1,'antares_xpansion.xpansion_study_reader.XpansionStudyReader.InvalidYearsWeightNumber']]],
  ['invalidyearsweightvalue_81',['invalidyearsweightvalue',['../classantares__xpansion_1_1xpansion__study__reader_1_1XpansionStudyReader_1_1InvalidYearsWeightValue.html',1,'antares_xpansion.xpansion_study_reader.XpansionStudyReader.InvalidYearsWeightValue'],['../classWeightsFileReader_1_1InvalidYearsWeightValue.html',1,'WeightsFileReader::InvalidYearsWeightValue']]],
  ['invested_20capacity_20and_20capacity_20of_20the_20antares_20study_82',['Link between invested capacity and capacity of the Antares study',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md137',1,'']]],
  ['invested_20capacity_20and_20investment_20cost_83',['Invested capacity and investment cost',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md208',1,'']]],
  ['investment_20candidates_84',['investment candidates',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md176',1,'Additional characteristics for links of investment candidates'],['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md174',1,'Fixed-cost annuity for investment candidates']]],
  ['investment_20candidates_20in_20tt_20candidates_20ini_20tt_85',['Characterization of investment candidates in &lt;tt&gt;candidates.ini&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md126',1,'']]],
  ['investment_20candidates_20on_20the_20same_20link_86',['Several investment candidates on the same link',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md141',1,'']]],
  ['investment_20cost_87',['Invested capacity and investment cost',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md208',1,'']]],
  ['investment_20in_20flexibility_88',['Investment in flexibility',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md172',1,'']]],
  ['investment_20in_20renewable_20generation_20capacity_89',['Investment in renewable generation capacity',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md171',1,'']]],
  ['investment_20in_20thermal_20generation_20capacity_90',['Investment in thermal generation capacity',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md170',1,'']]],
  ['investment_20in_20transmission_20capacity_20between_20two_20areas_91',['Investment in transmission capacity between two areas',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md169',1,'']]],
  ['investment_20problem_92',['investment problem',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md216',1,'Benders reformulation of the investment problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md213',1,'Constraints (for the investment problem)'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md214',1,'Investment problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html',1,'Mathematical aspects of the investment problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md219',1,'Reliability-constrained investment problem']]],
  ['investment_20problem_20generation_93',['Investment problem generation',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html',1,'']]],
  ['investment_20problem_20generation_3a_20tt_20problem_5fgeneration_20tt_94',['2- Investment problem generation: &lt;tt&gt;problem_generation&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md94',1,'']]],
  ['investment_20problem_20in_20antares_20xpansion_95',['The optimal investment problem in Antares-Xpansion',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html',1,'']]],
  ['investment_20tt_96',['&lt;tt&gt;max-investment&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md131',1,'']]],
  ['investment_20variables_97',['Investment variables',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html#autotoc_md203',1,'']]],
  ['iouterloopinputdatareader_98',['IOuterLoopInputDataReader',['../classOuterloop_1_1IOuterLoopInputDataReader.html',1,'Outerloop']]],
  ['iproblemproviderport_99',['IProblemProviderPort',['../classIProblemProviderPort.html',1,'']]],
  ['iproblemvariablesproviderport_100',['IProblemVariablesProviderPort',['../classIProblemVariablesProviderPort.html',1,'']]],
  ['iproblemwriter_101',['IProblemWriter',['../classIProblemWriter.html',1,'']]],
  ['iresultcapture_102',['IResultCapture',['../structCatch_1_1IResultCapture.html',1,'Catch']]],
  ['is_5faccurate_103',['is_accurate',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader.html#a0c3fa0cf225d9b7bb06864a8aa7f1b45',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['is_5fcallable_104',['is_callable',['../structCatch_1_1is__callable.html',1,'Catch']]],
  ['is_5fcallable_3c_20fun_28args_2e_2e_2e_29_3e_105',['is_callable&lt; Fun(Args...)&gt;',['../structCatch_1_1is__callable_3_01Fun_07Args_8_8_8_08_4.html',1,'Catch']]],
  ['is_5fcallable_5ftester_106',['is_callable_tester',['../structCatch_1_1is__callable__tester.html',1,'Catch']]],
  ['is_5frange_107',['is_range',['../structCatch_1_1is__range.html',1,'Catch']]],
  ['is_5frelaxed_108',['is_relaxed',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader.html#a4b43dd57f999df86ffacede36f47e197',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['isnot_109',['IsNot',['../classStringManip_1_1IsNot.html',1,'StringManip']]],
  ['isstreaminsertable_110',['IsStreamInsertable',['../classCatch_1_1Detail_1_1IsStreamInsertable.html',1,'Catch::Detail']]],
  ['issues_20please_20use_20the_20other_20ones_111',['⚠️ Single-file versions in Ubuntu are known to have MPI-related issues. Please use the other ones.',['../md_docs_2changelog_2CHANGELOG.html#autotoc_md18',1,'']]],
  ['istream_112',['IStream',['../structCatch_1_1IStream.html',1,'Catch']]],
  ['iteration_113',['Iteration',['../structOutput_1_1Iteration.html',1,'Output']]],
  ['iterationresultlog_114',['IterationResultLog',['../classxpansion_1_1logger_1_1IterationResultLog.html',1,'xpansion::logger']]],
  ['iterationsdata_115',['IterationsData',['../structOutput_1_1IterationsData.html',1,'Output']]],
  ['itestcaseregistry_116',['ITestCaseRegistry',['../structCatch_1_1ITestCaseRegistry.html',1,'Catch']]],
  ['itestinvoker_117',['ITestInvoker',['../structCatch_1_1ITestInvoker.html',1,'Catch']]],
  ['itransientexpression_118',['ITransientExpression',['../structCatch_1_1ITransientExpression.html',1,'Catch']]],
  ['iwriterlogger_119',['IWriterLogger',['../classIWriterLogger.html',1,'']]],
  ['ixpansionproblemsprovider_120',['IXpansionProblemsProvider',['../classIXpansionProblemsProvider.html',1,'']]]
];
