var searchData=
[
  ['a_20package_20manager_0',['Install with a package manager',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md69',1,'']]],
  ['a_20variable_20column_20id_20mapping_20file_1',['5- Creation of a variable / column ID mapping file',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md105',1,'']]],
  ['act_2',['act',['../classact.html',1,'']]],
  ['activelink_3',['ActiveLink',['../classActiveLink.html',1,'']]],
  ['activelinksbuilder_4',['ActiveLinksBuilder',['../classActiveLinksBuilder.html',1,'']]],
  ['add_5fcols_5',['add_cols',['../classProblem.html#a3a39dd85d31f7a5fe895fe8d119a7e69',1,'Problem::add_cols()'],['../classSolverAbstract.html#a4a4dacaf5af0d774302be7487f194f42',1,'SolverAbstract::add_cols()'],['../classSolverCbc.html#a4d0812f1777b1a4e43a71ed0d0e8c3f3',1,'SolverCbc::add_cols()'],['../classSolverClp.html#ab95a20cf2acc6d7a365a63d7e0923f49',1,'SolverClp::add_cols()'],['../classSolverXpress.html#a8e031ade7772323f466f16f3d9e45952',1,'SolverXpress::add_cols()'],['../classNOOPSolver.html#a1580de6c19d2196a778ed146cf85d96d',1,'NOOPSolver::add_cols()']]],
  ['add_5fcut_6',['add_cut',['../classWorkerMaster.html#a1278325052f29d3a4b145052a23761ad',1,'WorkerMaster']]],
  ['add_5fcut_5fby_5fiter_7',['add_cut_by_iter',['../classWorkerMaster.html#a3413236aeafd6292fd09f01b4f51486a',1,'WorkerMaster']]],
  ['add_5fdynamic_5fcut_8',['add_dynamic_cut',['../classWorkerMaster.html#ad82d7509516e2ddb7ed5d43e9b246f3e',1,'WorkerMaster']]],
  ['add_5fname_9',['add_name',['../classNOOPSolver.html#ae32c377fdb30d6d8969dc26f955d358e',1,'NOOPSolver::add_name()'],['../classSolverXpress.html#a3d66403a0b9cad3c4988c5f943fcfc57',1,'SolverXpress::add_name()'],['../classSolverClp.html#a8c52ca73a3482eee8e402dd9d95c1134',1,'SolverClp::add_name()'],['../classSolverCbc.html#a0990733602db4b38284455ef0aa0349a',1,'SolverCbc::add_name()'],['../classSolverAbstract.html#afc4ceb13f60ec7f53cdc166dd70baee6',1,'SolverAbstract::add_name()'],['../classProblem.html#a2fd6e04f639afc967adf2f1a3d3d4b85',1,'Problem::add_name()']]],
  ['add_5frows_10',['add_rows',['../classSolverClp.html#a94232131fe77df5b58b539e6fd0b10a9',1,'SolverClp::add_rows()'],['../classNOOPSolver.html#a8e091428888e75fcba2e8feb5a127054',1,'NOOPSolver::add_rows()'],['../classProblem.html#a8fb8c92a38162a74023e798e9e824c80',1,'Problem::add_rows()'],['../classSolverAbstract.html#a7cfec83d515d78f875e45c4743668be2',1,'SolverAbstract::add_rows()'],['../classSolverCbc.html#af74f4f01aef4f5bf99971d91e2000a10',1,'SolverCbc::add_rows()'],['../classSolverXpress.html#aa3387353e9219c23e22297b2943657dc',1,'SolverXpress::add_rows()']]],
  ['add_5fstream_11',['add_stream',['../classSolverAbstract.html#a4b0cf85b1d8d2b63c3bc8ef62ed036d9',1,'SolverAbstract']]],
  ['additional_20candidate_20constraints_12',['3- Read additional candidate constraints',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md103',1,'']]],
  ['additional_20characteristics_20for_20links_20of_20investment_20candidates_13',['Additional characteristics for links of investment candidates',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md163',1,'']]],
  ['additional_20constraints_20tt_14',['&lt;tt&gt;additional-constraints&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md184',1,'']]],
  ['additional_5fconstraints_15',['additional_constraints',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader.html#a4144519a671a579b2440aa61a06bf6b1',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['additionalconstraint_16',['additionalconstraint',['../classAdditionalConstraint.html#aac25a7a8f92a5ee43559630a5f4bcca6',1,'AdditionalConstraint::AdditionalConstraint(std::string sectionName_p, std::string constraintName_p, std::string sign_p, double rhs_p)'],['../classAdditionalConstraint.html#a6c15a4ee5ecfa901ba8a9e8d60383660',1,'AdditionalConstraint::AdditionalConstraint()=default'],['../classAdditionalConstraint.html',1,'AdditionalConstraint']]],
  ['additionalconstraints_17',['additionalconstraints',['../classAdditionalConstraints.html#aec74e09f6510d8f371a69b04afc0f877',1,'AdditionalConstraints::AdditionalConstraints(std::string constraints_file_path, ProblemGenerationLog::ProblemGenerationLoggerSharedPointer logger)'],['../classAdditionalConstraints.html#adb3cf7d561ce9b0c6a69b408505a3ee9',1,'AdditionalConstraints::AdditionalConstraints(ProblemGenerationLog::ProblemGenerationLoggerSharedPointer logger)'],['../classAdditionalConstraints.html',1,'AdditionalConstraints']]],
  ['additionalconstraintsreader_18',['additionalconstraintsreader',['../structAdditionalConstraintsReader.html#a13bb619592df9587a2d0bf6bffbbf870',1,'AdditionalConstraintsReader::AdditionalConstraintsReader(std::string const &amp;constraints_file_path, ProblemGenerationLog::ProblemGenerationLoggerSharedPointer logger)'],['../structAdditionalConstraintsReader.html#a39a522c1d724b360215ec54ed15ee6cd',1,'AdditionalConstraintsReader::AdditionalConstraintsReader(ProblemGenerationLog::ProblemGenerationLoggerSharedPointer logger)'],['../structAdditionalConstraintsReader.html',1,'AdditionalConstraintsReader']]],
  ['additionalconstraintsreadertest_19',['AdditionalConstraintsReaderTest',['../classAdditionalConstraintsReaderTest.html',1,'']]],
  ['additionalconstraintstest_20',['AdditionalConstraintsTest',['../classAdditionalConstraintsTest.html',1,'']]],
  ['addsubproblemcut_21',['addSubproblemCut',['../classWorkerMaster.html#acc3f28ce6ae84fc72955e36bb1679fbf',1,'WorkerMaster']]],
  ['addvariablestobinarise_22',['addVariablesToBinarise',['../classAdditionalConstraints.html#ab36807d147de7e46f29574156262ab9a',1,'AdditionalConstraints']]],
  ['addvariabletobinarise_23',['addVariableToBinarise',['../classAdditionalConstraints.html#adcd74c76f8273acaa05730110829537c',1,'AdditionalConstraints']]],
  ['algorithm_24',['algorithm',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md203',1,'Benders reformulation and decomposition algorithm'],['../md_docs_2user-guide_2get-started_2settings-definition.html',1,'Settings of the algorithm'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md206',1,'The Benders by batch algorithm'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md205',1,'The Benders decomposition algorithm']]],
  ['already_20installed_20capacity_20tt_25',['&lt;tt&gt;already-installed-capacity&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md121',1,'']]],
  ['already_20installed_20in_20direct_20link_20profile_20tt_26',['&lt;tt&gt;already-installed-[in]direct-link-profile&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md123',1,'']]],
  ['always_5ffalse_27',['always_false',['../structCatch_1_1always__false.html',1,'Catch']]],
  ['an_20antares_20simulation_28',['The operating cost as the solution of an Antares simulation',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md198',1,'']]],
  ['an_20antares_20xpansion_20study_29',['Set up an Antares-Xpansion study',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html',1,'']]],
  ['analysis_30',['analysis',['../classAnalysis.html',1,'Analysis'],['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md168',1,'Launch the sensitivity analysis'],['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md171',1,'Output of the sensitivity analysis'],['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md170',1,'Run the sensitivity analysis'],['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html',1,'Sensitivity analysis']]],
  ['analysis_20problem_31',['Mathematical formulation of the sensitivity analysis problem',['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md166',1,'']]],
  ['and_20capacity_20of_20the_20antares_20study_32',['Link between invested capacity and capacity of the Antares study',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md124',1,'']]],
  ['and_20costs_33',['Variables and costs',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md195',1,'']]],
  ['and_20decomposition_20algorithm_34',['Benders reformulation and decomposition algorithm',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md203',1,'']]],
  ['and_20get_20link_20column_20id_35',['1- Read candidates and get link column ID',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md99',1,'']]],
  ['and_20installation_20details_36',['Build and installation details',['../md_docs_2developer-guide_2install__from__sources_20-INSTALL.html#autotoc_md62',1,'']]],
  ['and_20investment_20cost_37',['Invested capacity and investment cost',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md196',1,'']]],
  ['annual_20cost_20per_20mw_20tt_38',['&lt;tt&gt;annual-cost-per-mw&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md117',1,'']]],
  ['annuity_20for_20decommissioning_20candidates_39',['Fixed-cost annuity for decommissioning candidates',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md162',1,'']]],
  ['annuity_20for_20investment_20candidates_40',['Fixed-cost annuity for investment candidates',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md161',1,'']]],
  ['antares_20n_20cpu_20tt_41',['&lt;tt&gt;--antares-n-cpu&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md143',1,'']]],
  ['antares_20optimization_20problem_20retrieval_42',['Antares optimization problem retrieval',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html',1,'']]],
  ['antares_20output_20directory_20tt_43',['&lt;tt&gt;--simulationName {last, your-antares-output-directory}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md140',1,'']]],
  ['antares_20problem_5fgeneration_20benders_20study_5fupdate_20sensitivity_20resume_20tt_44',['&lt;tt&gt;--step {full, antares, problem_generation, benders, study_update, sensitivity, resume}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md138',1,'']]],
  ['antares_20simulation_45',['The operating cost as the solution of an Antares simulation',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md198',1,'']]],
  ['antares_20simulator_20optimization_20problems_20retrieval_3a_20tt_20antares_20tt_46',['1- Antares-Simulator optimization problems retrieval: &lt;tt&gt;antares&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md84',1,'']]],
  ['antares_20study_47',['antares study',['../md_docs_2index.html#autotoc_md110',1,'Antares study'],['../index.html#autotoc_md2',1,'Antares study'],['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md124',1,'Link between invested capacity and capacity of the Antares study'],['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md155',1,'Prepare the Antares study']]],
  ['antares_20study_3a_20tt_20study_5fupdate_20tt_48',['4- Update of antares study: &lt;tt&gt;study_update&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md87',1,'']]],
  ['antares_20tt_49',['1- Antares-Simulator optimization problems retrieval: &lt;tt&gt;antares&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md84',1,'']]],
  ['antares_20version_20tt_50',['&lt;tt&gt;--antares-version&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md146',1,'']]],
  ['antares_20xpansion_51',['antares xpansion',['../index.html',1,'Antares-Xpansion'],['../md_docs_2user-guide_2get-started_2installation.html#autotoc_md131',1,'Download Antares-Xpansion'],['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md148',1,'Output of Antares-Xpansion'],['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md90',1,'Specific configuration for Antares-Xpansion'],['../md_docs_2user-guide_2optimization-principles_2investment-problem.html',1,'The optimal investment problem in Antares-Xpansion']]],
  ['antares_20xpansion_20changelog_52',['Antares-Xpansion changelog',['../md_docs_2changelog_2CHANGELOG.html',1,'']]],
  ['antares_20xpansion_20package_20executables_53',['Antares-Xpansion package executables',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md88',1,'']]],
  ['antares_20xpansion_20simulation_54',['antares xpansion simulation',['../md_docs_2index.html#autotoc_md111',1,'Antares-Xpansion simulation'],['../index.html#autotoc_md3',1,'Antares-Xpansion simulation']]],
  ['antares_20xpansion_20simulation_20procedure_55',['Antares-Xpansion simulation procedure',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html',1,'']]],
  ['antares_20xpansion_20study_56',['Set up an Antares-Xpansion study',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html',1,'']]],
  ['antares_5foutput_57',['antares_output',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader.html#a7ebd0291e5efb3c813ec863c9f31c80d',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['antares_5foutput_5fdir_58',['antares_output_dir',['../classantares__xpansion_1_1antares__driver_1_1AntaresDriver.html#a8440bc0602ca38c565287c80dcfbf0f2',1,'antares_xpansion::antares_driver::AntaresDriver']]],
  ['antares_5fxpansion_59',['antares_xpansion',['../namespaceantares__xpansion.html',1,'']]],
  ['antares_5fxpansion_3a_3aantares_5fdriver_60',['antares_driver',['../namespaceantares__xpansion_1_1antares__driver.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3abenders_5fdriver_61',['benders_driver',['../namespaceantares__xpansion_1_1benders__driver.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3aconfig_5floader_62',['config_loader',['../namespaceantares__xpansion_1_1config__loader.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3adriver_63',['driver',['../namespaceantares__xpansion_1_1driver.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3ainput_5fchecker_64',['input_checker',['../namespaceantares__xpansion_1_1input__checker.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3aproblem_5fgenerator_5fdriver_65',['problem_generator_driver',['../namespaceantares__xpansion_1_1problem__generator__driver.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3asensitivity_5fdriver_66',['sensitivity_driver',['../namespaceantares__xpansion_1_1sensitivity__driver.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3astudy_5fupdater_5fdriver_67',['study_updater_driver',['../namespaceantares__xpansion_1_1study__updater__driver.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3axpansion_5futils_68',['xpansion_utils',['../namespaceantares__xpansion_1_1xpansion__utils.html',1,'antares_xpansion']]],
  ['antares_5fxpansion_3a_3axpansionconfig_69',['xpansionConfig',['../namespaceantares__xpansion_1_1xpansionConfig.html',1,'antares_xpansion']]],
  ['antaresarchiveupdater_70',['AntaresArchiveUpdater',['../classAntaresArchiveUpdater.html',1,'']]],
  ['antaresarchiveupdaterexeerror_71',['AntaresArchiveUpdaterExeError',['../classantares__xpansion_1_1driver_1_1XpansionDriver_1_1AntaresArchiveUpdaterExeError.html',1,'antares_xpansion::driver::XpansionDriver']]],
  ['antaresarchiveupdaterexeoptions_72',['AntaresArchiveUpdaterExeOptions',['../classAntaresArchiveUpdaterExeOptions.html',1,'']]],
  ['antaresdriver_73',['AntaresDriver',['../classantares__xpansion_1_1antares__driver_1_1AntaresDriver.html',1,'antares_xpansion::antares_driver']]],
  ['antaresexecutionerror_74',['AntaresExecutionError',['../classantares__xpansion_1_1antares__driver_1_1AntaresDriver_1_1AntaresExecutionError.html',1,'antares_xpansion::antares_driver::AntaresDriver']]],
  ['antareslinkdatareader_75',['AntaresLinkDataReader',['../classAntaresLinkDataReader.html',1,'']]],
  ['antaresproblemtoxpansionproblemtranslator_76',['AntaresProblemToXpansionProblemTranslator',['../classAntaresProblemToXpansionProblemTranslator.html',1,'']]],
  ['antaresversionprovider_77',['AntaresVersionProvider',['../classAntaresVersionProvider.html',1,'']]],
  ['antaresversionproviderstub_78',['AntaresVersionProviderStub',['../classAntaresVersionProviderStub.html',1,'']]],
  ['approx_79',['Approx',['../classCatch_1_1Detail_1_1Approx.html',1,'Catch::Detail']]],
  ['archiveio_80',['ArchiveIO',['../classArchiveIO.html',1,'']]],
  ['archiveiogeneralexception_81',['ArchiveIOGeneralException',['../classArchiveIOGeneralException.html',1,'']]],
  ['archiveiospecificexception_82',['ArchiveIOSpecificException',['../classArchiveIOSpecificException.html',1,'']]],
  ['archivereader_83',['ArchiveReader',['../classArchiveReader.html',1,'']]],
  ['archivereadertest_84',['ArchiveReaderTest',['../classArchiveReaderTest.html',1,'']]],
  ['archiveupdatertest_85',['ArchiveUpdaterTest',['../classArchiveUpdaterTest.html',1,'']]],
  ['archivewriter_86',['ArchiveWriter',['../classArchiveWriter.html',1,'']]],
  ['archivewritertest_87',['ArchiveWriterTest',['../classArchiveWriterTest.html',1,'']]],
  ['area_20txt_20tt_88',['The file &lt;tt&gt;area.txt&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md94',1,'']]],
  ['areafileexception_89',['AreaFileException',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorDriver_1_1AreaFileException.html',1,'antares_xpansion::problem_generator_driver::ProblemGeneratorDriver']]],
  ['areas_90',['Investment in transmission capacity between two areas',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md156',1,'']]],
  ['as_91',['as',['../structCatch_1_1Generators_1_1as.html',1,'Catch::Generators']]],
  ['as_20the_20solution_20of_20an_20antares_20simulation_92',['The operating cost as the solution of an Antares simulation',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md198',1,'']]],
  ['aspects_20of_20the_20investment_20problem_93',['Mathematical aspects of the investment problem',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html',1,'']]],
  ['assertionhandler_94',['AssertionHandler',['../classCatch_1_1AssertionHandler.html',1,'Catch']]],
  ['assertioninfo_95',['AssertionInfo',['../structCatch_1_1AssertionInfo.html',1,'Catch']]],
  ['assertionreaction_96',['AssertionReaction',['../structCatch_1_1AssertionReaction.html',1,'Catch']]],
  ['automatic_20libraries_20compilation_20from_20git_97',['Automatic libraries compilation from git',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md70',1,'']]],
  ['autoreg_98',['AutoReg',['../structCatch_1_1AutoReg.html',1,'Catch']]]
];
