var searchData=
[
  ['m_20method_20benders_20mergemps_20adequacy_5fcriterion_20tt_0',['&lt;tt&gt;-m, --method {benders, mergeMPS, adequacy_criterion}&lt;/tt&gt;',['../md_docs_2reference_2cli.html#autotoc_md241',1,'']]],
  ['macos_1',['Linux/macOS',['../md_docs_2developer-guide_2install-from-source_2xpress.html#autotoc_md101',1,'']]],
  ['maintenance_2',['Refactoring &amp; Maintenance',['../md_docs_2overview_2CHANGELOG.html#autotoc_md152',1,'']]],
  ['manager_3',['Install with a VCPKG package manager',['../md_docs_2developer-guide_2install-from-source_2install-dependencies.html#autotoc_md76',1,'']]],
  ['mandatory_20arguments_4',['Mandatory arguments',['../md_docs_2reference_2trajectory-investment_2orchestration.html#autotoc_md294',1,'']]],
  ['mapping_20file_5',['5- Creation of a variable / column ID mapping file',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md131',1,'']]],
  ['mark_5findices_5fto_5fkeep_5fpresolve_6',['mark_indices_to_keep_presolve',['../classProblem.html#ac88e46f0d938d1e96195840043d800fc',1,'Problem::mark_indices_to_keep_presolve()'],['../classSolverAbstract.html#a921606b2acfc864c6e76c470064dce40',1,'SolverAbstract::mark_indices_to_keep_presolve()'],['../classSolverXpress.html#a0cfe27d07c07220bdce1368e220be826',1,'SolverXpress::mark_indices_to_keep_presolve()'],['../classSolverCbc.html#a89efc60109ea87a1d2f4090160dcd1ee',1,'SolverCbc::mark_indices_to_keep_presolve()'],['../classSolverClp.html#a9e616f254e74d5dcc6dad240514e991f',1,'SolverClp::mark_indices_to_keep_presolve()'],['../classNOOPSolver.html#aaa067994b51cd788f40541dc7316ab60',1,'NOOPSolver::mark_indices_to_keep_presolve()']]],
  ['markers_7',['Markers',['../md_docs_2agents_2testing.html#autotoc_md57',1,'']]],
  ['markers_8',['markers',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md325',1,'Test markers'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md336',1,'Test markers']]],
  ['master_9',['Master',['../classxpansion_1_1logger_1_1Master.html',1,'xpansion::logger']]],
  ['master_20merger_20executable_10',['Usage of the master merger executable',['../md_docs_2reference_2trajectory-investment_2merge-master.html#autotoc_md277',1,'']]],
  ['master_20merger_20info_20file_11',['Master merger info file',['../md_docs_2reference_2trajectory-investment_2merge-master.html#autotoc_md279',1,'']]],
  ['master_20problem_12',['4- Creation of master problem',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md130',1,'']]],
  ['master_20problem_20formulation_13',['Master problem formulation',['../md_docs_2reference_2outputs_2others.html#autotoc_md269',1,'']]],
  ['master_20problems_20of_20annual_20xpansion_20studies_14',['Merging the master problems of annual Xpansion studies',['../md_docs_2reference_2trajectory-investment_2merge-master.html',1,'']]],
  ['masterfilenotfound_15',['MasterFileNotFound',['../classantares__xpansion_1_1resume__study_1_1ResumeStudy_1_1MasterFileNotFound.html',1,'antares_xpansion::resume_study::ResumeStudy']]],
  ['mastergeneration_16',['MasterGeneration',['../classMasterGeneration.html',1,'']]],
  ['mastergenerationtest_17',['MasterGenerationTest',['../classMasterGenerationTest.html',1,'']]],
  ['masterloggertest_18',['MasterLoggerTest',['../classMasterLoggerTest.html',1,'']]],
  ['masterproblembuilder_19',['MasterProblemBuilder',['../classMasterProblemBuilder.html',1,'']]],
  ['masterupdatebase_20',['MasterUpdateBase',['../classOuterloop_1_1MasterUpdateBase.html',1,'Outerloop']]],
  ['masterupdatebasetest_21',['MasterUpdateBaseTest',['../classMasterUpdateBaseTest.html',1,'']]],
  ['mathlogger_22',['MathLogger',['../structMathLogger.html',1,'']]],
  ['mathloggerbase_23',['MathLoggerBase',['../structMathLoggerBase.html',1,'']]],
  ['mathloggerbaseexternalloop_24',['MathLoggerBaseExternalLoop',['../structMathLoggerBaseExternalLoop.html',1,'']]],
  ['mathloggerbehaviour_25',['MathLoggerBehaviour',['../structMathLoggerBehaviour.html',1,'']]],
  ['mathloggerbendersbybatch_26',['MathLoggerBendersByBatch',['../structMathLoggerBendersByBatch.html',1,'']]],
  ['mathloggerbendersbybatchexternalloop_27',['MathLoggerBendersByBatchExternalLoop',['../structMathLoggerBendersByBatchExternalLoop.html',1,'']]],
  ['mathloggerdriver_28',['MathLoggerDriver',['../classMathLoggerDriver.html',1,'']]],
  ['mathloggerexternalloopspecific_29',['MathLoggerExternalLoopSpecific',['../structMathLoggerExternalLoopSpecific.html',1,'']]],
  ['mathloggerfactory_30',['MathLoggerFactory',['../classMathLoggerFactory.html',1,'']]],
  ['mathloggerfile_31',['MathLoggerFile',['../classMathLoggerFile.html',1,'']]],
  ['mathloggerimplementation_32',['MathLoggerImplementation',['../classMathLoggerImplementation.html',1,'']]],
  ['mathloggerostream_33',['MathLoggerOstream',['../classMathLoggerOstream.html',1,'']]],
  ['max_5fcumulative_5finvestment_5fper_5fnode_20tt_34',['&lt;tt&gt;type: max_cumulative_investment_per_node&lt;/tt&gt;',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md309',1,'']]],
  ['max_5fcumulative_5fretirement_5fper_5fnode_20tt_35',['&lt;tt&gt;type: max_cumulative_retirement_per_node&lt;/tt&gt;',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md311',1,'']]],
  ['max_5finvestment_5fper_5fnode_5fper_5fcandidate_20tt_36',['&lt;tt&gt;type: max_investment_per_node_per_candidate&lt;/tt&gt;',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md308',1,'']]],
  ['max_5fretirement_5fper_5fnode_5fper_5fcandidate_20tt_37',['&lt;tt&gt;type: max_retirement_per_node_per_candidate&lt;/tt&gt;',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md310',1,'']]],
  ['maxitervalueerror_38',['MaxIterValueError',['../classantares__xpansion_1_1input__checker_1_1MaxIterValueError.html',1,'antares_xpansion::input_checker']]],
  ['maxunitsandmaxinvestmentarenullsimultaneously_39',['MaxUnitsAndMaxInvestmentAreNullSimultaneously',['../classantares__xpansion_1_1input__checker_1_1MaxUnitsAndMaxInvestmentAreNullSimultaneously.html',1,'antares_xpansion::input_checker']]],
  ['maxunitsandmaxinvestmentnonnullsimultaneously_40',['MaxUnitsAndMaxInvestmentNonNullSimultaneously',['../classantares__xpansion_1_1input__checker_1_1MaxUnitsAndMaxInvestmentNonNullSimultaneously.html',1,'antares_xpansion::input_checker']]],
  ['mcyearnotinactiveyearslisterror_41',['McYearNotInActiveYearsListError',['../classYearlyWeightsWriter_1_1McYearNotInActiveYearsListError.html',1,'YearlyWeightsWriter']]],
  ['memory_20optimization_20resolution_20process_42',['Memory optimization Resolution process',['../md_docs_2reference_2benders_2in-memory-compact-subproblems.html#autotoc_md227',1,'']]],
  ['merge_5flocal_5fsolver_43',['merge_local_solver',['../classAbstractMergeMPS.html#a5b71702ecca3ab9b5147169a297658af',1,'AbstractMergeMPS']]],
  ['mergemasterdata_44',['MergeMasterData',['../classdriver__merge__master_1_1MergeMasterData.html',1,'driver_merge_master']]],
  ['mergemasterdriver_45',['MergeMasterDriver',['../classdriver__merge__master_1_1MergeMasterDriver.html',1,'driver_merge_master']]],
  ['mergemasterexecutionerror_46',['MergeMasterExecutionError',['../classdriver__merge__master_1_1MergeMasterDriver_1_1MergeMasterExecutionError.html',1,'driver_merge_master::MergeMasterDriver']]],
  ['mergemasterexeerror_47',['MergeMasterExeError',['../classdriver__merge__master_1_1MergeMasterDriver_1_1MergeMasterExeError.html',1,'driver_merge_master::MergeMasterDriver']]],
  ['mergemasterinputerror_48',['MergeMasterInputError',['../classdriver__merge__master_1_1MergeMasterDriver_1_1MergeMasterInputError.html',1,'driver_merge_master::MergeMasterDriver']]],
  ['mergemastersubproblemmps_49',['MergeMasterSubproblemMPS',['../classMergeMasterSubproblemMPS.html',1,'']]],
  ['mergemastertrajectorymps_50',['MergeMasterTrajectoryMPS',['../classMergeMasterTrajectoryMPS.html',1,'']]],
  ['mergemps_20adequacy_5fcriterion_20tt_51',['&lt;tt&gt;-m, --method {benders, mergeMPS, adequacy_criterion}&lt;/tt&gt;',['../md_docs_2reference_2cli.html#autotoc_md241',1,'']]],
  ['mergempstest_52',['MergeMPSTest',['../classMergeMPSTest.html',1,'']]],
  ['merger_20executable_53',['Usage of the master merger executable',['../md_docs_2reference_2trajectory-investment_2merge-master.html#autotoc_md277',1,'']]],
  ['merger_20info_20file_54',['Master merger info file',['../md_docs_2reference_2trajectory-investment_2merge-master.html#autotoc_md279',1,'']]],
  ['mergeweightsdata_55',['MergeWeightsData',['../classdriver__merge__weights_1_1MergeWeightsData.html',1,'driver_merge_weights']]],
  ['mergeweightsdriver_56',['MergeWeightsDriver',['../classdriver__merge__weights_1_1MergeWeightsDriver.html',1,'driver_merge_weights']]],
  ['mergeweightsexecutionerror_57',['MergeWeightsExecutionError',['../classdriver__merge__weights_1_1MergeWeightsDriver_1_1MergeWeightsExecutionError.html',1,'driver_merge_weights::MergeWeightsDriver']]],
  ['mergeweightsexeerror_58',['MergeWeightsExeError',['../classdriver__merge__weights_1_1MergeWeightsDriver_1_1MergeWeightsExeError.html',1,'driver_merge_weights::MergeWeightsDriver']]],
  ['mergeweightsinputerror_59',['MergeWeightsInputError',['../classdriver__merge__weights_1_1MergeWeightsDriver_1_1MergeWeightsInputError.html',1,'driver_merge_weights::MergeWeightsDriver']]],
  ['mergeweightstrajectory_60',['MergeWeightsTrajectory',['../classMergeWeightsTrajectory.html',1,'']]],
  ['merging_20the_20master_20problems_20of_20annual_20xpansion_20studies_61',['Merging the master problems of annual Xpansion studies',['../md_docs_2reference_2trajectory-investment_2merge-master.html',1,'']]],
  ['method_20benders_20mergemps_20adequacy_5fcriterion_20tt_62',['&lt;tt&gt;-m, --method {benders, mergeMPS, adequacy_criterion}&lt;/tt&gt;',['../md_docs_2reference_2cli.html#autotoc_md241',1,'']]],
  ['micro_20iterations_63',['Micro Iterations',['../md_docs_2reference_2benders_2micro-iterations.html',1,'']]],
  ['micro_20iterations_64',['Launching a study with micro-iterations',['../md_docs_2reference_2benders_2micro-iterations.html#autotoc_md232',1,'']]],
  ['min_5finvestment_5fper_5fnode_5fper_5fcandidate_20tt_65',['&lt;tt&gt;type: min_investment_per_node_per_candidate&lt;/tt&gt;',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md312',1,'']]],
  ['min_5fretirement_5fper_5fnode_5fper_5fcandidate_20tt_66',['&lt;tt&gt;type: min_retirement_per_node_per_candidate&lt;/tt&gt;',['../md_docs_2reference_2trajectory-investment_2user-input.html#autotoc_md313',1,'']]],
  ['mini_5finstance_5finfeasible_67',['mini_instance_INFEASIBLE',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md323',1,'mini_instance_INFEASIBLE'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md334',1,'mini_instance_INFEASIBLE']]],
  ['mini_5finstance_5flp_5fdefault_68',['mini_instance_LP_default',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md320',1,'mini_instance_LP_default'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md331',1,'mini_instance_LP_default']]],
  ['mini_5finstance_5fmip_5fdefault_69',['mini_instance_MIP_default',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md321',1,'mini_instance_MIP_default'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md332',1,'mini_instance_MIP_default']]],
  ['mini_5finstance_5funbounded_70',['mini_instance_UNBOUNDED',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md322',1,'mini_instance_UNBOUNDED'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md333',1,'mini_instance_UNBOUNDED']]],
  ['mini_5fnetwork_5fdefault_71',['mini_network_default',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md318',1,'mini_network_default'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md329',1,'mini_network_default']]],
  ['mini_5fnetwork_5fslave_5fweight_72',['mini_network_slave_weight',['..//github/workspace/tests/end_to_end/benders/README.md#autotoc_md319',1,'mini_network_slave_weight'],['..//github/workspace/tests/end_to_end/restart/README.md#autotoc_md330',1,'mini_network_slave_weight']]],
  ['mismatchedparameters_73',['MismatchedParameters',['../classProblemGenerationOptions_1_1MismatchedParameters.html',1,'ProblemGenerationOptions']]],
  ['missingantaresoutput_74',['MissingAntaresOutput',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1MissingAntaresOutput.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['missingfile_75',['MissingFile',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1MissingFile.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['missingparameters_76',['MissingParameters',['../classProblemGenerationOptions_1_1MissingParameters.html',1,'ProblemGenerationOptions']]],
  ['missingsimulationname_77',['MissingSimulationName',['../classantares__xpansion_1_1config__loader_1_1ConfigLoader_1_1MissingSimulationName.html',1,'antares_xpansion::config_loader::ConfigLoader']]],
  ['modification_20of_20mps_20file_78',['2- Modification of .mps file',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md126',1,'']]],
  ['modification_20of_20weekly_20problems_20with_20tt_20lp_5fnamer_20tt_79',['Modification of weekly problems with &lt;tt&gt;lp_namer&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md124',1,'']]],
  ['modifications_20for_20em_20satellite_20problems_20em_80',['Modifications for &lt;em&gt;satellite problems&lt;/em&gt;',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md128',1,'']]],
  ['motivation_81',['Motivation',['../md_docs_2reference_2benders_2in-memory-compact-subproblems.html#autotoc_md222',1,'']]],
  ['mpi_20related_20issues_20please_20use_20the_20other_20ones_82',['⚠️ Single-file versions in Ubuntu are known to have MPI-related issues. Please use the other ones.',['../md_docs_2overview_2CHANGELOG.html#autotoc_md168',1,'']]],
  ['mpicommunicationstrategy_83',['MpiCommunicationStrategy',['../classMpiCommunicationStrategy.html',1,'']]],
  ['mps_20file_84',['2- Modification of .mps file',['../md_docs_2developer-guide_2xpansion-steps_2problem-modification.html#autotoc_md126',1,'']]],
  ['mps_20optimized_20tt_85',['&lt;tt&gt;--problem-format {MPS, OPTIMIZED}&lt;/tt&gt;',['../md_docs_2reference_2cli.html#autotoc_md242',1,'']]],
  ['mps_20tt_20file_86',['&lt;tt&gt;variables.txt&lt;/tt&gt; file for each &lt;tt&gt;.mps&lt;/tt&gt; file',['../md_docs_2developer-guide_2xpansion-steps_2antares-solver-problem.html#autotoc_md110',1,'']]],
  ['mps_20tt_20files_20for_20the_20weekly_20optimization_20problems_87',['&lt;tt&gt;.mps&lt;/tt&gt; files for the weekly optimization problems',['../md_docs_2developer-guide_2xpansion-steps_2antares-solver-problem.html#autotoc_md109',1,'']]],
  ['mpsfileproblemprovideradapter_88',['MPSFileProblemProviderAdapter',['../classMPSFileProblemProviderAdapter.html',1,'']]],
  ['mpstxtwritertest_89',['MpsTxtWriterTest',['../classMpsTxtWriterTest.html',1,'']]],
  ['mpszipfileexception_90',['MpsZipFileException',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorDriver_1_1MpsZipFileException.html',1,'antares_xpansion::problem_generator_driver::ProblemGeneratorDriver']]],
  ['multiple_20problem_20generation_91',['Multiple problem generation',['../md_docs_2reference_2trajectory-investment_2multiple-problem-generation.html',1,'']]],
  ['multiplealreadyinstalledcapacitydetectedforlink_92',['MultipleAlreadyInstalledCapacityDetectedForLink',['../classActiveLinksBuilder_1_1MultipleAlreadyInstalledCapacityDetectedForLink.html',1,'ActiveLinksBuilder']]],
  ['multiplealreadyinstalledprofiledetectedforlink_93',['MultipleAlreadyInstalledProfileDetectedForLink',['../classActiveLinksBuilder_1_1MultipleAlreadyInstalledProfileDetectedForLink.html',1,'ActiveLinksBuilder']]],
  ['multiplelinkiddetectedforlink_94',['MultipleLinkIddetectedForLink',['../classActiveLinksBuilder_1_1MultipleLinkIddetectedForLink.html',1,'ActiveLinksBuilder']]],
  ['multipleproblemgeneration_95',['MultipleProblemGeneration',['../classMultipleProblemGeneration.html',1,'']]],
  ['multipleproblemgenerationdata_96',['MultipleProblemGenerationData',['../classdriver__multiple__problem__gen_1_1MultipleProblemGenerationData.html',1,'driver_multiple_problem_gen']]],
  ['multipleproblemgenerationdriver_97',['MultipleProblemGenerationDriver',['../classdriver__multiple__problem__gen_1_1MultipleProblemGenerationDriver.html',1,'driver_multiple_problem_gen']]],
  ['multipleproblemgenerationexecutionerror_98',['MultipleProblemGenerationExecutionError',['../classdriver__multiple__problem__gen_1_1MultipleProblemGenerationDriver_1_1MultipleProblemGenerationExecutionError.html',1,'driver_multiple_problem_gen::MultipleProblemGenerationDriver']]],
  ['multipleproblemgenerationexeerror_99',['MultipleProblemGenerationExeError',['../classdriver__multiple__problem__gen_1_1MultipleProblemGenerationDriver_1_1MultipleProblemGenerationExeError.html',1,'driver_multiple_problem_gen::MultipleProblemGenerationDriver']]],
  ['multipleproblemgenerationexeoptions_100',['MultipleProblemGenerationExeOptions',['../classMultipleProblemGenerationExeOptions.html',1,'']]],
  ['multiply_5fobj_5fby_5fweight_5ffactor_101',['multiply_obj_by_weight_factor',['../classAbstractMergeMPS.html#a3564177205bdc0a9231ce4fef65c31aa',1,'AbstractMergeMPS']]]
];
