var searchData=
[
  ['package_20executables_0',['Antares-Xpansion package executables',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md119',1,'']]],
  ['package_20manager_1',['Install with a VCPKG package manager',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md88',1,'']]],
  ['parameters_2',['parameters',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md172',1,'Command line parameters'],['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md150',1,'Details of the parameters'],['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md212',1,'Details of the parameters']]],
  ['parse_5ftrajectory_5fuser_5ffile_3',['parse_trajectory_user_file',['../classuser__input__translation_1_1TrajectoryModule.html#aa2abbf6433de87715ee6b1c8b5e9cf85',1,'user_input_translation.TrajectoryModule.parse_trajectory_user_file()'],['../classtrajectory__module_1_1TrajectoryModule.html#ae2fbd8007ee1d3372122dea79558121c',1,'trajectory_module.TrajectoryModule.parse_trajectory_user_file()']]],
  ['parser_20translator_4',[' Input file parser &amp; translator',['../md_docs_2user-guide_2trajectory-investment_2user-input.html#autotoc_md271',1,'']]],
  ['parsing_5',['User input file parsing',['../md_docs_2user-guide_2trajectory-investment_2user-input.html',1,'']]],
  ['paths_20archives_20file_6',['Study paths / archives file',['../md_docs_2user-guide_2trajectory-investment_2multiple-problem-generation.html#autotoc_md261',1,'']]],
  ['pdf_20generation_7',['PDF generation',['../md_docs_2how__to.html#autotoc_md139',1,'']]],
  ['per_20mw_20tt_8',['&lt;tt&gt;annual-cost-per-mw&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md153',1,'']]],
  ['perfplotsgenerator_9',['PerfPlotsGenerator',['../classperformance_1_1PerfPlotsGenerator.html',1,'performance']]],
  ['platforms_10',['Handling Different Platforms',['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html#autotoc_md113',1,'']]],
  ['please_20use_20the_20other_20ones_11',['⚠️ Single-file versions in Ubuntu are known to have MPI-related issues. Please use the other ones.',['../md_docs_2changelog_2CHANGELOG.html#autotoc_md29',1,'']]],
  ['positivefloatvalueerror_12',['PositiveFloatValueError',['../classantares__xpansion_1_1input__checker_1_1PositiveFloatValueError.html',1,'antares_xpansion::input_checker']]],
  ['pre_20build_20dependency_13',['Using pre-build dependency',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md93',1,'']]],
  ['predicate_14',['Predicate',['../structPredicate.html',1,'']]],
  ['prepare_20the_20antares_20study_15',['Prepare the Antares study',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md193',1,'']]],
  ['prepare_5fdrivers_16',['prepare_drivers',['../classantares__xpansion_1_1full__run__driver_1_1FullRunDriver.html#aa41da6a9b74f253aed32501ce17b1fda',1,'antares_xpansion::full_run_driver::FullRunDriver']]],
  ['prepare_5ffolder_17',['prepare_folder',['../classdriver__trajectory_1_1TrajectoryInvestmentDriver.html#a247f5bf7e70d90b0e0b465e2eb0ce74d',1,'driver_trajectory::TrajectoryInvestmentDriver']]],
  ['prepare_5fresolution_5foptions_5ffile_18',['prepare_resolution_options_file',['../classdriver__resolution_1_1TrajectoryResolutionDriver.html#a1b25c911352ddd15806ffaf5b800cf92',1,'driver_resolution::TrajectoryResolutionDriver']]],
  ['presolve_19',['Presolve',['../classPresolve.html',1,'']]],
  ['presolve_20',['Calling the presolve',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html#autotoc_md232',1,'']]],
  ['presolve_20resume_20tt_21',['&lt;tt&gt;--step {full, antares, problem_generation, benders, study_update, sensitivity, presolve, resume}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md174',1,'']]],
  ['presolve_20tt_22',['&lt;tt&gt;--presolve&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md182',1,'']]],
  ['presolve_5fonly_23',['presolve_only',['../classProblem.html#afc5b4b38128ca8910c2337a78532d0fe',1,'Problem::presolve_only()'],['../classSolverAbstract.html#aba0acac777ba9772c45192f7c592129a',1,'SolverAbstract::presolve_only()'],['../classSolverXpress.html#a3d625d9a37fc658c0484cfce08a15a1a',1,'SolverXpress::presolve_only()'],['../classSolverCbc.html#a15eaa73751b90280e58d70c31adb1f01',1,'SolverCbc::presolve_only()'],['../classSolverClp.html#aab589e50b2dcc4b32fdc08d6f10bec0f',1,'SolverClp::presolve_only()'],['../classNOOPSolver.html#a8e5a2b8c83cc87fe0a9d7328ee4ded70',1,'NOOPSolver::presolve_only()']]],
  ['presolvedata_24',['PresolveData',['../classantares__xpansion_1_1presolve__driver_1_1PresolveData.html',1,'antares_xpansion::presolve_driver']]],
  ['presolvedriver_25',['PresolveDriver',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver.html',1,'antares_xpansion::presolve_driver']]],
  ['presolveexecutionerror_26',['PresolveExecutionError',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver_1_1PresolveExecutionError.html',1,'antares_xpansion::presolve_driver::PresolveDriver']]],
  ['presolveinputpatherror_27',['PresolveInputPathError',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver_1_1PresolveInputPathError.html',1,'antares_xpansion::presolve_driver::PresolveDriver']]],
  ['presolveoptions_28',['PresolveOptions',['../structPresolveOptions.html',1,'']]],
  ['presolveoptionsfileerror_29',['PresolveOptionsFileError',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver_1_1PresolveOptionsFileError.html',1,'antares_xpansion::presolve_driver::PresolveDriver']]],
  ['print_30',['print',['../classSimulationOptions.html#a9f76fa0b9615eac54d0e6394bbe50df8',1,'SimulationOptions::print()'],['../classuser__input__translation_1_1TrajectoryModule.html#a1d3875e16aea8301386b17d1510a6e31',1,'user_input_translation.TrajectoryModule.print()'],['../classtrajectory__module_1_1TrajectoryModule.html#affbc1aba335913eb1572fa92cfea24d5',1,'trajectory_module.TrajectoryModule.print()']]],
  ['problem_31',['Problem',['../classProblem.html',1,'']]],
  ['problem_32',['problem',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md135',1,'4- Creation of master problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md244',1,'Benders reformulation of the investment problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md241',1,'Constraints (for the investment problem)'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md242',1,'Investment problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html',1,'Mathematical aspects of the investment problem'],['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md204',1,'Mathematical formulation of the sensitivity analysis problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md247',1,'Reliability-constrained investment problem'],['../md_docs_2user-guide_2trajectory-investment_2trajectory-problem.html',1,'Trajectory investment problem']]],
  ['problem_20format_20mps_20optimized_20tt_33',['&lt;tt&gt;--problem-format {MPS, OPTIMIZED}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md178',1,'']]],
  ['problem_20formulation_34',['Problem formulation',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md234',1,'']]],
  ['problem_20generation_35',['problem generation',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html',1,'Investment problem generation'],['../md_docs_2user-guide_2trajectory-investment_2multiple-problem-generation.html',1,'Multiple problem generation']]],
  ['problem_20generation_3a_20tt_20problem_5fgeneration_20tt_36',['2- Investment problem generation: &lt;tt&gt;problem_generation&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md116',1,'']]],
  ['problem_20in_20antares_20xpansion_37',['The optimal investment problem in Antares-Xpansion',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html',1,'']]],
  ['problem_20retrieval_38',['Antares optimization problem retrieval',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html',1,'']]],
  ['problem_5fgeneration_20benders_20study_5fupdate_20sensitivity_20presolve_20resume_20tt_39',['&lt;tt&gt;--step {full, antares, problem_generation, benders, study_update, sensitivity, presolve, resume}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md174',1,'']]],
  ['problem_5fgeneration_20tt_40',['2- Investment problem generation: &lt;tt&gt;problem_generation&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md116',1,'']]],
  ['problemconstructiontest_41',['ProblemConstructionTest',['../classProblemConstructionTest.html',1,'']]],
  ['problemdata_42',['ProblemData',['../structOutput_1_1ProblemData.html',1,'Output::ProblemData'],['../structProblemData.html',1,'ProblemData']]],
  ['problemgeneration_43',['ProblemGeneration',['../classProblemGeneration.html',1,'']]],
  ['problemgenerationexeoptions_44',['ProblemGenerationExeOptions',['../classProblemGenerationExeOptions.html',1,'']]],
  ['problemgenerationexeoptionstest_45',['ProblemGenerationExeOptionsTest',['../classProblemGenerationExeOptionsTest.html',1,'']]],
  ['problemgenerationfilelogger_46',['ProblemGenerationFileLogger',['../classProblemGenerationLog_1_1ProblemGenerationFileLogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationilogger_47',['ProblemGenerationILogger',['../classProblemGenerationLog_1_1ProblemGenerationILogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationlogger_48',['ProblemGenerationLogger',['../classProblemGenerationLog_1_1ProblemGenerationLogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationloggertest_49',['ProblemGenerationLoggerTest',['../classProblemGenerationLoggerTest.html',1,'']]],
  ['problemgenerationoptions_50',['ProblemGenerationOptions',['../classProblemGenerationOptions.html',1,'']]],
  ['problemgenerationostreamlogger_51',['ProblemGenerationOstreamLogger',['../classProblemGenerationLog_1_1ProblemGenerationOstreamLogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationspyandmock_52',['ProblemGenerationSpyAndMock',['../classProblemGenerationSpyAndMock.html',1,'']]],
  ['problemgeneratordata_53',['ProblemGeneratorData',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorData.html',1,'antares_xpansion::problem_generator_driver']]],
  ['problemgeneratordriver_54',['ProblemGeneratorDriver',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorDriver.html',1,'antares_xpansion::problem_generator_driver']]],
  ['problemmodifier_55',['ProblemModifier',['../classProblemModifier.html',1,'']]],
  ['problemmodifiercapex_56',['ProblemModifierCapex',['../classProblemModifierCapex.html',1,'']]],
  ['problemmodifierprojection_57',['ProblemModifierProjection',['../classProblemModifierProjection.html',1,'']]],
  ['problemmodifiertest_58',['ProblemModifierTest',['../classProblemModifierTest.html',1,'']]],
  ['problemmodifiertestmultichronicle_59',['ProblemModifierTestMultiChronicle',['../classProblemModifierTestMultiChronicle.html',1,'']]],
  ['problemmodifiertestwithprofile_60',['ProblemModifierTestWithProfile',['../classProblemModifierTestWithProfile.html',1,'']]],
  ['problemnamecase_61',['ProblemNameCase',['../structProblemNameCase.html',1,'']]],
  ['problems_62',['problems',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md123',1,'&lt;tt&gt;.mps&lt;/tt&gt; files for the weekly optimization problems'],['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md132',1,'Initial weekly problems']]],
  ['problems_20em_63',['Modifications for &lt;em&gt;satellite problems&lt;/em&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md133',1,'']]],
  ['problems_20of_20annual_20xpansion_20studies_64',['Merging the master problems of annual Xpansion studies',['../md_docs_2user-guide_2trajectory-investment_2merge-master.html',1,'']]],
  ['problems_20retrieval_3a_20tt_20antares_20tt_65',['1- Antares-Simulator optimization problems retrieval: &lt;tt&gt;antares&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md115',1,'']]],
  ['problems_20with_20tt_20lp_5fnamer_20tt_66',['Modification of weekly problems with &lt;tt&gt;lp_namer&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md129',1,'']]],
  ['problemvariables_67',['ProblemVariables',['../structProblemVariables.html',1,'']]],
  ['problemvariablesfileadapter_68',['ProblemVariablesFileAdapter',['../classProblemVariablesFileAdapter.html',1,'']]],
  ['problemvariablesfromproblemadapter_69',['ProblemVariablesFromProblemAdapter',['../classProblemVariablesFromProblemAdapter.html',1,'']]],
  ['problemvariableszipadapter_70',['ProblemVariablesZipAdapter',['../classProblemVariablesZipAdapter.html',1,'']]],
  ['procedure_71',['Antares-Xpansion simulation procedure',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html',1,'']]],
  ['profile_20tt_72',['profile tt',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md158',1,'&lt;tt&gt;[in]direct-link-profile&lt;/tt&gt;'],['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md159',1,'&lt;tt&gt;already-installed-[in]direct-link-profile&lt;/tt&gt;']]],
  ['profilefilenegativevalue_73',['ProfileFileNegativeValue',['../classantares__xpansion_1_1input__checker_1_1ProfileFileNegativeValue.html',1,'antares_xpansion.input_checker.ProfileFileNegativeValue'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileNegativeValue.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileNegativeValue']]],
  ['profilefilenotexists_74',['ProfileFileNotExists',['../classantares__xpansion_1_1input__checker_1_1ProfileFileNotExists.html',1,'antares_xpansion::input_checker']]],
  ['profilefilevalueerror_75',['ProfileFileValueError',['../classantares__xpansion_1_1input__checker_1_1ProfileFileValueError.html',1,'antares_xpansion.input_checker.ProfileFileValueError'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileValueError.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileValueError']]],
  ['profilefilewrongnumberofcolumns_76',['ProfileFileWrongNumberOfcolumns',['../classantares__xpansion_1_1input__checker_1_1ProfileFileWrongNumberOfcolumns.html',1,'antares_xpansion.input_checker.ProfileFileWrongNumberOfcolumns'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileWrongNumberOfcolumns.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileWrongNumberOfcolumns']]],
  ['profilefilewrongnumberoflines_77',['ProfileFileWrongNumberOfLines',['../classantares__xpansion_1_1input__checker_1_1ProfileFileWrongNumberOfLines.html',1,'antares_xpansion.input_checker.ProfileFileWrongNumberOfLines'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileWrongNumberOfLines.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileWrongNumberOfLines']]],
  ['profilelinkchecker_78',['ProfileLinkChecker',['../classantares__xpansion_1_1profile__link__checker_1_1ProfileLinkChecker.html',1,'antares_xpansion::profile_link_checker']]],
  ['profiles_20depending_20on_20the_20monte_20carlo_20year_79',['Using different profiles depending on the Monte-Carlo year',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md161',1,'']]],
  ['profilesofdifferentdimensions_80',['ProfilesOfDifferentDimensions',['../classantares__xpansion_1_1candidates__reader_1_1ProfilesOfDifferentDimensions.html',1,'antares_xpansion::candidates_reader']]],
  ['profilesvalueerror_81',['ProfilesValueError',['../classantares__xpansion_1_1candidates__reader_1_1ProfilesValueError.html',1,'antares_xpansion::candidates_reader']]],
  ['pshiftmax_5f_82',['pShiftMax_',['../structLinkdataRecord_1_1FileColumns.html#a8d83f0f99914a833dfb34896ab69be36',1,'LinkdataRecord::FileColumns']]],
  ['pshiftmin_5f_83',['pShiftMin_',['../structLinkdataRecord_1_1FileColumns.html#a087c9dfcfef544c84f61925adcc1a7d4',1,'LinkdataRecord::FileColumns']]],
  ['python_20orchestrator_20tt_20get_5fnames_20tt_84',['Python orchestrator &lt;tt&gt;get_names&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md128',1,'']]],
  ['python_20version_85',['@ref &quot;python-version&quot; &quot;Python version&quot;',['../md_docs_2developer-guide_2install__from__sources_21-Development-requirements.html#autotoc_md85',1,'']]],
  ['python_20version_20python_20version_86',['@ref &quot;python-version&quot; &quot;Python version&quot;',['../md_docs_2developer-guide_2install__from__sources_21-Development-requirements.html#autotoc_md85',1,'']]]
];
