var searchData=
[
  ['package_20executables_0',['Antares-Xpansion package executables',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md183',1,'']]],
  ['package_20manager_1',['Install with a VCPKG package manager',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md150',1,'']]],
  ['parameters_2',['parameters',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md236',1,'Command line parameters'],['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md214',1,'Details of the parameters'],['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md277',1,'Details of the parameters']]],
  ['parse_5ftrajectory_5fuser_5ffile_3',['parse_trajectory_user_file',['../classuser__input__translation_1_1UserInputTranslator.html#ad5813f046fe5f99444c42a695c7a3c42',1,'user_input_translation::UserInputTranslator']]],
  ['parser_20translator_4',['Input file parser &amp; translator',['../md_docs_2user-guide_2trajectory-investment_2user-input.html#autotoc_md345',1,'']]],
  ['parsing_5',['User input file parsing',['../md_docs_2user-guide_2trajectory-investment_2user-input.html',1,'']]],
  ['paths_20archives_20file_6',['Study paths / archives file',['../md_docs_2user-guide_2trajectory-investment_2multiple-problem-generation.html#autotoc_md326',1,'']]],
  ['pdf_20generation_7',['PDF generation',['../md_docs_2how__to.html#autotoc_md203',1,'']]],
  ['per_20mw_20tt_8',['&lt;tt&gt;annual-cost-per-mw&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md217',1,'']]],
  ['performance_9',['Performance',['../md_docs_2agents_2cpp-conventions.html#autotoc_md23',1,'']]],
  ['performantaressimulation_10',['performAntaresSimulation',['../classProblemGeneration.html#a4a957acac85539627b906c1fca1eeb5f',1,'ProblemGeneration']]],
  ['perfplotsgenerator_11',['PerfPlotsGenerator',['../classperformance_1_1PerfPlotsGenerator.html',1,'performance']]],
  ['platforms_12',['Handling Different Platforms',['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html#autotoc_md174',1,'']]],
  ['please_20use_20the_20other_20ones_13',['⚠️ Single-file versions in Ubuntu are known to have MPI-related issues. Please use the other ones.',['../md_docs_2changelog_2CHANGELOG.html#autotoc_md91',1,'']]],
  ['pluriannual_20vision_14',[' Switching to a pluriannual vision',['../md_docs_2user-guide_2trajectory-investment_2trajectory-problem.html#autotoc_md338',1,'']]],
  ['positivefloatvalueerror_15',['PositiveFloatValueError',['../classantares__xpansion_1_1input__checker_1_1PositiveFloatValueError.html',1,'antares_xpansion::input_checker']]],
  ['pre_20build_20dependency_16',['Using pre-build dependency',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md155',1,'']]],
  ['predicate_17',['Predicate',['../structPredicate.html',1,'']]],
  ['prepare_20the_20antares_20study_18',['Prepare the Antares study',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md258',1,'']]],
  ['prepare_5fdrivers_19',['prepare_drivers',['../classantares__xpansion_1_1full__run__driver_1_1FullRunDriver.html#aa41da6a9b74f253aed32501ce17b1fda',1,'antares_xpansion::full_run_driver::FullRunDriver']]],
  ['prepare_5ffolder_20',['prepare_folder',['../classdriver__trajectory_1_1TrajectoryInvestmentDriver.html#a247f5bf7e70d90b0e0b465e2eb0ce74d',1,'driver_trajectory::TrajectoryInvestmentDriver']]],
  ['prepare_5fresolution_5foptions_5ffile_21',['prepare_resolution_options_file',['../classdriver__resolution_1_1TrajectoryResolutionDriver.html#a1b25c911352ddd15806ffaf5b800cf92',1,'driver_resolution::TrajectoryResolutionDriver']]],
  ['presolve_22',['Presolve',['../classPresolve.html',1,'']]],
  ['presolve_23',['Calling the presolve',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html#autotoc_md297',1,'']]],
  ['presolve_20resume_20tt_24',['&lt;tt&gt;--step {full, antares, problem_generation, benders, gems, study_update, sensitivity, presolve, resume}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md238',1,'']]],
  ['presolve_20tt_25',['&lt;tt&gt;--presolve&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md246',1,'']]],
  ['presolve_5fonly_26',['presolve_only',['../classProblem.html#afc5b4b38128ca8910c2337a78532d0fe',1,'Problem::presolve_only()'],['../classSolverAbstract.html#aba0acac777ba9772c45192f7c592129a',1,'SolverAbstract::presolve_only()'],['../classSolverXpress.html#a3d625d9a37fc658c0484cfce08a15a1a',1,'SolverXpress::presolve_only()'],['../classSolverCbc.html#a15eaa73751b90280e58d70c31adb1f01',1,'SolverCbc::presolve_only()'],['../classSolverClp.html#aab589e50b2dcc4b32fdc08d6f10bec0f',1,'SolverClp::presolve_only()'],['../classNOOPSolver.html#a8e5a2b8c83cc87fe0a9d7328ee4ded70',1,'NOOPSolver::presolve_only()']]],
  ['presolvedata_27',['PresolveData',['../classantares__xpansion_1_1presolve__driver_1_1PresolveData.html',1,'antares_xpansion::presolve_driver']]],
  ['presolvedriver_28',['PresolveDriver',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver.html',1,'antares_xpansion::presolve_driver']]],
  ['presolveexecutionerror_29',['PresolveExecutionError',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver_1_1PresolveExecutionError.html',1,'antares_xpansion::presolve_driver::PresolveDriver']]],
  ['presolveinputpatherror_30',['PresolveInputPathError',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver_1_1PresolveInputPathError.html',1,'antares_xpansion::presolve_driver::PresolveDriver']]],
  ['presolveoptions_31',['PresolveOptions',['../structPresolveOptions.html',1,'']]],
  ['presolveoptionsfileerror_32',['PresolveOptionsFileError',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver_1_1PresolveOptionsFileError.html',1,'antares_xpansion::presolve_driver::PresolveDriver']]],
  ['print_33',['print',['../classSimulationOptions.html#a9f76fa0b9615eac54d0e6394bbe50df8',1,'SimulationOptions::print()'],['../classuser__input__translation_1_1UserInputTranslator.html#aa056f616551e30b61e8d8c9accd287d4',1,'user_input_translation.UserInputTranslator.print()']]],
  ['problem_34',['Problem',['../classProblem.html',1,'']]],
  ['problem_35',['problem',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md199',1,'4- Creation of master problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md309',1,'Benders reformulation of the investment problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md306',1,'Constraints (for the investment problem)'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md307',1,'Investment problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html',1,'Mathematical aspects of the investment problem'],['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md269',1,'Mathematical formulation of the sensitivity analysis problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md312',1,'Reliability-constrained investment problem'],['../md_docs_2user-guide_2trajectory-investment_2trajectory-problem.html',1,'Trajectory investment problem']]],
  ['problem_20format_20mps_20optimized_20tt_36',['&lt;tt&gt;--problem-format {MPS, OPTIMIZED}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md242',1,'']]],
  ['problem_20formulation_37',['Problem formulation',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md299',1,'']]],
  ['problem_20generation_38',['problem generation',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html',1,'Investment problem generation'],['../md_docs_2user-guide_2trajectory-investment_2multiple-problem-generation.html',1,'Multiple problem generation']]],
  ['problem_20generation_3a_20tt_20problem_5fgeneration_20tt_39',['2- Investment problem generation: &lt;tt&gt;problem_generation&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md177',1,'']]],
  ['problem_20in_20antares_20xpansion_40',['The optimal investment problem in Antares-Xpansion',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html',1,'']]],
  ['problem_20retrieval_41',['Antares optimization problem retrieval',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html',1,'']]],
  ['problem_5fgeneration_20benders_20gems_20study_5fupdate_20sensitivity_20presolve_20resume_20tt_42',['&lt;tt&gt;--step {full, antares, problem_generation, benders, gems, study_update, sensitivity, presolve, resume}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md238',1,'']]],
  ['problem_5fgeneration_20tt_43',['2- Investment problem generation: &lt;tt&gt;problem_generation&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md177',1,'']]],
  ['problemconstructiontest_44',['ProblemConstructionTest',['../classProblemConstructionTest.html',1,'']]],
  ['problemdata_45',['ProblemData',['../structOutput_1_1ProblemData.html',1,'Output::ProblemData'],['../structProblemData.html',1,'ProblemData']]],
  ['problemgeneration_46',['ProblemGeneration',['../classProblemGeneration.html',1,'']]],
  ['problemgenerationexeoptions_47',['ProblemGenerationExeOptions',['../classProblemGenerationExeOptions.html',1,'']]],
  ['problemgenerationexeoptionstest_48',['ProblemGenerationExeOptionsTest',['../classProblemGenerationExeOptionsTest.html',1,'']]],
  ['problemgenerationfilelogger_49',['ProblemGenerationFileLogger',['../classProblemGenerationLog_1_1ProblemGenerationFileLogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationilogger_50',['ProblemGenerationILogger',['../classProblemGenerationLog_1_1ProblemGenerationILogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationlogger_51',['ProblemGenerationLogger',['../classProblemGenerationLog_1_1ProblemGenerationLogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationloggertest_52',['ProblemGenerationLoggerTest',['../classProblemGenerationLoggerTest.html',1,'']]],
  ['problemgenerationoptions_53',['ProblemGenerationOptions',['../classProblemGenerationOptions.html',1,'']]],
  ['problemgenerationostreamlogger_54',['ProblemGenerationOstreamLogger',['../classProblemGenerationLog_1_1ProblemGenerationOstreamLogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationspyandmock_55',['ProblemGenerationSpyAndMock',['../classProblemGenerationSpyAndMock.html',1,'']]],
  ['problemgeneratordata_56',['ProblemGeneratorData',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorData.html',1,'antares_xpansion::problem_generator_driver']]],
  ['problemgeneratordriver_57',['ProblemGeneratorDriver',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorDriver.html',1,'antares_xpansion::problem_generator_driver']]],
  ['problemmodifier_58',['ProblemModifier',['../classProblemModifier.html',1,'']]],
  ['problemmodifiercapex_59',['ProblemModifierCapex',['../classProblemModifierCapex.html',1,'']]],
  ['problemmodifierprojection_60',['ProblemModifierProjection',['../classProblemModifierProjection.html',1,'']]],
  ['problemmodifiertest_61',['ProblemModifierTest',['../classProblemModifierTest.html',1,'']]],
  ['problemmodifiertestmultichronicle_62',['ProblemModifierTestMultiChronicle',['../classProblemModifierTestMultiChronicle.html',1,'']]],
  ['problemmodifiertestwithprofile_63',['ProblemModifierTestWithProfile',['../classProblemModifierTestWithProfile.html',1,'']]],
  ['problemnamecase_64',['ProblemNameCase',['../structProblemNameCase.html',1,'']]],
  ['problems_65',['problems',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md187',1,'&lt;tt&gt;.mps&lt;/tt&gt; files for the weekly optimization problems'],['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md196',1,'Initial weekly problems']]],
  ['problems_20em_66',['Modifications for &lt;em&gt;satellite problems&lt;/em&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md197',1,'']]],
  ['problems_20of_20annual_20xpansion_20studies_67',['Merging the master problems of annual Xpansion studies',['../md_docs_2user-guide_2trajectory-investment_2merge-master.html',1,'']]],
  ['problems_20retrieval_3a_20tt_20antares_20tt_68',['1- Antares-Simulator optimization problems retrieval: &lt;tt&gt;antares&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md176',1,'']]],
  ['problems_20with_20tt_20lp_5fnamer_20tt_69',['Modification of weekly problems with &lt;tt&gt;lp_namer&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md193',1,'']]],
  ['problemvariables_70',['ProblemVariables',['../structProblemVariables.html',1,'']]],
  ['problemvariablesfileadapter_71',['ProblemVariablesFileAdapter',['../classProblemVariablesFileAdapter.html',1,'']]],
  ['problemvariablesfromproblemadapter_72',['ProblemVariablesFromProblemAdapter',['../classProblemVariablesFromProblemAdapter.html',1,'']]],
  ['problemvariableszipadapter_73',['ProblemVariablesZipAdapter',['../classProblemVariablesZipAdapter.html',1,'']]],
  ['procedure_74',['Antares-Xpansion simulation procedure',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html',1,'']]],
  ['profile_20tt_75',['profile tt',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md222',1,'&lt;tt&gt;[in]direct-link-profile&lt;/tt&gt;'],['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md223',1,'&lt;tt&gt;already-installed-[in]direct-link-profile&lt;/tt&gt;']]],
  ['profilefilenegativevalue_76',['ProfileFileNegativeValue',['../classantares__xpansion_1_1input__checker_1_1ProfileFileNegativeValue.html',1,'antares_xpansion.input_checker.ProfileFileNegativeValue'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileNegativeValue.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileNegativeValue']]],
  ['profilefilenotexists_77',['ProfileFileNotExists',['../classantares__xpansion_1_1input__checker_1_1ProfileFileNotExists.html',1,'antares_xpansion::input_checker']]],
  ['profilefilevalueerror_78',['ProfileFileValueError',['../classantares__xpansion_1_1input__checker_1_1ProfileFileValueError.html',1,'antares_xpansion.input_checker.ProfileFileValueError'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileValueError.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileValueError']]],
  ['profilefilewrongnumberofcolumns_79',['ProfileFileWrongNumberOfcolumns',['../classantares__xpansion_1_1input__checker_1_1ProfileFileWrongNumberOfcolumns.html',1,'antares_xpansion.input_checker.ProfileFileWrongNumberOfcolumns'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileWrongNumberOfcolumns.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileWrongNumberOfcolumns']]],
  ['profilefilewrongnumberoflines_80',['ProfileFileWrongNumberOfLines',['../classantares__xpansion_1_1input__checker_1_1ProfileFileWrongNumberOfLines.html',1,'antares_xpansion.input_checker.ProfileFileWrongNumberOfLines'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileWrongNumberOfLines.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileWrongNumberOfLines']]],
  ['profilelinkchecker_81',['ProfileLinkChecker',['../classantares__xpansion_1_1profile__link__checker_1_1ProfileLinkChecker.html',1,'antares_xpansion::profile_link_checker']]],
  ['profiles_20depending_20on_20the_20monte_20carlo_20year_82',['Using different profiles depending on the Monte-Carlo year',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md225',1,'']]],
  ['profilesofdifferentdimensions_83',['ProfilesOfDifferentDimensions',['../classantares__xpansion_1_1candidates__reader_1_1ProfilesOfDifferentDimensions.html',1,'antares_xpansion::candidates_reader']]],
  ['profilesvalueerror_84',['ProfilesValueError',['../classantares__xpansion_1_1candidates__reader_1_1ProfilesValueError.html',1,'antares_xpansion::candidates_reader']]],
  ['project_20structure_85',['Project Structure',['../md_docs_2agents_2cpp-conventions.html#autotoc_md17',1,'Project Structure'],['../md_docs_2agents_2python-conventions.html#autotoc_md31',1,'Project Structure']]],
  ['pshiftmax_5f_86',['pShiftMax_',['../structLinkdataRecord_1_1FileColumns.html#a8d83f0f99914a833dfb34896ab69be36',1,'LinkdataRecord::FileColumns']]],
  ['pshiftmin_5f_87',['pShiftMin_',['../structLinkdataRecord_1_1FileColumns.html#a087c9dfcfef544c84f61925adcc1a7d4',1,'LinkdataRecord::FileColumns']]],
  ['pytest_88',['Python Tests (pytest)',['../md_docs_2agents_2testing.html#autotoc_md54',1,'']]],
  ['python_89',['Unit Tests Only (C++ and Python)',['../md_docs_2agents_2testing.html#autotoc_md41',1,'']]],
  ['python_20conventions_90',['Python Conventions',['../md_docs_2agents_2python-conventions.html',1,'']]],
  ['python_20orchestrator_20tt_20get_5fnames_20tt_91',['Python orchestrator &lt;tt&gt;get_names&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md192',1,'']]],
  ['python_20tests_20pytest_92',['Python Tests (pytest)',['../md_docs_2agents_2testing.html#autotoc_md54',1,'']]],
  ['python_20unit_20tests_20only_93',['Python Unit Tests Only',['../md_docs_2agents_2testing.html#autotoc_md43',1,'']]],
  ['python_20version_94',['@ref &quot;python-version&quot; &quot;Python version&quot;',['../md_docs_2developer-guide_2install__from__sources_21-Development-requirements.html#autotoc_md147',1,'']]],
  ['python_20version_20python_20version_95',['@ref &quot;python-version&quot; &quot;Python version&quot;',['../md_docs_2developer-guide_2install__from__sources_21-Development-requirements.html#autotoc_md147',1,'']]]
];
