var searchData=
[
  ['package_20executables_0',['Antares-Xpansion package executables',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md128',1,'']]],
  ['package_20manager_1',['Install with a VCPKG package manager',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md97',1,'']]],
  ['parameters_2',['parameters',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md181',1,'Command line parameters'],['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md159',1,'Details of the parameters'],['../md_docs_2user-guide_2get-started_2settings-definition.html#autotoc_md222',1,'Details of the parameters']]],
  ['parse_5ftrajectory_5fuser_5ffile_3',['parse_trajectory_user_file',['../classuser__input__translation_1_1UserInputTranslator.html#ad5813f046fe5f99444c42a695c7a3c42',1,'user_input_translation::UserInputTranslator']]],
  ['parser_20translator_4',['Input file parser &amp; translator',['../md_docs_2user-guide_2trajectory-investment_2user-input.html#autotoc_md290',1,'']]],
  ['parsing_5',['User input file parsing',['../md_docs_2user-guide_2trajectory-investment_2user-input.html',1,'']]],
  ['paths_20archives_20file_6',['Study paths / archives file',['../md_docs_2user-guide_2trajectory-investment_2multiple-problem-generation.html#autotoc_md271',1,'']]],
  ['pdf_20generation_7',['PDF generation',['../md_docs_2how__to.html#autotoc_md148',1,'']]],
  ['per_20mw_20tt_8',['&lt;tt&gt;annual-cost-per-mw&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md162',1,'']]],
  ['perfplotsgenerator_9',['PerfPlotsGenerator',['../classperformance_1_1PerfPlotsGenerator.html',1,'performance']]],
  ['platforms_10',['Handling Different Platforms',['../md_docs_2developer-guide_2install__from__sources_26-Xpress.html#autotoc_md122',1,'']]],
  ['please_20use_20the_20other_20ones_11',['⚠️ Single-file versions in Ubuntu are known to have MPI-related issues. Please use the other ones.',['../md_docs_2changelog_2CHANGELOG.html#autotoc_md38',1,'']]],
  ['pluriannual_20vision_12',[' Switching to a pluriannual vision',['../md_docs_2user-guide_2trajectory-investment_2trajectory-problem.html#autotoc_md283',1,'']]],
  ['positivefloatvalueerror_13',['PositiveFloatValueError',['../classantares__xpansion_1_1input__checker_1_1PositiveFloatValueError.html',1,'antares_xpansion::input_checker']]],
  ['pre_20build_20dependency_14',['Using pre-build dependency',['../md_docs_2developer-guide_2install__from__sources_22-Dependencies-install.html#autotoc_md102',1,'']]],
  ['predicate_15',['Predicate',['../structPredicate.html',1,'']]],
  ['prepare_20the_20antares_20study_16',['Prepare the Antares study',['../md_docs_2user-guide_2get-started_2prepare-a-simulation.html#autotoc_md203',1,'']]],
  ['prepare_5fdrivers_17',['prepare_drivers',['../classantares__xpansion_1_1full__run__driver_1_1FullRunDriver.html#aa41da6a9b74f253aed32501ce17b1fda',1,'antares_xpansion::full_run_driver::FullRunDriver']]],
  ['prepare_5ffolder_18',['prepare_folder',['../classdriver__trajectory_1_1TrajectoryInvestmentDriver.html#a247f5bf7e70d90b0e0b465e2eb0ce74d',1,'driver_trajectory::TrajectoryInvestmentDriver']]],
  ['prepare_5fresolution_5foptions_5ffile_19',['prepare_resolution_options_file',['../classdriver__resolution_1_1TrajectoryResolutionDriver.html#a1b25c911352ddd15806ffaf5b800cf92',1,'driver_resolution::TrajectoryResolutionDriver']]],
  ['presolve_20',['Presolve',['../classPresolve.html',1,'']]],
  ['presolve_21',['Calling the presolve',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html#autotoc_md242',1,'']]],
  ['presolve_20resume_20tt_22',['&lt;tt&gt;--step {full, antares, problem_generation, benders, study_update, sensitivity, presolve, resume}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md183',1,'']]],
  ['presolve_20tt_23',['&lt;tt&gt;--presolve&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md191',1,'']]],
  ['presolve_5fonly_24',['presolve_only',['../classProblem.html#afc5b4b38128ca8910c2337a78532d0fe',1,'Problem::presolve_only()'],['../classSolverAbstract.html#aba0acac777ba9772c45192f7c592129a',1,'SolverAbstract::presolve_only()'],['../classSolverXpress.html#a3d625d9a37fc658c0484cfce08a15a1a',1,'SolverXpress::presolve_only()'],['../classSolverCbc.html#a15eaa73751b90280e58d70c31adb1f01',1,'SolverCbc::presolve_only()'],['../classSolverClp.html#aab589e50b2dcc4b32fdc08d6f10bec0f',1,'SolverClp::presolve_only()'],['../classNOOPSolver.html#a8e5a2b8c83cc87fe0a9d7328ee4ded70',1,'NOOPSolver::presolve_only()']]],
  ['presolvedata_25',['PresolveData',['../classantares__xpansion_1_1presolve__driver_1_1PresolveData.html',1,'antares_xpansion::presolve_driver']]],
  ['presolvedriver_26',['PresolveDriver',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver.html',1,'antares_xpansion::presolve_driver']]],
  ['presolveexecutionerror_27',['PresolveExecutionError',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver_1_1PresolveExecutionError.html',1,'antares_xpansion::presolve_driver::PresolveDriver']]],
  ['presolveinputpatherror_28',['PresolveInputPathError',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver_1_1PresolveInputPathError.html',1,'antares_xpansion::presolve_driver::PresolveDriver']]],
  ['presolveoptions_29',['PresolveOptions',['../structPresolveOptions.html',1,'']]],
  ['presolveoptionsfileerror_30',['PresolveOptionsFileError',['../classantares__xpansion_1_1presolve__driver_1_1PresolveDriver_1_1PresolveOptionsFileError.html',1,'antares_xpansion::presolve_driver::PresolveDriver']]],
  ['print_31',['print',['../classSimulationOptions.html#a9f76fa0b9615eac54d0e6394bbe50df8',1,'SimulationOptions::print()'],['../classuser__input__translation_1_1UserInputTranslator.html#aa056f616551e30b61e8d8c9accd287d4',1,'user_input_translation.UserInputTranslator.print()']]],
  ['problem_32',['Problem',['../classProblem.html',1,'']]],
  ['problem_33',['problem',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md144',1,'4- Creation of master problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md254',1,'Benders reformulation of the investment problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md251',1,'Constraints (for the investment problem)'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md252',1,'Investment problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html',1,'Mathematical aspects of the investment problem'],['../md_docs_2user-guide_2get-started_2sensitivity-analysis.html#autotoc_md214',1,'Mathematical formulation of the sensitivity analysis problem'],['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md257',1,'Reliability-constrained investment problem'],['../md_docs_2user-guide_2trajectory-investment_2trajectory-problem.html',1,'Trajectory investment problem']]],
  ['problem_20format_20mps_20optimized_20tt_34',['&lt;tt&gt;--problem-format {MPS, OPTIMIZED}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md187',1,'']]],
  ['problem_20formulation_35',['Problem formulation',['../md_docs_2user-guide_2optimization-principles_2problem-formalization.html#autotoc_md244',1,'']]],
  ['problem_20generation_36',['problem generation',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html',1,'Investment problem generation'],['../md_docs_2user-guide_2trajectory-investment_2multiple-problem-generation.html',1,'Multiple problem generation']]],
  ['problem_20generation_3a_20tt_20problem_5fgeneration_20tt_37',['2- Investment problem generation: &lt;tt&gt;problem_generation&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md125',1,'']]],
  ['problem_20in_20antares_20xpansion_38',['The optimal investment problem in Antares-Xpansion',['../md_docs_2user-guide_2optimization-principles_2investment-problem.html',1,'']]],
  ['problem_20retrieval_39',['Antares optimization problem retrieval',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html',1,'']]],
  ['problem_5fgeneration_20benders_20study_5fupdate_20sensitivity_20presolve_20resume_20tt_40',['&lt;tt&gt;--step {full, antares, problem_generation, benders, study_update, sensitivity, presolve, resume}&lt;/tt&gt;',['../md_docs_2user-guide_2get-started_2launching-optimization.html#autotoc_md183',1,'']]],
  ['problem_5fgeneration_20tt_41',['2- Investment problem generation: &lt;tt&gt;problem_generation&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md125',1,'']]],
  ['problemconstructiontest_42',['ProblemConstructionTest',['../classProblemConstructionTest.html',1,'']]],
  ['problemdata_43',['ProblemData',['../structOutput_1_1ProblemData.html',1,'Output::ProblemData'],['../structProblemData.html',1,'ProblemData']]],
  ['problemgeneration_44',['ProblemGeneration',['../classProblemGeneration.html',1,'']]],
  ['problemgenerationexeoptions_45',['ProblemGenerationExeOptions',['../classProblemGenerationExeOptions.html',1,'']]],
  ['problemgenerationexeoptionstest_46',['ProblemGenerationExeOptionsTest',['../classProblemGenerationExeOptionsTest.html',1,'']]],
  ['problemgenerationfilelogger_47',['ProblemGenerationFileLogger',['../classProblemGenerationLog_1_1ProblemGenerationFileLogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationilogger_48',['ProblemGenerationILogger',['../classProblemGenerationLog_1_1ProblemGenerationILogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationlogger_49',['ProblemGenerationLogger',['../classProblemGenerationLog_1_1ProblemGenerationLogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationloggertest_50',['ProblemGenerationLoggerTest',['../classProblemGenerationLoggerTest.html',1,'']]],
  ['problemgenerationoptions_51',['ProblemGenerationOptions',['../classProblemGenerationOptions.html',1,'']]],
  ['problemgenerationostreamlogger_52',['ProblemGenerationOstreamLogger',['../classProblemGenerationLog_1_1ProblemGenerationOstreamLogger.html',1,'ProblemGenerationLog']]],
  ['problemgenerationspyandmock_53',['ProblemGenerationSpyAndMock',['../classProblemGenerationSpyAndMock.html',1,'']]],
  ['problemgeneratordata_54',['ProblemGeneratorData',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorData.html',1,'antares_xpansion::problem_generator_driver']]],
  ['problemgeneratordriver_55',['ProblemGeneratorDriver',['../classantares__xpansion_1_1problem__generator__driver_1_1ProblemGeneratorDriver.html',1,'antares_xpansion::problem_generator_driver']]],
  ['problemmodifier_56',['ProblemModifier',['../classProblemModifier.html',1,'']]],
  ['problemmodifiercapex_57',['ProblemModifierCapex',['../classProblemModifierCapex.html',1,'']]],
  ['problemmodifierprojection_58',['ProblemModifierProjection',['../classProblemModifierProjection.html',1,'']]],
  ['problemmodifiertest_59',['ProblemModifierTest',['../classProblemModifierTest.html',1,'']]],
  ['problemmodifiertestmultichronicle_60',['ProblemModifierTestMultiChronicle',['../classProblemModifierTestMultiChronicle.html',1,'']]],
  ['problemmodifiertestwithprofile_61',['ProblemModifierTestWithProfile',['../classProblemModifierTestWithProfile.html',1,'']]],
  ['problemnamecase_62',['ProblemNameCase',['../structProblemNameCase.html',1,'']]],
  ['problems_63',['problems',['../md_docs_2developer-guide_2xpansion__steps_21-antares-solver-problem.html#autotoc_md132',1,'&lt;tt&gt;.mps&lt;/tt&gt; files for the weekly optimization problems'],['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md141',1,'Initial weekly problems']]],
  ['problems_20em_64',['Modifications for &lt;em&gt;satellite problems&lt;/em&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md142',1,'']]],
  ['problems_20of_20annual_20xpansion_20studies_65',['Merging the master problems of annual Xpansion studies',['../md_docs_2user-guide_2trajectory-investment_2merge-master.html',1,'']]],
  ['problems_20retrieval_3a_20tt_20antares_20tt_66',['1- Antares-Simulator optimization problems retrieval: &lt;tt&gt;antares&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html#autotoc_md124',1,'']]],
  ['problems_20with_20tt_20lp_5fnamer_20tt_67',['Modification of weekly problems with &lt;tt&gt;lp_namer&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md138',1,'']]],
  ['problemvariables_68',['ProblemVariables',['../structProblemVariables.html',1,'']]],
  ['problemvariablesfileadapter_69',['ProblemVariablesFileAdapter',['../classProblemVariablesFileAdapter.html',1,'']]],
  ['problemvariablesfromproblemadapter_70',['ProblemVariablesFromProblemAdapter',['../classProblemVariablesFromProblemAdapter.html',1,'']]],
  ['problemvariableszipadapter_71',['ProblemVariablesZipAdapter',['../classProblemVariablesZipAdapter.html',1,'']]],
  ['procedure_72',['Antares-Xpansion simulation procedure',['../md_docs_2developer-guide_2xpansion__steps_20-overview.html',1,'']]],
  ['profile_20tt_73',['profile tt',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md167',1,'&lt;tt&gt;[in]direct-link-profile&lt;/tt&gt;'],['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md168',1,'&lt;tt&gt;already-installed-[in]direct-link-profile&lt;/tt&gt;']]],
  ['profilefilenegativevalue_74',['ProfileFileNegativeValue',['../classantares__xpansion_1_1input__checker_1_1ProfileFileNegativeValue.html',1,'antares_xpansion.input_checker.ProfileFileNegativeValue'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileNegativeValue.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileNegativeValue']]],
  ['profilefilenotexists_75',['ProfileFileNotExists',['../classantares__xpansion_1_1input__checker_1_1ProfileFileNotExists.html',1,'antares_xpansion::input_checker']]],
  ['profilefilevalueerror_76',['ProfileFileValueError',['../classantares__xpansion_1_1input__checker_1_1ProfileFileValueError.html',1,'antares_xpansion.input_checker.ProfileFileValueError'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileValueError.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileValueError']]],
  ['profilefilewrongnumberofcolumns_77',['ProfileFileWrongNumberOfcolumns',['../classantares__xpansion_1_1input__checker_1_1ProfileFileWrongNumberOfcolumns.html',1,'antares_xpansion.input_checker.ProfileFileWrongNumberOfcolumns'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileWrongNumberOfcolumns.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileWrongNumberOfcolumns']]],
  ['profilefilewrongnumberoflines_78',['ProfileFileWrongNumberOfLines',['../classantares__xpansion_1_1input__checker_1_1ProfileFileWrongNumberOfLines.html',1,'antares_xpansion.input_checker.ProfileFileWrongNumberOfLines'],['../classantares__xpansion_1_1split__link__profile_1_1SplitLinkProfile_1_1ProfileFileWrongNumberOfLines.html',1,'antares_xpansion.split_link_profile.SplitLinkProfile.ProfileFileWrongNumberOfLines']]],
  ['profilelinkchecker_79',['ProfileLinkChecker',['../classantares__xpansion_1_1profile__link__checker_1_1ProfileLinkChecker.html',1,'antares_xpansion::profile_link_checker']]],
  ['profiles_20depending_20on_20the_20monte_20carlo_20year_80',['Using different profiles depending on the Monte-Carlo year',['../md_docs_2user-guide_2get-started_2candidate-definition.html#autotoc_md170',1,'']]],
  ['profilesofdifferentdimensions_81',['ProfilesOfDifferentDimensions',['../classantares__xpansion_1_1candidates__reader_1_1ProfilesOfDifferentDimensions.html',1,'antares_xpansion::candidates_reader']]],
  ['profilesvalueerror_82',['ProfilesValueError',['../classantares__xpansion_1_1candidates__reader_1_1ProfilesValueError.html',1,'antares_xpansion::candidates_reader']]],
  ['pshiftmax_5f_83',['pShiftMax_',['../structLinkdataRecord_1_1FileColumns.html#a8d83f0f99914a833dfb34896ab69be36',1,'LinkdataRecord::FileColumns']]],
  ['pshiftmin_5f_84',['pShiftMin_',['../structLinkdataRecord_1_1FileColumns.html#a087c9dfcfef544c84f61925adcc1a7d4',1,'LinkdataRecord::FileColumns']]],
  ['python_20orchestrator_20tt_20get_5fnames_20tt_85',['Python orchestrator &lt;tt&gt;get_names&lt;/tt&gt;',['../md_docs_2developer-guide_2xpansion__steps_22-problem-modification.html#autotoc_md137',1,'']]],
  ['python_20version_86',['@ref &quot;python-version&quot; &quot;Python version&quot;',['../md_docs_2developer-guide_2install__from__sources_21-Development-requirements.html#autotoc_md94',1,'']]],
  ['python_20version_20python_20version_87',['@ref &quot;python-version&quot; &quot;Python version&quot;',['../md_docs_2developer-guide_2install__from__sources_21-Development-requirements.html#autotoc_md94',1,'']]]
];
