# ===========================================================================
# CMake configuration
# ===========================================================================

# ===========================================================================
# Targets
# ===========================================================================

# ---------------------------------------------------------------------------
# Presolve Exe
# ---------------------------------------------------------------------------

add_executable(presolve
        ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp
)
target_link_libraries(presolve
        PUBLIC
        ${PROJECT_NAME}::factories
        ${PROJECT_NAME}::presolvecore
)


install(TARGETS presolve DESTINATION bin)
