* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 0
*   Variables        : 1
*     Binary         : 0
*     Integer        : 0
*     Continuous     : 1
NAME          
ROWS
 N  COST
COLUMNS
    G_p_max_0_0  COST             20
RHS
BOUNDS
 UP BOUND        G_p_max_0_0      10
ENDATA
