@startuml
'https://plantuml.com/sequence-diagram
!include <C4/C4_Container>

Container(Xpansion, "Xpansion", "C++", "Perform investment simulations for Antares studies")
System(systemAlias, "Antares", "Quantify the adequacy, or the economic performance of interconnected energy systems")

Person(Alice, "Alice", "Chargée d'étude")
Rel(Alice, Xpansion, "Configure study for")

Person(Bob, "Bob", "Thésard")
Rel(Bob, Xpansion, "Try new things")

Container(Simulator, "Antares simulator", "C++", "Quantify the adequacy, or the economic performance of interconnected energy systems")
Container(Web, "Antares Web", "React/Python", "Manage studies")

Rel(Xpansion, Simulator, "Perform iteration of")
Rel(Web, Xpansion, "Run")
Rel(Alice, Web, "Use to run and configure studies")

@enduml