name: "Download and build gtest"
description: "build gtest for centos7"
runs:
  using: "composite"
  steps:
    - id: build-gtest
      shell: bash
      run: |
        source /opt/rh/devtoolset-10/enable || source /opt/rh/devtoolset-10/enable || true
        git clone -b v1.14.0 https://github.com/google/googletest.git
        cd googletest
        cmake3 -G"Unix Makefiles"
        make -j8
        make install