#ifndef ANTARES_XPANSION_SRC_CPP_BENDERS_BENDERS_MPI_BENDERSMPIMAIN_H
#define ANTARES_XPANSION_SRC_CPP_BENDERS_BENDERS_MPI_BENDERSMPIMAIN_H

#define BENDERSMPIMAIN

int BendersMpiMain(int argc, char **argv);

#endif  // ANTARES_XPANSION_SRC_CPP_BENDERS_BENDERS_MPI_BENDERSMPIMAIN_H
