#ifndef ANTARES_XPANSION_SRC_CPP_MULTISOLVER_INTERFACE_OTHERSOLVER_H
#define ANTARES_XPANSION_SRC_CPP_MULTISOLVER_INTERFACE_OTHERSOLVER_H

#include "SolverAbc.h"
using OtherSolverType = SolverAbc;
std::string GetOtherSolverName() { return SolverAbc::NAME_; }
#endif  // ANTARES_XPANSION_SRC_CPP_MULTISOLVER_INTERFACE_OTHERSOLVER_H
