name: "Create single file .zip archive"
description: "Create single file .zip archive (Windows only)"
inputs:
  antares-xpansion-version:
    description: 'antares-xpansion version'
    required: true

outputs:
  archive-path:
    description: "Created archive path"
    value: ${{ steps.create.outputs.archive-path }}
  archive-name:
    description: "Created archive name"
    value: ${{ steps.create.outputs.archive-name }}
runs:
  using: "composite"
  steps:
    - id: create
      shell: bash
      run: |
        cd _install
        rm -f ./antares-xpansion-launcher*
        pyinstaller -F ../src/python/launch.py -n antares-xpansion-launcher \
        --add-data "../src/python/config.yaml;." \
        --add-data "./bin/;bin" \
        --exclude-module _bootlocale
        mv ./dist/antares-xpansion-launcher* .
        rm -rf bin build dist
        rm *.spec

    - id: archive-windows
      shell: pwsh
      run: |
        $ARCHIVE_NAME = "antaresXpansion-${{ inputs.antares-xpansion-version }}-windows-single-file.zip"
        $ARCHIVE_PATH = Join-Path $env:GITHUB_WORKSPACE "_install\$ARCHIVE_NAME"
        Set-Location "$env:GITHUB_WORKSPACE/_install"
        Compress-Archive -Path * -DestinationPath $ARCHIVE_PATH
        # Write outputs
        Write-Output "archive-path=_install/$ARCHIVE_NAME" >> $Env:GITHUB_OUTPUT
        Write-Output "archive-name=$ARCHIVE_NAME" >> $Env:GITHUB_OUTPUT
