name: "Generate User Guide pdf"
description: "Generate User Guide pdf using Sphinx (not supported on windows)"
inputs:
  antares-xpansion-version:
    description: 'antares-xpansion version'
    required: true
outputs:
  pdf-path:
    description: "path of the user guide pdf"
    value: ${{ steps.create.outputs.pdf-path }}
  pdf-name:
    description: "name of the user guide pdf"
    value: ${{ steps.create.outputs.pdf-name }}
runs:
  using: "composite"
  steps:
    - id: create
      shell: bash
      run: |
        PDF_NAME=antaresXpansion-UserGuide-${{ inputs.antares-xpansion-version }}.pdf
        cd docs/pdf-doc-generation-with-sphinx
        bash create_pdf_doc.sh $PDF_NAME
        mv antaresxpansionuserguide.pdf $PDF_NAME
        PDF_PATH=docs/pdf-doc-generation-with-sphinx/$PDF_NAME
        echo "::set-output name=pdf-path::$PDF_PATH"
        echo "::set-output name=pdf-name::$PDF_NAME"
