name: "Generate User Guide pdf"
description: "Generate User Guide pdf using Sphinx (not supported on windows)"
inputs:
  antares-xpansion-version:
    description: 'antares-xpansion version'
    required: true
outputs:
  pdf-path:
    description: "path of the user guide pdf"
    value: ${{ steps.create.outputs.pdf-path }}
  pdf-name:
    description: "name of the user guide pdf"
    value: ${{ steps.create.outputs.pdf-name }}
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements-tests.txt
        pip3 install -r requirements-doc.txt

    - name: Install libraries
      shell: bash
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install latexmk texlive-latex-recommended texlive-formats-extra

    - id: create
      shell: bash
      run: |
        PDF_NAME=antaresXpansion-UserGuide-${{ inputs.antares-xpansion-version }}.pdf
        cd docs/pdf-doc-generation-with-sphinx
        bash create_pdf_doc.sh $PDF_NAME
        mv antaresxpansionuserguide.pdf $PDF_NAME
        PDF_PATH=docs/pdf-doc-generation-with-sphinx/$PDF_NAME
        echo "::set-output name=pdf-path::$PDF_PATH"
        echo "::set-output name=pdf-name::$PDF_NAME"
