name: "Download extract .zip precompiled libraries"
description: "Download and extract .zip precompiled libraries from antares-deps and antares-simulator repository"
inputs:
  antares-version:
    description: 'antares-solver version'
    required: true
  os:
    description: 'operational system used for github action'
    required: true
  buildtype:
    description: 'build type'
    required: false
    default: 'Release'
  variant:
    description: 'extra qualifiers'
    required: false
    default: ""

runs:
  using: "composite"
  steps: 
  - id: download-extract
    shell: bash
    run: |
           wget https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases/download/v${{inputs.antares-version}}/rte-antares-${{inputs.antares-version}}-installer-64bits.zip
           unzip rte-antares-${{inputs.antares-version}}-installer-64bits.zip
           rm -rf rte-antares-${{inputs.antares-version}}-installer-64bits.zip
