name: "Download extract .zip precompiled libraries"
description: "Download and extract .zip precompiled libraries from antares-deps and antares-simulator repository"
inputs:
  antares-deps-version:
    description: 'antares-deps version'
    required: true  
  antares-version:
    description: 'antares-solver version'
    required: true  
  os:
    description: 'operational system used for github action'
    required: true
runs:
  using: "composite"
  steps: 
  - id: download-extract
    shell: bash
    run: |
           wget https://github.com/AntaresSimulatorTeam/antares-deps/releases/download/v${{inputs.antares-deps-version}}/rte-antares-deps-${{inputs.os}}-Release-solver-no-ortools.zip
           unzip rte-antares-deps-${{inputs.os}}-Release-solver-no-ortools.zip
           rm -rf rte-antares-deps-${{inputs.os}}-Release-solver-no-ortools.zip
           
           wget https://github.com/AntaresSimulatorTeam/Antares_Simulator/releases/download/v${{inputs.antares-version}}/rte-antares-${{inputs.antares-version}}-installer-64bits.zip
           unzip rte-antares-${{inputs.antares-version}}-installer-64bits.zip
           rm -rf rte-antares-${{inputs.antares-version}}-installer-64bits.zip