name: "Read a json value"
description: "Read a json value"
inputs:
  path:
    description: "Path to json file"
    required: true
  key:
    description: "key to read the value"
    required: true
outputs:
  result:
    description: "Value attached to the key"
    value: ${{steps.export-value.outputs.result}}

runs:
  using: "composite"
  steps:
    - id: read-file
      shell: bash
      run: |
        echo "content<<EOF" >> "$GITHUB_OUTPUT"
        cat ${{inputs.path}} >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - id: export-value
      shell: bash
      run: |
        val=${{fromJson(steps.read-file.outputs.content)[inputs.key]}}
        echo "result=$val" >> "$GITHUB_OUTPUT"