name: Ubuntu CI (system libs)

on:
  push:
    branches:
      - main
      - develop
      - doc
jobs:

  build:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
          
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements-tests.txt
          pip3 install -r requirements-doc.txt

    - name: Install libraries
      run: |
           sudo apt-get update --fix-missing
           sudo apt-get install latexmk texlive-latex-recommended texlive-formats-extra

    - name: Read antares-xpansion version
      id: antares-xpansion-version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'antares-version.json'
        prop_path: 'antares_xpansion_version'
        
    - name: copy mkdocs and build sphinx latexpdf
      run: |
            cd pdf-doc-generation-with-sphinx
            cp ../docs/index.md source/intro.md
            cp -r ../docs/assets/ source/
            cp -r ../docs/user-guide source/
            make latexpdf


    - name: user guide upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-xpansion-user-guide
        path: pdf-doc-generation-with-sphinx/build/latex/antaresxpansionuserguide.pdf

