name: Centos7 CI (system libs)

on:
  push:
    branches:
      - main
      - develop
      - features/*
      - feature/*
      - fix/*
jobs:

  build:

    runs-on: ubuntu-latest
    container: 'centos:7'

    steps:
    
    - name: Set up Python
      run: |
           yum update -y
           yum install -y python3 python3-pip

    - name: Install libraries
      run: |
           yum install -y wget git epel-release redhat-lsb-core gcc gcc-c++ make centos-release-scl scl-utils
           yum install -y jsoncpp-devel gtest-devel openmpi-devel boost-openmpi-devel doxygen graphviz
           yum install -y openssl-devel curl-devel libuuid-devel
           yum install -y cmake3 devtoolset-7 environment-modules
                      
    
    - uses: nelonoel/branch-name@v1.0.1
    
    - name: Checkout
      run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git -b ${BRANCH_NAME} .
    
    - name: Download pre-compiled librairies
      run: |
           wget https://github.com/AntaresSimulatorTeam/antares-deps/releases/download/v1.1.0/rte-antares-deps-centos7-Release-solver.tar.gz
           tar -xvf rte-antares-deps-centos7-Release-solver.tar.gz
           rm -rf rte-antares-deps-centos7-Release-solver.tar.gz
    
    - name: Init submodule
      run: |
           git submodule update --init --recursive .
          
    - name: Install dependencies
      run: |
          pip3 install -r src/src_python/requirements.txt
          pip3 install -r src/tests/examples/requirements.txt

    - name: Configure
      run: |
           source /opt/rh/devtoolset-7/enable
           export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH
           export PATH=/usr/lib64/openmpi/bin:$PATH
           
           cmake3 -B _build -S . -DDEPS_INSTALL_DIR=rte-antares-deps-Release -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DUSE_SEQUENTIAL=true -DUSE_MPI=true

    - name: Build
      run: |
           source /opt/rh/devtoolset-7/enable
           export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH
           export PATH=/usr/lib64/openmpi/bin:$PATH
           cmake3 --build _build --config Release -j2
           
    - name: Running unit tests
      run: |
           source /opt/rh/devtoolset-7/enable
           export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH
           export PATH=/usr/lib64/openmpi/bin:$PATH
           cd _build
           ctest3 -C Release --output-on-failure -L "medium"
           
    - name: Installer .tar.gz creation
      run: |
           cd _build
           cpack3 -G TGZ
           
    - name: Installer upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-xpansion-installer-64bits
        path: _build/antaresXpansion-*.*.*-*.tar.gz

