name: Centos7 CI (docker image)

on:
  push:
    branches:
      - main
      - develop
      - features/*
      - feature/*
      - fix/*
      - release/*
  
jobs:

  docker_publish:
          
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: |
          docker/centos7
          
    - name: Read antares-solver version
      if: ${{steps.changed-files-specific.outputs.any_changed}} == 'true'
      id: antares-version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'antares-version.json'
        prop_path: 'antares_version'
        
    - name: Read antares-deps version
      if: ${{steps.changed-files-specific.outputs.any_changed}} == 'true'
      id: antares-deps-version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'antares-version.json'
        prop_path: 'antares_deps_version'
        
    - name: Docker file push
      if: ${{steps.changed-files-specific.outputs.any_changed}} == 'true'
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        ANTARES_DEPS_VERSION: ${{steps.antares-deps-version.outputs.prop}}
        ANTARES_SOLVER_VERSION: ${{steps.antares-version.outputs.prop}}
      with:
        name: antaresrte/rte-antares
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: docker
        dockerfile: centos7
        cache: true
        tags: centos7-xpansion
        buildargs: ANTARES_DEPS_VERSION, ANTARES_SOLVER_VERSION

  build:

    runs-on: ubuntu-latest
    needs: docker_publish
    container: 'antaresrte/rte-antares:centos7-xpansion'

    steps:
    
    - uses: nelonoel/branch-name@v1.0.1
    
    - name: Checkout
      run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git -b ${BRANCH_NAME} .
        
    - name: Read antares-xpansion version
      id: antares-xpansion-version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'antares-version.json'
        prop_path: 'antares_xpansion_version'
    
    - name: Init submodule
      run: |
           git submodule update --init --recursive antares-deps
          
    - name: Install dependencies
      run: |
          pip3 install -r requirements-tests.txt

    - name: Configure
      run: |
           source /opt/rh/devtoolset-7/enable
           export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH
           export PATH=/usr/lib64/openmpi/bin:$PATH
           cmake3 -B _build -S . -DDEPS_INSTALL_DIR=/rte-antares-deps-Release -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DUSE_SEQUENTIAL=true -DUSE_MPI=true  -DCMAKE_INSTALL_PREFIX=_install -DBUILD_not_system=OFF

    - name: Build
      run: |
           source /opt/rh/devtoolset-7/enable
           export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH
           export PATH=/usr/lib64/openmpi/bin:$PATH
           cmake3 --build _build --config Release -j2  --target install
           
    - name: Running unit tests
      run: |
           cd _build
           ctest3 -C Release --output-on-failure -L "unit|benders"
           
    - id: create-single-file
      name: Single file .tar.gz creation
      uses: ./.github/workflows/single-file-creation-tgz
      with:
        antares-xpansion-version: ${{steps.antares-xpansion-version.outputs.prop}}
      
    - name: Installer .rpm creation
      run: |
           cd _build
           cpack3 -G RPM
           
    - name: Installer .tar.gz creation
      run: |
           cd _build
           cpack3 -G TGZ

    - name: Installer archive upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-xpansion-centos7-archive
        path: _build/*.tar.gz
        
    - name: Installer rpm upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-xpansion-centos7-rpm
        path: _build/*.rpm

    - name: Single file upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-xpansion-centos-single-file
        path: ${{ steps.create-single-file.outputs.archive-path }}
