name: Centos7 CI (bare docker image)

on:
  push:
    branches:
      - main
      - develop
      - features/*
      - feature/*
      - fix/*
      - release/*
  release:
    types: [ created ]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:

  docker_publish:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.3
        with:
          files: |
            docker/centos7-bare

      - name: Docker file push
        id: docker_push
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: antaresrte/rte-antares
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker
          dockerfile: centos7-bare
          cache: false
          tags: centos7-xpansion-bare

  userguide:
    runs-on: ubuntu-latest
    outputs:
      pdf-name: ${{ steps.create-user-guide.outputs.pdf-name }}

    steps:
      - uses: actions/checkout@v2

      - name: Read antares-xpansion version
        id: antares-xpansion-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'antares-version.json'
          prop_path: 'antares_xpansion_version'

      - id: create-user-guide
        name: user guide pdf creation
        uses: ./.github/workflows/generate-userguide-pdf
        with:
          antares-xpansion-version: ${{steps.antares-xpansion-version.outputs.prop}}

      - name: user guide upload
        id: userguide_upload
        uses: actions/upload-artifact@v2
        with:
          name: user-guide
          path: ${{ steps.create-user-guide.outputs.pdf-path }}

  build:

    runs-on: ubuntu-latest
    needs: [docker_publish, userguide]
    container: 'antaresrte/rte-antares:centos7-xpansion-bare'
    strategy:
      matrix:
        xprs: [ ON, OFF ]
    env:
      XPRESSDIR: ${{ github.workspace }}/xpress
      XPRESS: ${{ github.workspace }}/xpress/bin
      XPRS_LIB_Path: ${{ github.workspace }}/xpress/lib

    steps:
      - uses: nelonoel/branch-name@v1.0.1

      - name: Get release
        if: github.event_name == 'release' && github.event.action == 'created'
        id: get_release
        uses: bruceadams/get-release@v1.2.3

      - name: Checkout
        run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git -b ${BRANCH_NAME} .
          git submodule update --init --recursive antares-deps

      - name: Checkout xpressmp linux
        run: |
          git clone https://${{ secrets.AS_TOKEN }}@github.com/rte-france/xpress-mp.git ${{ env.XPRESSDIR }}

      - name: Read antares-solver version
        id: antares-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'antares-version.json'
          prop_path: 'antares_version'

      - name: Read antares-xpansion version
        id: antares-xpansion-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'antares-version.json'
          prop_path: 'antares_xpansion_version'

      - name: Read antares-deps version
        id: antares-deps-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'antares-version.json'
          prop_path: 'antares_deps_version'

      - name: Download pre-compiled librairies
        uses: ./.github/workflows/download-extract-precompiled-libraries-tgz
        with:
          antares-deps-version: ${{steps.antares-deps-version.outputs.prop}}
          antares-version: ${{steps.antares-version.outputs.prop}}
          os: centos7
          os-full-name: CentOS-7.9.2009

      - name: Install dependencies
        run: |
          pip3 install -r requirements-tests.txt
          pip3 install -r requirements-ui.txt

      - name: Download userguide
        uses: actions/download-artifact@v2
        with:
          name: user-guide
          path: docs/

      - name: Configure
        run: |
          source /opt/rh/devtoolset-7/enable
          export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH
          export PATH=/usr/lib64/openmpi/bin:$PATH
          cmake3 -B _build -S . \
                 -DDEPS_INSTALL_DIR=rte-antares-deps-Release \
                 -DBUILD_TESTING=ON \
                 -DCMAKE_BUILD_TYPE=Release \
                 -DUSE_MPI=ON \
                 -DCMAKE_INSTALL_PREFIX=_install \
                 -DBUILD_UI=ON \
                 -DUSER_GUIDE_PATH="docs/${{ needs.userguide.outputs.pdf-name }}" \
                 -DXPRESS=${{ matrix.xprs }} \
                 -DXPRESS_ROOT=${{ env.XPRESSDIR }} \
                 -DALLOW_RUN_AS_ROOT=ON

      - name: Build
        run: |
          source /opt/rh/devtoolset-7/enable
          export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH
          export PATH=/usr/lib64/openmpi/bin:$PATH
          cmake3 --build _build --config Release -j2 --target install

      - name: .tar.gz creation
        run: |
          cd _build
          cpack3 -G TGZ
          export TGZ_NAME=$(ls *.tar.gz)
          echo "TGZ_NAME=$TGZ_NAME" >> $GITHUB_ENV

      - name: Installer .rpm creation
        run: |
          cd _build
          cpack3 -G RPM
          export RPM_NAME=$(ls *.rpm)
          echo "RPM_NAME=$RPM_NAME" >> $GITHUB_ENV

      - name: set name variables
        id: single_file_name
        shell: bash
        run: |
          XPRS=${{ matrix.xprs }}
          [ $XPRS == "ON" ] && WITH_XPRS="-xpress" || WITH_XPRS=""
          VERSION=${{steps.antares-xpansion-version.outputs.prop}}${WITH_XPRS}
          echo "::set-output name=version::$VERSION"
          echo "VERSION_WITH_XPRESS=$VERSION"
          echo "VERSION_WITH_XPRESS=$VERSION" >> $GITHUB_ENV

      - id: create-single-file
        name: Single file .tar.gz creation
        uses: ./.github/workflows/single-file-creation-tgz
        with:
          antares-xpansion-version: ${{env.VERSION_WITH_XPRESS}}

      - name: Upload .tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.TGZ_NAME}}
          path: _build/${{env.TGZ_NAME}}

      - name: Upload rpm
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.RPM_NAME}}
          path: _build/${{env.RPM_NAME}}

      - name: Upload single file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.create-single-file.outputs.archive-name }}
          path: ${{ steps.create-single-file.outputs.archive-path }}

      - name: Running unit tests
        shell: bash
        run: |
          source /etc/profile.d/modules.sh
          module load mpi
          export LD_LIBRARY_PATH=LD_LIBRARY_PATH:${{ env.XPRS_LIB_Path }}
          export XPRESS=${{ env.XPRESS }}
          cd _build
          ctest3 -C Release --output-on-failure -L "unit|benders"

      - name: Publish .tar.gz
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: _build/${{env.TGZ_NAME}}
          asset_name: ${{env.TGZ_NAME}}
          asset_content_type: application/octet-stream

      - name: Publish .rpm
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: _build/${{env.RPM_NAME}}
          asset_name: ${{env.RPM_NAME}}
          asset_content_type: application/octet-stream

      - name: Publish single file
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.create-single-file.outputs.archive-path }}
          asset_name: ${{ steps.create-single-file.outputs.archive-name }}
          asset_content_type: application/octet-stream
