name: CI docker hub

on: 
  push:
    branches:
      - develop
      - features/*
      - feature/*
      - fix/*

jobs:
  linux:
  
    strategy:
      fail-fast: false
      matrix:
        container:
        - 'antaresrte/rte-antares:ubuntu-ortools'
  
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Init submodule
      run: |
           git submodule update --init --recursive .
           
    - name: Set up Python
      run: |
          apt-get install python3-pip -y
                    
    - name: Install dependencies
      run: |
          python3 -m pip install --upgrade pip
          pip3 install -r src/src_python/requirements.txt

    - name: Init submodule
      run: |
          git submodule update --init --recursive
    
    - name: Configure
      run: |
           cmake -B _build -S . -DCMAKE_BUILD_TYPE=Release -Dsirius_solver_ROOT=/sirius-install -DUSE_SEQUENTIAL=true -DUSE_MPI=true

    - name: Build
      run: |           
           cmake --build _build --config Release -j2
           
    - name: Installer .tar.gz creation
      run: |
           cd _build
           cpack -G TGZ
           
    - name: Installer upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-installer-64bits
        path: _build/antaresXpansion-*.*.*-*.tar.gz
