name: CI docker hub

on: 
  push:
    branches:
      - develop
      - features/*
      - feature/*

jobs:
  centos:
  
    runs-on: ubuntu-latest
    container: jmkerloch/rte-antares:centos8-ortools
    steps:
    - uses: actions/checkout@v2
    
    - name: Install libraries
      run: |
           sudo apt-get update --fix-missing
           sudo apt-get install libjsoncpp-dev libgtest-dev libboost-mpi-dev
           sudo apt-get install libuuid1 uuid-dev libssh2-1 libssh2-1-dev libidn2-dev libidn11 libidn11-dev gtk2.0 libwxgtk3.0-dev libcurl4-openssl-dev libb64-dev
           sudo apt-get install libboost-test-dev libboost-filesystem-dev libboost-dev
           cd /usr/src/googletest/
           sudo cmake .
           sudo cmake --build . --target install

    - name: Configure
      run: |
           mkdir _build
           cd _build
           cmake3  .. -DCMAKE_BUILD_TYPE=Release -DUSE_SEQUENTIAL=true -DUSE_MPI=true -DBUILD_antares_solver=OFF -DBUILD_ortools=OFF

    - name: Build
      run: |
           cmake3 --build _build --config release -j2
           
    - name: Installer .tar.gz creation
      run: |
           cd _build
           cpack -G TGZ
           
    - name: Installer upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-xpansion-installer-64bits
        path: _build/antaresXpansion-*.*.*-*.tar.gz
