name: CI docker hub

on: 
  push:
    branches:
      - develop
      - features/*
      - feature/*

jobs:
  centos:
  
    runs-on: ubuntu-latest
    container: jmkerloch/rte-antares:centos8-ortools
    steps:
    - uses: actions/checkout@v2
    
    - name: Install libraries
      run: |
           git clone https://github.com/google/googletest.git
           cd googletest
           cmake3 .
           cmake3 --build . --target install
           cd ..
           rm -rf googletest
           yum install jsoncpp-devel -y

    - name: Configure
      run: |
           mkdir _build
           cd _build
           cmake3  .. -DCMAKE_BUILD_TYPE=Release -DUSE_SEQUENTIAL=true -DUSE_MPI=false -DBUILD_antares_solver=OFF -DBUILD_ortools=OFF

    - name: Build
      run: |
           cmake3 --build _build --config release
           
    - name: Installer .tar.gz creation
      run: |
           cd _build
           cpack -G TGZ
           
    - name: Installer upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-xpansion-installer-64bits
        path: _build/antaresXpansion-*.*.*-*.tar.gz
