name: Docs Build Check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check external link validity
        uses: tcort/github-action-markdown-link-check@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v7
      
      - name: Install dependencies with uv
        run: uv sync --frozen

      # Fail notably if an internal link is incorrect
      - name: Build MkDocs
        run: uv run mkdocs build --strict