name: Linux CI (system libs)

on:
  push:
    branches:
      - develop
      - features/*
      - feature/*
      - fix/*
jobs:

  build:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install libraries
      run: |
           sudo apt-get update --fix-missing
           sudo apt-get install libjsoncpp-dev libgtest-dev libboost-mpi-dev
           sudo apt-get install libuuid1 uuid-dev libssh2-1 libssh2-1-dev libidn2-dev libidn11 libidn11-dev gtk2.0 libwxgtk3.0-dev libcurl4-openssl-dev libb64-dev
           sudo apt-get install libboost-test-dev libboost-filesystem-dev libboost-regex-dev libboost-dev
           cd /usr/src/googletest/
           sudo cmake .
           sudo cmake --build . --target install

    - name: Configure
      run: |
           cmake -B _build -S . -DCMAKE_BUILD_TYPE=Release -DUSE_SEQUENTIAL=true -DUSE_MPI=true -DBUILD_DEPS=ON

    - name: Build
      run: |
           cmake --build _build --config Release -j2
           
    - name: Installer .tar.gz creation
      run: |
           cd _build
           cpack -G TGZ
           
    - name: Installer upload
      uses: actions/upload-artifact@v2
      with:
        name: antares-xpansion-installer-64bits
        path: _build/antaresXpansion-*.*.*-*.tar.gz

