name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          echo ${{ github.ref }}
      - if: ${{ contains(github.ref, '-rc')  }}
        run: |
          echo "ok"
      - if: ${{ contains(github.ref, '-rc') && true || false  }}
        run: |
          echo "ok"
      - if: ${{ ! contains(github.ref, '-rc')  }}
        run: |
          echo "no"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, '-rc')  }}