name: Release Userguide pdf

on:
  release:
    types: [created]

jobs:

  build:

    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
          
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements-tests.txt
          pip3 install -r requirements-doc.txt

    - name: Install libraries
      run: |
           sudo apt-get update --fix-missing
           sudo apt-get install latexmk texlive-latex-recommended texlive-formats-extra

    - name: Read antares-xpansion version
      id: antares-xpansion-version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'antares-version.json'
        prop_path: 'antares_xpansion_version'

    - id: create-user-guide
      name: user guide pdf creation
      uses: ./.github/workflows/generate-userguide-pdf
      with:
        antares-xpansion-version: ${{steps.antares-xpansion-version.outputs.prop}}

    - name: user guide upload
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ${{ steps.create-user-guide.outputs.pdf-path }}
        asset_name: ${{ steps.create-user-guide.outputs.pdf-name }}
        asset_content_type: application/pdf
