name: Release Userguide pdf

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3

    - name: Read antares-xpansion version
      id: antares-xpansion-version
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'antares-version.json'
        prop_path: 'antares_xpansion_version'

    - id: create-user-guide
      name: user guide pdf creation
      uses: ./.github/workflows/generate-userguide-pdf
      with:
        antares-xpansion-version: ${{steps.antares-xpansion-version.outputs.prop}}

    - name: user guide upload
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ${{ steps.create-user-guide.outputs.pdf-path }}
        asset_name: ${{ steps.create-user-guide.outputs.pdf-name }}
        asset_content_type: application/pdf
