name: test ubuntu archive

on:
  merge_group:
  push:
  pull_request:
  release:
    types: [ created ]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:


  ubuntu-20-04:
    runs-on: ubuntu-latest
    container: 'ubuntu:20.04'
    strategy:
      matrix:
        xprs: [
          # { value: XPRESS-ON, ref: 8.13a },
          { value: XPRESS-ON, ref: 9.2.5 },
          #{ value: XPRESS-OFF }
        ]
    env:
      XPRESSDIR: ${{ github.workspace }}/xpress
      XPRESS: ${{ github.workspace }}/xpress/bin
      XPRS_LIB_Path: ${{ github.workspace }}/xpress/lib
      XPRESSDIR_CONTAINER: ${GITHUB_WORKSPACE}/xpress
      XPRESS_CONTAINER: ${GITHUB_WORKSPACE}/xpress/bin
      XPRS_LIB_Path_CONTAINER: ${GITHUB_WORKSPACE}/xpress/lib
      DEBIAN_FRONTEND: noninteractive



    steps:
      - run: |
          apt-get -y update 
          apt-get -y install libjsoncpp-dev wget libopenmpi3
          wget https://github.com/AntaresSimulatorTeam/antares-xpansion/releases/download/v1.3.0/antaresXpansion-1.3.0-xpress-ubuntu-20.04.tar.gz
          mkdir test
          tar xvfz antaresXpansion-1.3.0-xpress-ubuntu-20.04.tar.gz -C test
      - run: |    
          cd test
          ./antares-xpansion-launcher -i examples/SmallTestFiveCandidates
          echo "****************************"
          ./antares-xpansion-launcher -i examples/SmallTestFiveCandidates -n 2 --allow-run-as-root
    
     