name: Test env

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - ci/*
jobs:

  build:

    runs-on: ubuntu-latest
    container: 'centos:7'

    steps:
      - uses: actions/checkout@v3
      - run: |
          echo `uname -a`

      - uses: ./.github/actions/test

