name: Ubuntu CI (system libs)

on:
  push:
    branches:
      - main
      - develop
      - features/*
      - feature/*
      - fix/*
      - release/*
  release:
    types: [ created ]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:

  userguide:
    runs-on: ubuntu-latest
    outputs:
      pdf-name: ${{ steps.create-user-guide.outputs.pdf-name }}

    steps:
      - uses: actions/checkout@v2

      - name: Read antares-xpansion version
        id: antares-xpansion-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'antares-version.json'
          prop_path: 'antares_xpansion_version'

      - id: create-user-guide
        name: user guide pdf creation
        uses: ./.github/workflows/generate-userguide-pdf
        with:
          antares-xpansion-version: ${{steps.antares-xpansion-version.outputs.prop}}

      - name: user guide upload
        id: userguide_upload
        uses: actions/upload-artifact@v2
        with:
          name: user-guide
          path: ${{ steps.create-user-guide.outputs.pdf-path }}

  build:

    needs: userguide
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-20.04]
        xprs: [ON, OFF]
    env:
      XPRESSDIR: ${{ github.workspace }}/xpress
      XPRESS: ${{ github.workspace }}/xpress/bin
      XPRS_LIB_Path: ${{ github.workspace }}/xpress/lib

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Checkout xpressmp linux
        uses: actions/checkout@v2
        with:
          repository: rte-france/xpress-mp
          path: ${{ env.XPRESSDIR }}
          ref: master
          token: ${{ secrets.AS_TOKEN }} #reniew token periodically

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}-${{ matrix.xprs }}

      - name: Get release
        if: github.event_name == 'release' && github.event.action == 'created'
        id: get_release
        uses: bruceadams/get-release@v1.2.3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-tests.txt
          pip install -r requirements-ui.txt

      - name: Install mandatory system libraries
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install libjsoncpp-dev libgtest-dev libboost-mpi-dev libboost-program-options-dev libtbb-dev
          cd /usr/src/googletest/
          sudo cmake .
          sudo cmake --build . --target install

      - name: Read antares-solver version
        id: antares-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'antares-version.json'
          prop_path: 'antares_version'

      - name: Read antares-xpansion version
        id: antares-xpansion-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'antares-version.json'
          prop_path: 'antares_xpansion_version'

      - name: Read antares-deps version
        id: antares-deps-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'antares-version.json'
          prop_path: 'antares_deps_version'

      - name: Download pre-compiled librairies
        uses: ./.github/workflows/download-extract-precompiled-libraries-tgz
        with:
          antares-deps-version: ${{steps.antares-deps-version.outputs.prop}}
          antares-version: ${{steps.antares-version.outputs.prop}}
          os: ${{matrix.os}}
          os-full-name: Ubuntu-20.04

      - name: Download userguide
        uses: actions/download-artifact@v2
        with:
          name: user-guide
          path: docs/

      - name: Configure
        shell: bash
        run: |
          cmake -B _build -S . \
                -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
                -DDEPS_INSTALL_DIR=rte-antares-deps-Release \
                -DBUILD_TESTING=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DUSE_MPI=ON \
                -DCMAKE_INSTALL_PREFIX=_install \
                -DBUILD_UI=ON  \
                -DUSER_GUIDE_PATH="docs/${{ needs.userguide.outputs.pdf-name }}" \
                -DXPRESS=${{ matrix.xprs }} \
                -DXPRESS_ROOT=${{ env.XPRESSDIR }}

      - name: Build
        run: |
          cmake --build _build --config Release -j2 --target install

      - name: set name variables
        id: single_file_name
        shell: bash
        run: |
          XPRS=${{ matrix.xprs }}
          [ $XPRS == "ON" ] && WITH_XPRS="-xpress" || WITH_XPRS=""
          VERSION=${{steps.antares-xpansion-version.outputs.prop}}${WITH_XPRS}
          echo "::set-output name=version::$VERSION"
          echo "VERSION_WITH_XPRESS=$VERSION"
          echo "VERSION_WITH_XPRESS=$VERSION" >> $GITHUB_ENV

      - id: create-single-file
        name: Single file .tar.gz creation
        uses: ./.github/workflows/single-file-creation-tgz
        with:
          antares-xpansion-version: ${{env.VERSION_WITH_XPRESS}}

      - name: Installer .tar.gz creation
        run: |
          cd _build
          cpack -G TGZ
          export TGZ_NAME=$(ls *.tar.gz)
          echo "TGZ_NAME=$TGZ_NAME" >> $GITHUB_ENV

      - name: Installer .deb creation
        run: |
          cd _build
          cpack -G DEB
          export DEB_NAME=$(ls *.deb)
          echo "DEB_NAME=$DEB_NAME" >> $GITHUB_ENV

      - name: Upload .tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.TGZ_NAME}}
          path: _build/${{env.TGZ_NAME}}

      - name: Upload .deb
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.DEB_NAME}}
          path: _build/${{env.DEB_NAME}}

      - name: Upload single file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.create-single-file.outputs.archive-name }}
          path: ${{ steps.create-single-file.outputs.archive-path }}

      - name: Running unit tests
        run: |
          cd _build
          ctest -C Release --output-on-failure -L "medium|unit|benders|lpnamer"

      - name: Publish .tar.gz
        if:  github.event_name == 'release' && github.event.action == 'created'
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: _build/${{env.TGZ_NAME}}
          asset_name: ${{env.TGZ_NAME}}
          asset_content_type: application/octet-stream

      - name: Publish .deb
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: _build/${{env.DEB_NAME}}
          asset_name: ${{env.DEB_NAME}}
          asset_content_type: application/octet-stream

      - name: Publish single file
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ steps.create-single-file.outputs.archive-path }}
          asset_name: ${{ steps.create-single-file.outputs.archive-name }}
          asset_content_type: application/octet-stream

