name: Ubuntu CI full build

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - ci/*
jobs:

  build:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-tests.txt
          pip install -r requirements-ui.txt

      - name: Install mandatory system libraries
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install libjsoncpp-dev libgtest-dev libboost-mpi-dev libboost-program-options-dev libtbb-dev
          cd /usr/src/googletest/
          sudo cmake .
          sudo cmake --build . --target install

      - name: Read antares-xpansion version
        id: antares-xpansion-version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'antares-version.json'
          prop_path: 'antares_xpansion_version'

      - name: Configure
        run: |
          cmake -B _build -S . \
                -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
                -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release \
                -DUSE_MPI=ON -DCMAKE_INSTALL_PREFIX=_install \
                -DBUILD_UI=ON

      - name: Build
        run: |
          cmake --build _build --config Release -j2 --target install

      - name: Running unit tests
        run: |
          cd _build
          ctest -C Release --output-on-failure -L "medium|unit|benders|lpnamer"

      - id: create-single-file
        name: Single file .tar.gz creation
        uses: ./.github/workflows/single-file-creation-tgz
        with:
          antares-xpansion-version: ${{steps.antares-xpansion-version.outputs.prop}}

      - name: Installer .tar.gz creation
        run: |
          cd _build
          cpack -G TGZ

      - name: Installer .deb creation
        run: |
          cd _build
          cpack -G DEB

