name: Windows CI (VCPKG)

on:
  push:
    branches:
      - test/vcpkg
jobs:

  windows:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [windows-latest]
        buildtype: [release]
        triplet: [x64-windows]
        
    env:
      # Indicates the location of the vcpkg as a Git submodule of the project repository.
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: true
      


 
          
    - name: Pre-requisites
      shell: cmd
      run: |          
          choco install wget zip unzip --no-progress
          wget -nv https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe
          msmpisetup.exe -unattend

   
        
    - name : Install deps with VCPKG
      run: |
          cd vcpkg
          ./bootstrap-vcpkg.sh
          vcpkg install jsoncpp gtest boost-mpi boost-program-options --triplet ${{matrix.triplet}}
          rm -rf buildtrees
          rm -rf packages
          rm -rf downloads
      shell: bash
        
  